unpackaged/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <label>BOM</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>BOM Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/BOM__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>BOMs</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/BOM__c/fields/Part_Number2__c.field-meta.xml
<CustomField>
    <fullName>Part_Number2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Part Number</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>BOMs</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <formula>Text(Opportunity__r.Financing_Tool__c)</formula>
    <label>Financing Tool</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New-Case Created</fullName>
            </value>
            <value>
                <fullName>Reimburement Under Review</fullName>
            </value>
            <value>
                <fullName>Reimburement Approved</fullName>
            </value>
            <value>
                <fullName>Reimburesment Declined</fullName>
            </value>
            <value>
                <fullName>Roof Review Required</fullName>
            </value>
            <value>
                <fullName>Roof Review Pending Site Visit</fullName>
            </value>
            <value>
                <fullName>Re-Roof Required Pending Quote</fullName>
            </value>
            <value>
                <fullName>Customer Accepted- Pending Coordination</fullName>
            </value>
            <value>
                <fullName>Re-Roof Underway</fullName>
            </value>
            <value>
                <fullName>Re-Roof Complete- Pending JCO</fullName>
            </value>
            <value>
                <fullName>Roof Complete- Ready for invoice</fullName>
            </value>
            <value>
                <fullName>Roof Reviewed- Re-Roof Not Needed</fullName>
            </value>
            <value>
                <fullName>Electrical Review Required</fullName>
            </value>
            <value>
                <fullName>Electrical Review Pending Site Visit</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade Required Pending Quote</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade Pending Utility Disconnect</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade Scheduled</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade at Installation</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade Complete</fullName>
            </value>
            <value>
                <fullName>Electrical Reviewed- No Upgrade Required</fullName>
            </value>
            <value>
                <fullName>Structural Review Required</fullName>
            </value>
            <value>
                <fullName>Structural Review Pending Site Visit</fullName>
            </value>
            <value>
                <fullName>Structural Upgrade Required Pending Quote</fullName>
            </value>
            <value>
                <fullName>Structural Upgrade Scheduled</fullName>
            </value>
            <value>
                <fullName>Structural Upgrade at Installation</fullName>
            </value>
            <value>
                <fullName>Structural Upgrade Complete</fullName>
            </value>
            <value>
                <fullName>Structural Reviewed- No Upgrade Needed</fullName>
            </value>
            <value>
                <fullName>Trenching Review Required</fullName>
            </value>
            <value>
                <fullName>Trenching Review Pending Site Visit</fullName>
            </value>
            <value>
                <fullName>Trenching Required Pending Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Utility__c.field-meta.xml
<CustomField>
    <fullName>Utility__c</fullName>
    <formula>TEXT ( Opportunity__r.Utility__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Utility</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Supply_Chain.recordType-meta.xml
<RecordType>
    <fullName>Supply_Chain</fullName>
    <active>true</active>
    <businessProcess>Design Process</businessProcess>
    <label>Supply Chain</label>
</RecordType>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Utility__c.field-meta.xml
<CustomField>
    <fullName>Utility__c</fullName>
    <formula>TEXT(Opportunity__r.Utility__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Utility</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Design.recordType-meta.xml
<RecordType>
    <fullName>Design</fullName>
    <active>true</active>
    <label>Site Approval</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Financing.recordType-meta.xml
<RecordType>
    <fullName>Financing</fullName>
    <active>true</active>
    <label>Financing</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Installation_Scheduling.recordType-meta.xml
<RecordType>
    <fullName>Installation_Scheduling</fullName>
    <active>true</active>
    <label>Installation Scheduling</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Interconnection.recordType-meta.xml
<RecordType>
    <fullName>Interconnection</fullName>
    <active>true</active>
    <label>Interconnection</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Permitting.recordType-meta.xml
<RecordType>
    <fullName>Permitting</fullName>
    <active>true</active>
    <label>Permitting</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/PTO.recordType-meta.xml
<RecordType>
    <fullName>PTO</fullName>
    <active>true</active>
    <label>PTO</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/State_Certification.recordType-meta.xml
<RecordType>
    <fullName>State_Certification</fullName>
    <active>true</active>
    <label>State Certification</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Supply_Chain.recordType-meta.xml
<RecordType>
    <fullName>Supply_Chain</fullName>
    <active>true</active>
    <label>Supply Chain</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Milestone__c/fields/Contract_Received_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Milestone__c</fullName>
    <label>Contract Received - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Contract_Signed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_Milestone__c</fullName>
    <label>Contract Signed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Design_Completed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Design_Completed_Milestone__c</fullName>
    <label>Design Completed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Design_Queued_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Design_Queued_Milestone__c</fullName>
    <label>Design Queued - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Energy_Bill_checked__c.field-meta.xml
<CustomField>
    <fullName>Energy_Bill_checked__c</fullName>
    <label>Usage Verification Complete</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Inspection_Complete_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Complete_Milestone__c</fullName>
    <label>Inspection Complete - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Installation_Completed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Installation_Completed_Milestone__c</fullName>
    <label>Installation Completed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Permit_Submitted_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Permit_Submitted_Milestone__c</fullName>
    <label>Permit Submitted - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Survey_Complete_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Survey_Complete_Confirmed__c</fullName>
    <label>Survey Complete Confirmed</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/RadiusHandlerTest.cls
@isTest
public with sharing class RadiusHandlerTest {
    @TestSetup
    static void setup(){
        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account anAccount = TestDataFactory.createAccount('Palmetto Acc', designSalesId);
        INSERT anAccount;
        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity anOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', anAccount.Id, '1. Appointment Set', 'Alabama');
        anOpportunity.Utility__c = 'Austin Energy';
        INSERT anOpportunity;
        
        TriggerConfiguration__c aTriggerConfiguration = new TriggerConfiguration__c(Name= 'Order API Trigger',Active__c = true);
        INSERT aTriggerConfiguration;

        Product2 aProduct = new Product2();
        aProduct.Name = 'PV-000001';
        aProduct.ProductCode = 'PV-000001';
        INSERT aProduct;

        BOM__c aBom = new BOM__c();
        aBom.Opportunity__c = anOpportunity.Id;
        aBom.Part_Number2__c = aProduct.Id;
        INSERT aBom;

    }
    @IsTest
    static void unitTest1(){
        

        Project_Milestone__c aProjectMilestone = [
            SELECT Id 
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Test.startTest();
        aProjectMilestone.Survey_Complete_Confirmed__c = Datetime.now().addDays(1);
        aProjectMilestone.Energy_Bill_checked__c = Datetime.now();
        aProjectMilestone.Contract_Received_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        Project_Milestone__c verifyMilestone = [
            SELECT Id, Design_Queued_Milestone__c, Survey_Complete_Confirmed__c
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        System.assertEquals(verifyMilestone.Survey_Complete_Confirmed__c, verifyMilestone.Design_Queued_Milestone__c);
    }

    @IsTest
    static void unitTest2(){
        Project_Milestone__c aProjectMilestone = [
            SELECT Id, Design_Queued_Milestone__c
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Opportunity anOpportunity = [
            SELECT Id
            FROM Opportunity
            WHERE Name = 'Palmetto Acc - Opportunity'
        ];

        Test.startTest();
        anOpportunity.Financing_Tool__c = 'Sunlight';
        UPDATE anOpportunity;
        aProjectMilestone.Design_Queued_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJob = [
            SELECT Id
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND (RecordType.DeveloperName = 'Design' OR RecordType.DeveloperName = 'Financing')
        ];
        
        System.assertEquals(2, verifyJob.size());
        
    }

    @IsTest
    static void unitTest3(){
        Project_Milestone__c aProjectMilestone = [
            SELECT Id, Design_Queued_Milestone__c
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Test.startTest();
        aProjectMilestone.Design_Completed_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJob = [
            SELECT Id
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND RecordType.DeveloperName = 'Permitting'
        ];
        
        System.assertEquals(1, verifyJob.size());
    }

    @IsTest
    static void unitTest4(){
        Opportunity anOpportunity = [
            SELECT Id
            FROM Opportunity
            WHERE Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Id supplyChainId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Supply_Chain').getRecordTypeId();   
        Job__c supplyChainJob = new Job__c();
        supplyChainJob.RecordTypeId = supplyChainId;
        supplyChainJob.Opportunity__c = anOpportunity.Id;
        INSERT supplyChainJob;

        Project_Milestone__c aProjectMilestone = [
            SELECT Id, Design_Queued_Milestone__c
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Test.startTest();
        aProjectMilestone.Design_Completed_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJob = [
            SELECT Id, Flow_Status__c
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND RecordType.DeveloperName = 'Supply_Chain'
        ];
        
        System.assertEquals('Design / BOM Complete', verifyJob[0].Flow_Status__c);
    }

    @IsTest
    static void unitTest5(){
        Project_Milestone__c aProjectMilestone = [
            SELECT Id, Design_Queued_Milestone__c
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Test.startTest();
        aProjectMilestone.Permit_Submitted_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJob = [
            SELECT Id
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND RecordType.DeveloperName = 'Installation_Scheduling'
        ];
        
        System.assertEquals(1, verifyJob.size());
    }

    @IsTest
    static void unitTest6(){
        Project_Milestone__c aProjectMilestone = [
            SELECT Id, Design_Queued_Milestone__c
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Test.startTest();
        aProjectMilestone.Installation_Completed_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJob = [
            SELECT Id
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND RecordType.DeveloperName = 'Inspection'
        ];
        
        System.assertEquals(1, verifyJob.size());
    }

    @IsTest
    static void unitTest7(){
        Opportunity anOpportunity = [
            SELECT Id
            FROM Opportunity
            WHERE Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Id supplyChainId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Supply_Chain').getRecordTypeId();   
        Job__c supplyChainJob = new Job__c();
        supplyChainJob.RecordTypeId = supplyChainId;
        supplyChainJob.Opportunity__c = anOpportunity.Id;
        INSERT supplyChainJob;

        Project_Milestone__c aProjectMilestone = [
            SELECT Id, Design_Queued_Milestone__c
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Test.startTest();
        aProjectMilestone.Installation_Completed_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJob = [
            SELECT Id, Flow_Status__c
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND RecordType.DeveloperName = 'Supply_Chain'
        ];
        
        System.assertEquals('Fulfilled', verifyJob[0].Flow_Status__c);
    }

    @IsTest
    static void unitTest8(){
        Project_Milestone__c aProjectMilestone = [
            SELECT Id, Design_Queued_Milestone__c
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Test.startTest();
        aProjectMilestone.Contract_Signed_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJob = [
            SELECT Id
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND RecordType.DeveloperName = 'Supply_Chain'
        ];
        
        System.assertEquals(1, verifyJob.size());
    }

    @IsTest
    static void unitTest9(){
        Opportunity anOpportunity = [
            SELECT Id
            FROM Opportunity
            WHERE Name = 'Palmetto Acc - Opportunity'
        ];
        
        Project_Milestone__c aProjectMilestone = [
            SELECT Id, Design_Queued_Milestone__c
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Test.startTest();
        aProjectMilestone.Inspection_Complete_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJob = [
            SELECT Id
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND RecordType.DeveloperName = 'PTO'
        ];
        
        System.assertEquals(1, verifyJob.size());
    }

    @IsTest
    static void unitTest10(){
        Project_Milestone__c aProjectMilestone = [
            SELECT Id
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Opportunity anOpportunity = [
            SELECT Id
            FROM Opportunity
            WHERE Name = 'Palmetto Acc - Opportunity'
        ];

        Test.startTest();
        aProjectMilestone.Permit_Received_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Case> verifyCaseList = [
            SELECT Id 
            FROM CASE
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
        ];

        System.assertEquals(2, verifyCaseList.size());
        
    }

    @IsTest
    static void unitTest11(){
        Project_Milestone__c aProjectMilestone = [
            SELECT Id
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Opportunity anOpportunity = [
            SELECT Id
            FROM Opportunity
            WHERE Name = 'Palmetto Acc - Opportunity'
        ];

        anOpportunity.Inverter_1__c = 'Test';
        UPDATE anOpportunity;
        
        BOM__c aBom = [
            SELECT Id
            FROM BOM__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            LIMIT 1
        ];

        Product2 aProduct = new Product2();
        aProduct.Name = 'IN-000002';
        aProduct.ProductCode = 'IN-000002';
        INSERT aProduct;

        aBom.Part_Number2__c = aProduct.Id;
        UPDATE aBom;

        Test.startTest();
        aProjectMilestone.Permit_Received_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Case> verifyCaseList = [
            SELECT Id, Subject
            FROM Case
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
        ];

        System.assertEquals(3, verifyCaseList.size());
        
    }
    
    @IsTest
    static void unitTest12(){
        List<Project_Milestone__c> projectMilestones = [
            SELECT Id
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
        ];
        
        Project_Milestone__c aProjectMilestone = projectMilestones[0];
        aProjectMilestone.All_Documentation_Reviewed_and_Confirmed__c = Datetime.now();
        UPDATE aProjectMilestone;
        
        Test.startTest();
        aProjectMilestone.Design_Completed_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJobList = [
            SELECT Id
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND RecordType.DeveloperName = 'Interconnection'
        ];

        System.assertEquals(1, verifyJobList.size());
    }

    @IsTest
    static void testStateCertificationJobCreation(){
        List<Project_Milestone__c> projectMilestones = [
            SELECT Id
            FROM Project_Milestone__c 
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
        ];
        
        Project_Milestone__c aProjectMilestone = projectMilestones[0];
        
        Test.startTest();
        aProjectMilestone.Design_Completed_Milestone__c = Datetime.now();
        UPDATE aProjectMilestone;
        Test.stopTest();

        List<Job__c> verifyJobList = [
            SELECT Id
            FROM Job__c
            WHERE Opportunity__r.Name = 'Palmetto Acc - Opportunity'
            AND RecordType.DeveloperName = 'State_Certification'
        ];

        System.assertEquals(1, verifyJobList.size());
    }
}