unpackaged/main/default/objects/Contract/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Inverter_1__c.field-meta.xml
<CustomField>
    <fullName>Inverter_1__c</fullName>
    <label>Inverter 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SolarEdge SE3000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE3800H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE5000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE6000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE7600H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE10000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE11400A-US</fullName>
            </value>
            <value>
                <fullName>SE9KUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Inverter_2__c.field-meta.xml
<CustomField>
    <fullName>Inverter_2__c</fullName>
    <label>Inverter 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SolarEdge SE3000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE3800H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE5000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE6000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE7600H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE10000A-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE11400A-US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Number_of_Solar_Panels__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Solar_Panels__c</fullName>
    <label>Number of Solar Panels</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Authority_Having_Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Authority_Having_Jurisdiction__c</fullName>
    <description>TigerWeb/Alchemy Integrated</description>
    <label>Authority Having Jurisdiction</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Inverter_1__c.field-meta.xml
<CustomField>
    <fullName>Inverter_1__c</fullName>
    <label>Inverter 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SolarEdge SE3000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE3800H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE5000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE6000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE7600H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE10000H-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE11400A-US</fullName>
            </value>
            <value>
                <fullName>SE9KUS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Inverter_2__c.field-meta.xml
<CustomField>
    <fullName>Inverter_2__c</fullName>
    <label>Inverter 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SolarEdge SE3000A-US</fullName>
                <label>SolarEdge SE3000H-US</label>
            </value>
            <value>
                <fullName>SolarEdge SE3800A-US</fullName>
                <label>SolarEdge SE3800H-US</label>
            </value>
            <value>
                <fullName>SolarEdge SE5000A-US</fullName>
                <label>SolarEdge SE5000H-US</label>
            </value>
            <value>
                <fullName>SolarEdge SE6000A-US</fullName>
                <label>SolarEdge SE6000H-US</label>
            </value>
            <value>
                <fullName>SolarEdge SE7600A-US</fullName>
                <label>SolarEdge SE7600H-US</label>
            </value>
            <value>
                <fullName>SolarEdge SE10000A-US</fullName>
            </value>
            <value>
                <fullName>SolarEdge SE11400A-US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Number_of_Solar_Panels__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Solar_Panels__c</fullName>
    <inlineHelpText>Source of truth is Alchemy</inlineHelpText>
    <label>Number of Solar Panels</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/of_Solar_Panels__c.field-meta.xml
<CustomField>
    <fullName>of_Solar_Panels__c</fullName>
    <label># of Panels</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Open_Retention_Case__c.field-meta.xml
<CustomField>
    <fullName>Open_Retention_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open Retention Case?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>Contact__r.Phone</formula>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PermitJobOpportunityController.cls
public with sharing class PermitJobOpportunityController {
    @AuraEnabled(cacheable=true)
    public static Opportunity getOpportunities(Id recordId) {
        return [
            SELECT Id, Authority_Having_Jurisdiction__c, of_Solar_Panels__c, Email__c, Phone__c, Open_Retention_Case__c,
                Inverter_1__c, Inverter_2__c, Contract.Amount__c, Number_of_Solar_Panels__c,
                (
                    SELECT Id, Name, Url
                    FROM GoogleDocs
                ),
                (
                    SELECT Id, Name, dsfs__DocuSign_Envelope_ID__c
                    FROM dsfs__R00N80000002fD9vEAE__r
                )
            FROM Opportunity
            WHERE Id IN (SELECT Opportunity__c FROM Job__c WHERE ID = :recordId)
            LIMIT 1
        ];
    }
}