unpackaged/main/default/objects/Account/fields/Accountreferral__c.field-meta.xml
<CustomField>
    <fullName>Accountreferral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associated referred accounts.</description>
    <label>Ambassador</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ambassador Program</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Referral_By_Code__c.field-meta.xml
<CustomField>
    <fullName>Referral_By_Code__c</fullName>
    <label>Referral By Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Referral_Code__c.field-meta.xml
<CustomField>
    <fullName>Referral_Code__c</fullName>
    <label>Referral Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Account_TriggerHandler.cls
public class Account_TriggerHandler {
    public static void AccountRefferal(list<Account> Acct)
    {
        Map<String, Id> AccountMap = new Map<String, Id>();         
        for(Account acmap : [select Referral_Code__c,id from Account where Referral_Code__c != ''])
        {
            AccountMap.put(acmap.Referral_Code__c,acmap.Id);
        }
        for(Account newac : Acct)
        {
            if(AccountMap.containskey(newac.Referral_By_Code__c) && newac.Referral_By_Code__c != '')
            {
                newac.Accountreferral__c = AccountMap.get(newac.Referral_By_Code__c);
            }
        }
    }
}