unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential - Customer</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Architects, Developers and Land Planners</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Brokerage Co.</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Contractor</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Homebuilder</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Property Manager</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Architects, Developers and Land Planners</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Contractor</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Homebuilder</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Property Manager</fullName>
            </value>
            <value>
                <fullName>Commercial - Customer</fullName>
            </value>
            <value>
                <fullName>Investor - Corporate Debt</fullName>
            </value>
            <value>
                <fullName>Investor - Corporate Equity</fullName>
            </value>
            <value>
                <fullName>Investor - Corporate Other</fullName>
            </value>
            <value>
                <fullName>Investor - Property Debt</fullName>
            </value>
            <value>
                <fullName>Investor - Property Equity</fullName>
            </value>
            <value>
                <fullName>Investor - Property Other</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Array (entire system)</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Debt</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Sponsor Equity</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Tax Equity</fullName>
            </value>
            <value>
                <fullName>Sunrun Installation</fullName>
            </value>
            <value>
                <fullName>Utility - Customer</fullName>
            </value>
            <value>
                <fullName>Business Development - REIT</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Build Only</fullName>
            </value>
            <value>
                <fullName>Ambassador</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

unpackaged/main/default/objects/Dealer_Fee_Product__c/Dealer_Fee_Product__c.object-meta.xml
<CustomObject>
    <label>Dealer Fee Product</label>
    <nameField>
        <label>Dealer Fee Product	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Fee Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Dealer_Fee_Product__c/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Dealer_Fee_Product__c/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Auto populates the "Close Date"date that only the Project Admin/Coordinator (currently Sid) or Project Manager (currently Kevin) can check.</description>
    <label>Contract Received Confirmed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed_Date__c</fullName>
    <label>Contract Received Confirmed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential - Customer</fullName>
                <default>true</default>
                <label>Residential - Customer</label>
            </value>
            <value>
                <fullName>Alchemy</fullName>
            </value>
            <value>
                <fullName>Build Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Engineering_Created__c.field-meta.xml
<CustomField>
    <fullName>Engineering_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BOM Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Final_Design_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Design_Created_Date__c</fullName>
    <label>BOM Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lead_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Type__c</fullName>
    <label>Lead Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>Self-Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Number_of_Arrays__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Arrays__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Number of Arrays</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Number_of_Solar_Panels__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Solar_Panels__c</fullName>
    <inlineHelpText>Source of truth is Alchemy</inlineHelpText>
    <label>Number of Solar Panels</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Proposal_Created__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proposal Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X3rd_Party_Partner__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Partner__c</fullName>
    <label>3rd Party Partner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100 better built</fullName>
            </value>
            <value>
                <fullName>10x Solutions LLC</fullName>
            </value>
            <value>
                <fullName>1nnov8tive LLC</fullName>
            </value>
            <value>
                <fullName>1UP Solar</fullName>
            </value>
            <value>
                <fullName>1UP Solar LLC</fullName>
            </value>
            <value>
                <fullName>25th Hour Solutions LLC</fullName>
            </value>
            <value>
                <fullName>320 Solar LLC</fullName>
            </value>
            <value>
                <fullName>361 Technologies LLC</fullName>
            </value>
            <value>
                <fullName>365 Solar Energy</fullName>
            </value>
            <value>
                <fullName>3rd Rock Solar Discounters</fullName>
            </value>
            <value>
                <fullName>413Solar</fullName>
            </value>
            <value>
                <fullName>413Solar LLC</fullName>
            </value>
            <value>
                <fullName>4Season Real Estate Solutions LLC</fullName>
            </value>
            <value>
                <fullName>528 Lumen</fullName>
            </value>
            <value>
                <fullName>A3nergy Solutions</fullName>
            </value>
            <value>
                <fullName>ABC PRO GRP, LLC</fullName>
            </value>
            <value>
                <fullName>Absolute Sustainability LLC</fullName>
            </value>
            <value>
                <fullName>Active Care Connections</fullName>
            </value>
            <value>
                <fullName>Adorno Consulting LLC</fullName>
            </value>
            <value>
                <fullName>Advanced Exteriors, LLC</fullName>
            </value>
            <value>
                <fullName>Advanced Exteriors LLC</fullName>
            </value>
            <value>
                <fullName>Advisors Solar Group Inc.</fullName>
            </value>
            <value>
                <fullName>AE Contracting Services LLC</fullName>
            </value>
            <value>
                <fullName>AE Solar</fullName>
            </value>
            <value>
                <fullName>Ageint Security</fullName>
            </value>
            <value>
                <fullName>Alamo Smart Home</fullName>
            </value>
            <value>
                <fullName>Aligned Energy Partners</fullName>
            </value>
            <value>
                <fullName>Alliance Service Professionals LLC</fullName>
            </value>
            <value>
                <fullName>All in One Exterior and Construction</fullName>
            </value>
            <value>
                <fullName>Aloha Sun Power</fullName>
            </value>
            <value>
                <fullName>Harbor Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateDealerProductTest.cls
@isTest
private class BatchToUpdateDealerProductTest
{
    static testMethod void unitTest(){
        string account_recordtype_id = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Residential - Customer').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Harbor Energy',account_recordtype_id);
        insert objAccount;
        
        Contact objContact = TestDataFactory.createContact('Vanit', 'Jain', objAccount.Id);
        insert objContact;
    
        string opp_recordtype_id = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(opp_recordtype_id, 'Test 2', objAccount.id, '7a. Contract Received Confirmed', 'Alabama');
        objOpportunity.LeadSource = '3rd Party Provider';
        objOpportunity.Lead_Source_Type__c = 'Channel';
        objOpportunity.Customer_Type__c = 'Residential - Customer';
        objOpportunity.Financing_Tool__c  = 'Sunlight';
        objOpportunity.X3rd_Party_Partner__c = 'Harbor Energy';
        objOpportunity.Loan_Term__c = '20';
        objOpportunity.Proposal_Created__c = true;
        objOpportunity.Engineering_Created__c = true;
        objOpportunity.Final_Design_Created_Date__c = system.Date.today();
        objOpportunity.Number_of_Arrays__c = 1;
        objOpportunity.Contract_Received_Confirmed__c= true;
        objOpportunity.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-5);
        objOpportunity.Amount = 30000;
        objOpportunity.Number_of_Solar_Panels__c  = 25;
        objOpportunity.Panel_Type__c = 'Q.PEAK-G4.1 300';
        objOpportunity.Panel_Wattage__c = 300;
        objOpportunity.Test_Account__c = false;
        objOpportunity.Contact__c = objContact.Id;
        objOpportunity.APR__c = '3.49%';
        objOpportunity.Location__c = 'New Jersey';
        objOpportunity.Contract_Received_Date__c = Date.newInstance(2020, 1, 1);
        insert objOpportunity;
        
        objOpportunity = TestDataFactory.createOpportunity(opp_recordtype_id, 'Test 2', objAccount.id, '7a. Contract Received Confirmed', 'Alabama');
        objOpportunity.LeadSource = '3rd Party Provider';
        objOpportunity.Lead_Source_Type__c = 'Channel';
        objOpportunity.Customer_Type__c = 'Residential - Customer';
        objOpportunity.Financing_Tool__c  = 'Cash';
        objOpportunity.X3rd_Party_Partner__c = 'Harbor Energy';
        objOpportunity.Loan_Term__c = '20';
        objOpportunity.Proposal_Created__c = true;
        objOpportunity.Engineering_Created__c = true;
        objOpportunity.Final_Design_Created_Date__c = system.Date.today();
        objOpportunity.Number_of_Arrays__c = 1;
        objOpportunity.Contract_Received_Confirmed__c= true;
        objOpportunity.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-5);
        objOpportunity.Amount = 30000;
        objOpportunity.Number_of_Solar_Panels__c  = 25;
        objOpportunity.Panel_Type__c = 'Q.PEAK-G4.1 300';
        objOpportunity.Panel_Wattage__c = 300;
        objOpportunity.Test_Account__c = false;
        objOpportunity.Contact__c = objContact.Id;
        objOpportunity.APR__c = '3.49%';
        objOpportunity.Location__c = 'New Jersey';
        objOpportunity.Contract_Received_Date__c = Date.newInstance(2020, 1, 1);
        insert objOpportunity;
    
        Dealer_Fee_Product__c objProduct = new Dealer_Fee_Product__c();
        objProduct.State__c = 'New Jersey';
        objProduct.APR__c = '3.49%';
        objProduct.Financing_Tool__c = 'Sunlight';
        objProduct.Classification__c = 'Internal';
        objProduct.Loan_Term__c = '20';
        insert objProduct;
        
        objProduct = new Dealer_Fee_Product__c();
        objProduct.State__c = 'New Jersey';
        objProduct.APR__c = '3.49%';
        objProduct.Financing_Tool__c = 'Cash';
        objProduct.Classification__c = 'Internal';
        objProduct.Loan_Term__c = '20';
        insert objProduct;
        
        Database.executeBatch(new BatchToUpdateDealerProduct());
    }
}