unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential - Customer</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Architects, Developers and Land Planners</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Brokerage Co.</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Contractor</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Homebuilder</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Property Manager</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Architects, Developers and Land Planners</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Contractor</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Homebuilder</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Property Manager</fullName>
            </value>
            <value>
                <fullName>Commercial - Customer</fullName>
            </value>
            <value>
                <fullName>Investor - Corporate Debt</fullName>
            </value>
            <value>
                <fullName>Investor - Corporate Equity</fullName>
            </value>
            <value>
                <fullName>Investor - Corporate Other</fullName>
            </value>
            <value>
                <fullName>Investor - Property Debt</fullName>
            </value>
            <value>
                <fullName>Investor - Property Equity</fullName>
            </value>
            <value>
                <fullName>Investor - Property Other</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Array (entire system)</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Debt</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Sponsor Equity</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Tax Equity</fullName>
            </value>
            <value>
                <fullName>Sunrun Installation</fullName>
            </value>
            <value>
                <fullName>Utility - Customer</fullName>
            </value>
            <value>
                <fullName>Business Development - REIT</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Build Only</fullName>
            </value>
            <value>
                <fullName>Ambassador</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Appointment_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_and_Time__c</fullName>
    <label>Appointment Date and Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential - Customer</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>Residential - Customer</label>
            </value>
            <value>
                <fullName>Alchemist</fullName>
            </value>
            <value>
                <fullName>Build Partner</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Surveyor</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/testLeadEventProcess.cls
@isTest
private class testLeadEventProcess {
   
   @testSetup static void setupUpdateLeads() {
       List<lead> leadList = New List<lead>();
           for(integer i = 1; i < 101; i++){
               leadlist.add(
                   new lead(
                       company='update test account ' + i,
                       phone='555-555-5555',
                       street='123 Anywhere',
                       lastName = 'udtestingName' + i,
                       Appointment_Date_and_Time__c = system.now().addDays(i),
                       Customer_Type__c = 'Utility - Customer'
                   )
               
               );
           } 
       insert leadlist;
   }


    static testMethod void testInsert(){
       Test.startTest();
       List<lead> leadList = New List<lead>();
           for(integer i = 1; i < 101; i++){
               leadlist.add(
                   new lead(
                       company='testing account ' + i,
                       phone='555-555-5555',
                       street='123 Anywhere',
                       lastName = 'testingName' + i,
                       Appointment_Date_and_Time__c = system.now().addDays(i),
                       Customer_Type__c = 'Utility - Customer'
                   )
               
               );
           } 
       insert leadlist;
       Test.stopTest();
       
   
   }
   
   static testMethod void testupdate(){
       
       List<lead> leadList = New List<lead>([Select Id, company, lastName, Appointment_Date_and_Time__c, Customer_Type__c from Lead where lastName like '%udtestingName%']);
            
       Test.startTest();
       for(lead l : leadlist){
           l.Appointment_Date_and_Time__c = l.Appointment_Date_and_Time__c.addHours(1);
       }
       update leadlist;
       Test.stopTest();
       
   
   }
   
   static testMethod void testupdateB(){
       
       List<lead> leadList = New List<lead>();
           for(integer i = 1; i < 101; i++){
               leadlist.add(
                   new lead(
                       company='testing account ' + i,
                       phone='555-555-5555',
                       street='123 Anywhere',
                       lastName = 'testingName' + i,
                       Customer_Type__c = 'Utility - Customer'
                   )
               
               );
       } 
       insert leadlist;
       Test.startTest();
       for(lead l : leadlist){
           l.Appointment_Date_and_Time__c = system.now().addDays(2);
       }
       update leadlist;
       Test.stopTest();
       
   
   }
   
}