unpackaged/main/default/objects/Account/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential - Customer</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Architects, Developers and Land Planners</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Brokerage Co.</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Contractor</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Homebuilder</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Property Manager</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Architects, Developers and Land Planners</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Contractor</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Homebuilder</fullName>
            </value>
            <value>
                <fullName>Commercial Channel Partner - Property Manager</fullName>
            </value>
            <value>
                <fullName>Commercial - Customer</fullName>
            </value>
            <value>
                <fullName>Investor - Corporate Debt</fullName>
            </value>
            <value>
                <fullName>Investor - Corporate Equity</fullName>
            </value>
            <value>
                <fullName>Investor - Corporate Other</fullName>
            </value>
            <value>
                <fullName>Investor - Property Debt</fullName>
            </value>
            <value>
                <fullName>Investor - Property Equity</fullName>
            </value>
            <value>
                <fullName>Investor - Property Other</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Array (entire system)</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Debt</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Sponsor Equity</fullName>
            </value>
            <value>
                <fullName>Investor - Solar Tax Equity</fullName>
            </value>
            <value>
                <fullName>Sunrun Installation</fullName>
            </value>
            <value>
                <fullName>Utility - Customer</fullName>
            </value>
            <value>
                <fullName>Business Development - REIT</fullName>
            </value>
            <value>
                <fullName>Residential Channel Partner - Build Only</fullName>
            </value>
            <value>
                <fullName>Ambassador</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Test_Account__c.field-meta.xml
<CustomField>
    <fullName>Test_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Auto populates the "Close Date"date that only the Project Admin/Coordinator (currently Sid) or Project Manager (currently Kevin) can check.</description>
    <label>Contract Received Confirmed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed_Date__c</fullName>
    <label>Contract Received Confirmed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential - Customer</fullName>
                <default>true</default>
                <label>Residential - Customer</label>
            </value>
            <value>
                <fullName>Alchemy</fullName>
            </value>
            <value>
                <fullName>Build Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Engineering_Created__c.field-meta.xml
<CustomField>
    <fullName>Engineering_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BOM Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Final_Design_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Design_Created_Date__c</fullName>
    <label>BOM Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lead_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Type__c</fullName>
    <label>Lead Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>Self-Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Number_of_Arrays__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Arrays__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Number of Arrays</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Number_of_Solar_Panels__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Solar_Panels__c</fullName>
    <inlineHelpText>Source of truth is Alchemy</inlineHelpText>
    <label>Number of Solar Panels</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opp_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Opp_Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Do NOT designate CUSTOMER contact.</inlineHelpText>
    <label>Opp Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Opp Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Panel_Type__c.field-meta.xml
<CustomField>
    <fullName>Panel_Type__c</fullName>
    <label>Panel Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LG 310N1C-G4</fullName>
            </value>
            <value>
                <fullName>LG 320 Black/Black</fullName>
            </value>
            <value>
                <fullName>LG335N1C-A5</fullName>
            </value>
            <value>
                <fullName>LG 335W</fullName>
            </value>
            <value>
                <fullName>LG 360W</fullName>
            </value>
            <value>
                <fullName>Q-Peak G4.1 305</fullName>
            </value>
            <value>
                <fullName>Q.PEAK Duo BLK-G5 310</fullName>
            </value>
            <value>
                <fullName>Q.PEAK-G4.1 300</fullName>
            </value>
            <value>
                <fullName>Q Cells 310W Q.Peak Duo</fullName>
            </value>
            <value>
                <fullName>Silfab 300W - All black</fullName>
            </value>
            <value>
                <fullName>Trina 300TSM-DD05A.08(II)</fullName>
            </value>
            <value>
                <fullName>Axitec 300 AXIblackpremium</fullName>
            </value>
            <value>
                <fullName>Yingli 310D-30b</fullName>
            </value>
            <value>
                <fullName>Hanwha 315w</fullName>
            </value>
            <value>
                <fullName>330W All Black Module</fullName>
            </value>
            <value>
                <fullName>Qcell 340W</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Panel_Wattage__c.field-meta.xml
<CustomField>
    <fullName>Panel_Wattage__c</fullName>
    <inlineHelpText>Source of truth is Alchemy</inlineHelpText>
    <label>Panel Wattage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Proposal_Created__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proposal Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Test_Account__c.field-meta.xml
<CustomField>
    <fullName>Test_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Test Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X3rd_Party_Partner__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Partner__c</fullName>
    <label>3rd Party Partner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100 better built</fullName>
            </value>
            <value>
                <fullName>10x Solutions LLC</fullName>
            </value>
            <value>
                <fullName>1nnov8tive LLC</fullName>
            </value>
            <value>
                <fullName>1UP Solar</fullName>
            </value>
            <value>
                <fullName>1UP Solar LLC</fullName>
            </value>
            <value>
                <fullName>25th Hour Solutions LLC</fullName>
            </value>
            <value>
                <fullName>320 Solar LLC</fullName>
            </value>
            <value>
                <fullName>361 Technologies LLC</fullName>
            </value>
            <value>
                <fullName>365 Solar Energy</fullName>
            </value>
            <value>
                <fullName>3rd Rock Solar Discounters</fullName>
            </value>
            <value>
                <fullName>413Solar</fullName>
            </value>
            <value>
                <fullName>413Solar LLC</fullName>
            </value>
            <value>
                <fullName>4Season Real Estate Solutions LLC</fullName>
            </value>
            <value>
                <fullName>528 Lumen</fullName>
            </value>
            <value>
                <fullName>A3nergy Solutions</fullName>
            </value>
            <value>
                <fullName>ABC PRO GRP, LLC</fullName>
            </value>
            <value>
                <fullName>Absolute Sustainability LLC</fullName>
            </value>
            <value>
                <fullName>Active Care Connections</fullName>
            </value>
            <value>
                <fullName>Adorno Consulting LLC</fullName>
            </value>
            <value>
                <fullName>Advanced Exteriors, LLC</fullName>
            </value>
            <value>
                <fullName>Advanced Exteriors LLC</fullName>
            </value>
            <value>
                <fullName>Advisors Solar Group Inc.</fullName>
            </value>
            <value>
                <fullName>AE Contracting Services LLC</fullName>
            </value>
            <value>
                <fullName>AE Solar</fullName>
            </value>
            <value>
                <fullName>Ageint Security</fullName>
            </value>
            <value>
                <fullName>Alamo Smart Home</fullName>
            </value>
            <value>
                <fullName>Aligned Energy Partners</fullName>
            </value>
            <value>
                <fullName>Alliance Service Professionals LLC</fullName>
            </value>
            <value>
                <fullName>All in One Exterior and Construction</fullName>
            </value>
            <value>
                <fullName>Aloha Sun Power</fullName>
            </value>
            <value>
                <fullName>Harbor Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PopulateChannelPartnerTest.cls
@isTest
private class PopulateChannelPartnerTest
{
    static testMethod void unitTest(){
        String account_recordtype_id = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Residential - Customer').getRecordTypeId();
        Account acc = TestDataFactory.createAccount('Harbor Energy',account_recordtype_id);
        insert acc;
        
        Contact cont = TestDataFactory.createContact('Test','O1', acc.id);
        cont.Title = 'Leadership';
        cont.email = 'test1@gmai.com';
        insert cont;
        
        string opp_recordtype_id = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity opp_1 = TestDataFactory.createOpportunity(opp_recordtype_id, 'Test 2', acc.id, '7a. Contract Received Confirmed', 'Alabama');
        opp_1.LeadSource = '3rd Party Provider';
        opp_1.Lead_Source_Type__c = 'Channel';
        opp_1.Customer_Type__c = 'Residential - Customer';
        opp_1.Financing_Tool__c = 'Sunlight';
        opp_1.X3rd_Party_Partner__c = 'Harbor Energy';
        opp_1.Loan_Term__c = '20';
        opp_1.Proposal_Created__c = true;
        opp_1.Engineering_Created__c = true;
        opp_1.Final_Design_Created_Date__c = system.Date.today();
        opp_1.Number_of_Arrays__c = 1;
        opp_1.Contract_Received_Confirmed__c= true;
        opp_1.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-5);
        opp_1.Amount = 30000;
        opp_1.Number_of_Solar_Panels__c  = 25;
        opp_1.Panel_Type__c = 'Q.PEAK-G4.1 300';
        opp_1.Panel_Wattage__c = 300;
        opp_1.Test_Account__c = false;
        opp_1.Opp_Primary_Contact__c = cont.Id;
        insert opp_1;
        
        Database.executeBatch(new PopulateChannelPartner());
    }
}