unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Service_Agreement__c/Service_Agreement__c.object-meta.xml
<CustomObject>
    <label>Service Agreement</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Service Agreement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Agreement__c/fields/Active_MSA_Flag__c.field-meta.xml
<CustomField>
    <fullName>Active_MSA_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active MSA Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Service_Agreement__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Service Agreements</relationshipLabel>
    <relationshipName>Service_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Vendor__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Interview Complete</fullName>
            </value>
            <value>
                <fullName>App Complete</fullName>
            </value>
            <value>
                <fullName>Doc Review</fullName>
            </value>
            <value>
                <fullName>Docs Failed</fullName>
            </value>
            <value>
                <fullName>MSA Signed</fullName>
            </value>
            <value>
                <fullName>Ready for Orientation</fullName>
            </value>
            <value>
                <fullName>Ready to Schedule</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved not Active</fullName>
            </value>
            <value>
                <fullName>Do not Schedule</fullName>
            </value>
            <value>
                <fullName>Off Boarded</fullName>
            </value>
            <value>
                <fullName>Docs Approved</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Do Not Contact</fullName>
            </value>
            <value>
                <fullName>Pending Background Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ServiceAgreementHandlerTest.cls
@isTest(seeAllData=true)
private class ServiceAgreementHandlerTest
{
    static testMethod void unitTest(){
        Vendor__c objVendor = new Vendor__c();
        objVendor.Name = 'Test';
        objVendor.Stage__c = 'Account Approved';
        objVendor.Email__c = 'test@test.com';
        objVendor.Mobile__c = '1234567899';
        insert objVendor;
        
        Service_Agreement__c objServiceAgreement = new Service_Agreement__c();
        objServiceAgreement.Vendor__c = objVendor.Id;
        insert objServiceAgreement;
        Test.startTest();
        try{
            objServiceAgreement.Active_MSA_Flag__c = true;
            update objServiceAgreement;
            
            new ServiceProviderHandler().onAfterInsert(null);
        } catch(Exception e){}
        Test.stopTest();
    }
}