unpackaged/main/default/objects/Account/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <description>Mapped from Lead</description>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Scope_of_Work</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job_Assigned_To__c/Job_Assigned_To__c.object-meta.xml
<CustomObject>
    <label>Job Assigned To</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs Assigned To</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job_Assigned_To__c/fields/Capability__c.field-meta.xml
<CustomField>
    <fullName>Capability__c</fullName>
    <label>Capability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Scope_of_Work</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job_Assigned_To__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Jobs Assigned To</relationshipLabel>
    <relationshipName>Jobs_Assigned</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor</relationshipLabel>
    <relationshipName>Vendor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Partner_Scope_of_Work.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Development</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Vehicle Charging Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Work</fullName>
    </customValue>
    <customValue>
        <fullName>Ground Mount</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Low Voltage (Thermostat)</fullName>
    </customValue>
    <customValue>
        <fullName>Main Panel Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>O&amp;M</fullName>
    </customValue>
    <customValue>
        <fullName>Permit and Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Permitting</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Abatement</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>PV Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Rafter / Structural Upgrades</fullName>
    </customValue>
    <customValue>
        <fullName>Roofing</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Tree Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Trenching</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Design</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Warranty &amp; Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Inspections</fullName>
        <isActive>false</isActive>
        <label>Inspections</label>
    </customValue>
    <masterLabel>Partner Scope of Work</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/JobAssignedToHandler.cls
public class JobAssignedToHandler {
    public void onBeforeInsert(List<Job_Assigned_To__c> listJObAssignedTo){
        preventIncorrectScopeOfWorkSelection(listJObAssignedTo);
    }
    public void onBeforeUpdate(List<Job_Assigned_To__c> listJObAssignedTo, Map<Id,Job_Assigned_To__c> mapOldJobAssignedTo){
        preventIncorrectScopeOfWorkSelection(listJObAssignedTo);
    }
    public void onAfterInsert(List<Job_Assigned_To__c> listJObAssignedTo){
        
            sendUpdateCallOut(listJObAssignedTo);
        
    }
    public void onAfterUpdate(List<Job_Assigned_To__c> listJobAssignedTo, Map<Id,Job_Assigned_To__c> mapOldJobAssignedTo){
        List<Job_Assigned_To__c> listUpdatedScopeOdWork = new List<Job_Assigned_To__c>();
        for(Job_Assigned_To__c objJobAssignedTo  : listJobAssignedTo){
            if(objJobAssignedTo.Capability__c != mapOldJobAssignedTo.get(objJobAssignedTo.Id).Capability__c){
                listJobAssignedTo.add(objJobAssignedTo);
            }
        }
        if(!listJobAssignedTo.isEmpty()){
            preventIncorrectScopeOfWorkSelection(listJObAssignedTo);
        }
    }
    
    private void preventIncorrectScopeOfWorkSelection(List<Job_Assigned_To__c> listJObAssignedTo){
        Set<Id> vendorId = new Set<Id>();
        for(Job_Assigned_To__c objJobAssignedTo : listJObAssignedTo){
            vendorId.add(objJobAssignedTo.Vendor__c);
        }
        Map<Id,Vendor__c> mapAccountsById = new Map<Id,Vendor__c>([SELECT Id, Account__r.Scope_of_Work__c FROM Vendor__c WHERE Id IN :vendorId]);
        for(Job_Assigned_To__c objJobAssignedTo : listJObAssignedTo){
            if(!mapAccountsById.containsKey(objJobAssignedTo.Vendor__c) ||
                !(mapAccountsById.get(objJobAssignedTo.Vendor__c).Account__r.Scope_of_Work__c != null) ||
                !mapAccountsById.get(objJobAssignedTo.Vendor__c).Account__r.Scope_of_Work__c.contains(objJobAssignedTo.Capability__c)){

                objJobAssignedTo.addError(System.Label.Wrong_scope_of_work);
            }
        }
    }

    private void sendUpdateCallOut(List<Job_Assigned_To__c> listJObAssignedTo){
        Set<Id> jobAssignedToIds = new Set<Id>();
        for(Job_Assigned_To__c objJobAssignedTo : listJObAssignedTo){
            jobAssignedToIds.add(objJobAssignedTo.Id);
        }
            if(!jobAssignedToIds.isEmpty()){
                PalmettoAPIService.sendJobAssignmentData(jobAssignedToIds);
            }
        
    }
}