unpackaged/main/default/objects/Account/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <description>Mapped from Lead</description>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Scope_of_Work</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/AHJ_Assumed__c.field-meta.xml
<CustomField>
    <fullName>AHJ_Assumed__c</fullName>
    <label>AHJ Assumed</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Partner_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Partner_Job_ID__c</fullName>
    <label>Partner Job ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Electrical Vehicle Charging Equipment</fullName>
            </value>
            <value>
                <fullName>Electrical Work</fullName>
            </value>
            <value>
                <fullName>Ground Mount</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Low Voltage(Thermostat)</fullName>
            </value>
            <value>
                <fullName>Main Panel Upgrade</fullName>
            </value>
            <value>
                <fullName>O&amp;M</fullName>
            </value>
            <value>
                <fullName>Permit and Installation</fullName>
            </value>
            <value>
                <fullName>Permitting</fullName>
            </value>
            <value>
                <fullName>Pest Abatement</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>PV Installation</fullName>
            </value>
            <value>
                <fullName>Rafter / Structural Upgrades</fullName>
            </value>
            <value>
                <fullName>Re-Roof</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Tree Removal</fullName>
            </value>
            <value>
                <fullName>Trenching</fullName>
            </value>
            <value>
                <fullName>Inspections</fullName>
                <isActive>false</isActive>
                <label>Inspections</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/AHJ_Assumed__c.field-meta.xml
<CustomField>
    <fullName>AHJ_Assumed__c</fullName>
    <label>AHJ Assumed</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of contact associated with opportunity</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Partner_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Partner_Job_ID__c</fullName>
    <label>Partner Job ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Electrical Vehicle Charging Equipment</fullName>
            </value>
            <value>
                <fullName>Electrical Work</fullName>
            </value>
            <value>
                <fullName>Ground Mount</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Low Voltage(Thermostat)</fullName>
            </value>
            <value>
                <fullName>Main Panel Upgrade</fullName>
            </value>
            <value>
                <fullName>O&amp;M</fullName>
            </value>
            <value>
                <fullName>Permit and Installation</fullName>
            </value>
            <value>
                <fullName>Permitting</fullName>
            </value>
            <value>
                <fullName>Pest Abatement</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>PV Installation</fullName>
            </value>
            <value>
                <fullName>Rafter / Structural Upgrades</fullName>
            </value>
            <value>
                <fullName>Re-Roof</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Tree Removal</fullName>
            </value>
            <value>
                <fullName>Trenching</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Partner_Scope_of_Work.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Development</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Vehicle Charging Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Work</fullName>
    </customValue>
    <customValue>
        <fullName>Ground Mount</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Low Voltage (Thermostat)</fullName>
    </customValue>
    <customValue>
        <fullName>Main Panel Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>O&amp;M</fullName>
    </customValue>
    <customValue>
        <fullName>Permit and Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Permitting</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Abatement</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>PV Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Rafter / Structural Upgrades</fullName>
    </customValue>
    <customValue>
        <fullName>Roofing</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Tree Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Trenching</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Design</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Warranty &amp; Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Inspections</fullName>
        <isActive>false</isActive>
        <label>Inspections</label>
    </customValue>
    <masterLabel>Partner Scope of Work</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/LeadHandler.cls
public class LeadHandler
{
    //This method is executed on before insert event of trigger.
    public void onBeforeInsert(List<Lead> lstLead){
        populateCompany(lstLead);
    }
    //This method is executed on after insert event of trigger.
    public void onAfterInsert(List<Lead> lstLead){
        convertLead(lstLead);
    }
    //This method is executed on after update event of trigger.
    public void onAfterUpdate(List<Lead> lstLead, Map<Id, Lead> mapIdToOldLead){
        updateOpportunity(lstLead, mapIdToOldLead);
    }
    
    //This method is used to populate the company name before conversion.
    private void populateCompany(List<Lead> lstLead){
        Id buildOnlyLeadId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Build Only').getRecordTypeId();
        for(Lead objLead : lstLead){
            if(objLead.RecordTypeId == buildOnlyLeadId && objLead.Company == 'X'){
                objLead.Company = (objLead.FirstName == null?'':objLead.FirstName) + ' ' + objLead.LastName + ' - Account';
            }
        }
    }
    
    
    //This method is used to convert lead.
    
    private void convertLead(List<Lead> lstLead){
        Id buildOnlyLeadId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Build Only').getRecordTypeId();
        List<Database.LeadConvert> lstLeadConvert = new List<Database.LeadConvert>();
        Map<Id, Lead> mapIdToLead = new Map<Id, Lead>();
        for(Lead objLead : lstLead){
            if(objLead.RecordTypeId == buildOnlyLeadId && String.isNotBlank(objLead.Scope_of_Work__c) && objLead.Scope_of_Work__c.containsIgnoreCase('Installation') && !objLead.Scope_of_Work__c.containsIgnoreCase('PV Installation')){
                Database.LeadConvert objLeadConvert = new Database.LeadConvert();
                objLeadConvert.setLeadId(objLead.Id);
                objLeadConvert.setConvertedStatus('Qualified');
                lstLeadConvert.add(objLeadConvert);
                mapIdToLead.put(objLead.Id, objLead);
            }
        }
        System.debug('>>>>lstLeadConvert>>>>'+lstLeadConvert);
        if(!lstLeadConvert.isEmpty()){
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.AllowSave = true;
            List<Database.LeadConvertResult> lstResult = Database.convertLead(lstLeadConvert, dml);
            
            for(Database.LeadConvertResult objresult : lstResult){
                if(!objresult.isSuccess()){
                    Id leadId = objresult.getLeadId();
                    String errorMsg = '';
                    for(Database.Error objError : objresult.getErrors()){
                        errorMsg += objError.getMessage() + ', ';
                    }
                    if(mapIdToLead.containsKey(leadId)){
                        mapIdToLead.get(leadId).addError(errorMsg);
                    }
                }
            }
        }
    }
	
    
    //This method is used to opp name after lead conversion.
    private void updateOpportunity(List<Lead> lstLead, Map<Id, Lead> mapIdToOldLead){
        Map<Id, Opportunity> mapIdToOpp = new Map<Id, Opportunity>();
        Map<Id, Account> mapIdToAcc = new Map<Id, Account>();
        
        Id buildOnlyAccountId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Only').getRecordTypeId();
        Id buildOnlyLeadId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Build Only').getRecordTypeId();
        Id buildOnlyOppId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Build Only').getRecordTypeId();

        
        for(Lead objLead : lstLead){
            Lead objOldLead = mapIdToOldLead.get(objLead.Id);
            if(objLead.RecordTypeId == buildOnlyLeadId  && objLead.IsConverted != objOldLead.IsConverted && objLead.IsConverted == true
                && String.isNotBlank(objLead.Scope_of_Work__c) && objLead.Scope_of_Work__c.containsIgnoreCase('Installation') && !objLead.Scope_of_Work__c.containsIgnoreCase('PV Installation')){
                Opportunity objOpp = new Opportunity();
                objOpp.Id = objLead.ConvertedOpportunityId;
                objOpp.RecordTypeId = buildOnlyOppId;
                objOpp.Name = (objLead.FirstName == null?'':objLead.FirstName) + ' ' + objLead.LastName + ' - Account - Opportunity';
                objOpp.Contact__c = objLead.ConvertedContactId;
                objOpp.AHJ_Assumed__c = objLead.AHJ_Assumed__c;
                objOpp.Partner_Job_ID__c = objLead.Partner_Job_ID__c;
               
                if(objlead.Scope_of_Work__c.containsIgnoreCase('Permit and Installation')){
                    objOpp.StageName = '13. Engineering Design Complete';
                } else{
                    objOpp.StageName = '18. Installation';
                }
                mapIdToOpp.put(objOpp.Id, objOpp);
                
                Account objAccount = new Account();
                objAccount.Id = objLead.ConvertedAccountId;
                objAccount.recordTypeId = buildOnlyAccountId;
                mapIdToAcc.put(objAccount.Id, objAccount);
            }
        }
        
        if(!mapIdToOpp.isEmpty())
            update mapIdToOpp.values();
        if(!mapIdToAcc.isEmpty())
            update mapIdToAcc.values();
    }
}