unpackaged/main/default/objects/Account/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <description>Mapped from Lead</description>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Scope_of_Work</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case_Assigned_To__c/Case_Assigned_To__c.object-meta.xml
<CustomObject>
    <description>Junction object between cases and build partners</description>
    <label>Case Assigned To</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases Assigned To</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case_Assigned_To__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Cases Assigned To</relationshipLabel>
    <relationshipName>Cases_Assigned_To</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor</relationshipLabel>
    <relationshipName>Vendor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Partner_Scope_of_Work.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Development</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Vehicle Charging Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Work</fullName>
    </customValue>
    <customValue>
        <fullName>Ground Mount</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Low Voltage (Thermostat)</fullName>
    </customValue>
    <customValue>
        <fullName>Main Panel Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>O&amp;M</fullName>
    </customValue>
    <customValue>
        <fullName>Permit and Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Permitting</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Abatement</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>PV Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Rafter / Structural Upgrades</fullName>
    </customValue>
    <customValue>
        <fullName>Roofing</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Tree Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Trenching</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Design</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Warranty &amp; Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Inspections</fullName>
        <isActive>false</isActive>
        <label>Inspections</label>
    </customValue>
    <masterLabel>Partner Scope of Work</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseAssignedToHandler.cls
public with sharing class CaseAssignedToHandler {
    public void onBeforeInsert(List<Case_Assigned_To__c> listCaseAssignedTo){
        preventIncorrectScopeOfWorkSelection(listCaseAssignedTo);
    }
    public void onBeforeUpdate(List<Case_Assigned_To__c> listCaseAssignedTo, Map<Id,Case_Assigned_To__c> mapOldCaseAssignedTo){
        preventIncorrectScopeOfWorkSelection(listCaseAssignedTo);
    }
    public void onAfterInsert(List<Case_Assigned_To__c> listCaseAssignedTo){
        sendUpdateCallOut(listCaseAssignedTo);
    }
    public void onAfterUpdate(List<Case_Assigned_To__c> listCaseAssignedTo, Map<Id,Case_Assigned_To__c> mapOldCaseAssignedTo){
        List<Case_Assigned_To__c> listUpdatedScopeOdWork = new List<Case_Assigned_To__c>();
        for(Case_Assigned_To__c objCaseAssignedTo  : listCaseAssignedTo){
            if(objCaseAssignedTo.Capability__c != mapOldCaseAssignedTo.get(objCaseAssignedTo.Id).Capability__c){
                listCaseAssignedTo.add(objCaseAssignedTo);
            }
        }
        if(!listCaseAssignedTo.isEmpty()){
            preventIncorrectScopeOfWorkSelection(listCaseAssignedTo);
        }
    }
    
    private void preventIncorrectScopeOfWorkSelection(List<Case_Assigned_To__c> listCaseAssignedTo){
        Set<Id> vendorIds = new Set<Id>();
        for(Case_Assigned_To__c objCaseAssignedTo : listCaseAssignedTo){
            if(objCaseAssignedTo.Capability__c != null && objCaseAssignedTo.Capability__c != ''){
                vendorIds.add(objCaseAssignedTo.Vendor__c);
            }
        }
        Map<Id,Vendor__c> mapAccountsById = new Map<Id,Vendor__c>([SELECT Id, Account__r.Scope_of_work__c FROM Vendor__c WHERE Id IN :vendorIds]);
        for(Case_Assigned_To__c objCaseAssignedTo : listCaseAssignedTo){
            if(mapAccountsById.containsKey(objCaseAssignedTo.Vendor__c) &&
                (!(mapAccountsById.get(objCaseAssignedTo.Vendor__c).Account__r.Scope_of_work__c != null) ||
                !mapAccountsById.get(objCaseAssignedTo.Vendor__c).Account__r.Scope_of_work__c.contains(objCaseAssignedTo.Capability__C))){

                objCaseAssignedTo.addError(System.Label.Wrong_scope_of_work);
            }
        }
    }

    private void sendUpdateCallOut(List<Case_Assigned_To__c> caseJObAssignedTo){
        Set<Id> caseAssignedToIds = new Set<Id>();
        for(Case_Assigned_To__c objCaseAssignedTo : caseJObAssignedTo){
            caseAssignedToIds.add(objCaseAssignedTo.Id);
        }
        if(!caseAssignedToIds.isEmpty() && !System.isBatch()){
            PalmettoAPIService.sendCaseAssignmentData(caseAssignedToIds);
        }
    }
}