unpackaged/main/default/objects/Account/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <description>Mapped from Lead</description>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Scope_of_Work</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Case_Assigned_to__c.field-meta.xml
<CustomField>
    <fullName>Case_Assigned_to__c</fullName>
    <label>Case Assigned to</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alejandra Torricos</fullName>
            </value>
            <value>
                <fullName>Amy Denheyer</fullName>
            </value>
            <value>
                <fullName>Ana Havliand</fullName>
            </value>
            <value>
                <fullName>Dawn Heck</fullName>
            </value>
            <value>
                <fullName>Machias Schoen</fullName>
            </value>
            <value>
                <fullName>Mary Cole</fullName>
            </value>
            <value>
                <fullName>Meghan Eggers</fullName>
            </value>
            <value>
                <fullName>Sandy Feliz Dominguez</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <formula>Text(Opportunity__r.Financing_Tool__c)</formula>
    <label>Financing Tool</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>TEXT (Opportunity__r.Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Design_Change.recordType-meta.xml
<RecordType>
    <fullName>Design_Change</fullName>
    <active>true</active>
    <businessProcess>Standard Support Process</businessProcess>
    <label>Design Change</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Pennsylvania.recordType-meta.xml
<RecordType>
    <fullName>Pennsylvania</fullName>
    <active>false</active>
    <businessProcess>Standard Support Process</businessProcess>
    <label>Pennsylvania</label>
</RecordType>

unpackaged/main/default/objects/Case_Assigned_To__c/Case_Assigned_To__c.object-meta.xml
<CustomObject>
    <description>Junction object between cases and build partners</description>
    <label>Case Assigned To</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases Assigned To</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case_Assigned_To__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Cases Assigned To</relationshipLabel>
    <relationshipName>Cases_Assigned_To</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Case_Assigned_To__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Cases Assigned To</relationshipLabel>
    <relationshipName>Cases_Assigned_To</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
            <value>
                <fullName>Pennsylvania</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Electrical Vehicle Charging Equipment</fullName>
            </value>
            <value>
                <fullName>Electrical Work</fullName>
            </value>
            <value>
                <fullName>Ground Mount</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Low Voltage(Thermostat)</fullName>
            </value>
            <value>
                <fullName>Main Panel Upgrade</fullName>
            </value>
            <value>
                <fullName>O&amp;M</fullName>
            </value>
            <value>
                <fullName>Permit and Installation</fullName>
            </value>
            <value>
                <fullName>Permitting</fullName>
            </value>
            <value>
                <fullName>Pest Abatement</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>PV Installation</fullName>
            </value>
            <value>
                <fullName>Rafter / Structural Upgrades</fullName>
            </value>
            <value>
                <fullName>Re-Roof</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Tree Removal</fullName>
            </value>
            <value>
                <fullName>Trenching</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Build Partner</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TriggerConfiguration__c/TriggerConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Configuration</label>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor</relationshipLabel>
    <relationshipName>Vendor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Partner_Scope_of_Work.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Development</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Vehicle Charging Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Work</fullName>
    </customValue>
    <customValue>
        <fullName>Ground Mount</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Low Voltage (Thermostat)</fullName>
    </customValue>
    <customValue>
        <fullName>Main Panel Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>O&amp;M</fullName>
    </customValue>
    <customValue>
        <fullName>Permit and Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Permitting</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Abatement</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>PV Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Rafter / Structural Upgrades</fullName>
    </customValue>
    <customValue>
        <fullName>Roofing</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Tree Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Trenching</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Design</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Warranty &amp; Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Inspections</fullName>
        <isActive>false</isActive>
        <label>Inspections</label>
    </customValue>
    <masterLabel>Partner Scope of Work</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseAssignedToHandlerTest.cls
@isTest
public class CaseAssignedToHandlerTest {
    @isTest
    private static void testPreventCreationWrongScopeOfWork() {
        // Test data setup
        TriggerConfiguration__c caseApiCall = new TriggerConfiguration__c();
        caseApiCall.Name = 'Case Assignment API Trigger';
        caseApiCall.Active__c = true;
        insert caseApiCall;

        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;

        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        bpAccount.Scope_of_Work__c = 'Design;Inspection';
        insert bpAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;
        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Pennsylvania';
        insert objOpportunity;

        Id desingChangeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Design_Change').getRecordTypeId();
        Case objCase = new Case();
        objCase.Opportunity__c = objOpportunity.Id;
        objCase.RecordTypeId = desingChangeId;
        insert objCase;

        // Actual test
        Test.startTest();
        try{
            Case_Assigned_To__c objCaseAssignment = new Case_Assigned_To__c(
            Vendor__c = buildPartner.Id,
            Case__c = objCase.Id,
            Capability__c = 'Permitting'
            );
            insert objCaseAssignment;
            System.assert(false, 'An exception should have been thrown by the trigger but was not.');
        }catch(Exception e){
            Test.stopTest();
            // Asserts
            System.assert(e.getMessage().contains(System.Label.Wrong_scope_of_work), 'The exception thrown was not the expected one');
        }
    } 

    @isTest
    private static void testPreventUpdateWrongScopeOfWork() {
        // Test data setup
        TriggerConfiguration__c caseApiCall = new TriggerConfiguration__c();
        caseApiCall.Name = 'Case Assignment API Trigger';
        caseApiCall.Active__c = true;
        insert caseApiCall;
        
        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;

        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        bpAccount.Scope_of_Work__c = 'Design;Inspection';
        insert bpAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;
        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Pennsylvania';
        insert objOpportunity;

        Id desingChangeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Design_Change').getRecordTypeId();
        Case objCase = new Case();
        objCase.Opportunity__c = objOpportunity.Id;
        objCase.RecordTypeId = desingChangeId;
        insert objCase;
 
        Case_Assigned_To__c objCaseAssignment = new Case_Assigned_To__c(
            Vendor__c = buildPartner.Id,
            Case__c = objCase.Id,
            Capability__c = 'Design'
            );
        insert objCaseAssignment;

        // Actual test
        Test.startTest();
        try{
            objCaseAssignment.Capability__c = 'Permitting';
            update objCaseAssignment;
            System.assert(false, 'An exception should have been thrown by the trigger but was not.');
        }catch(Exception e){
            Test.stopTest();
            // Asserts
            System.assert(e.getMessage().contains(System.Label.Wrong_scope_of_work), 'The exception thrown was not the expected one');
        }
    }
}