unpackaged/main/default/objects/Account/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <description>Mapped from Lead</description>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Scope_of_Work</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Automation__c.field-meta.xml
<CustomField>
    <fullName>Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <formula>Opportunity__r.Installation_Complete_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>TEXT(Opportunity__r.Location__c)</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Site Approval</fullName>
            </value>
            <value>
                <fullName>Virtual Survey</fullName>
            </value>
            <value>
                <fullName>Physical Survey</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MA SMART)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (IL ABP)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (RI ReGrowth)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (CT Green Bank)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (PennAEPS)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NJ TREC)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MD)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NV)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (Austin TX)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (San Antonio TX)</fullName>
            </value>
            <value>
                <fullName>Contract Processing- Document Verification</fullName>
            </value>
            <value>
                <fullName>Document Verification</fullName>
            </value>
            <value>
                <fullName>Job Close Out</fullName>
            </value>
            <value>
                <fullName>HOA</fullName>
            </value>
            <value>
                <fullName>Permit Issuance</fullName>
            </value>
            <value>
                <fullName>Interconnection</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>Loan except Sunnova</fullName>
            </value>
            <value>
                <fullName>Sunnova</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
            <value>
                <fullName>Installation Scheduling</fullName>
            </value>
            <value>
                <fullName>System Activation</fullName>
            </value>
            <value>
                <fullName>PV Materials Verification</fullName>
            </value>
            <value>
                <fullName>Additional Adder Coordination</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade</fullName>
            </value>
            <value>
                <fullName>Ground Mount Coordination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Design.recordType-meta.xml
<RecordType>
    <fullName>Design</fullName>
    <active>true</active>
    <label>Site Approval</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Job_Close_Out.recordType-meta.xml
<RecordType>
    <fullName>Job_Close_Out</fullName>
    <active>true</active>
    <label>Job Close Out</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Permitting.recordType-meta.xml
<RecordType>
    <fullName>Permitting</fullName>
    <active>true</active>
    <label>Permitting</label>
</RecordType>

unpackaged/main/default/objects/Job_Assigned_To__c/Job_Assigned_To__c.object-meta.xml
<CustomObject>
    <label>Job Assigned To</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs Assigned To</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job_Assigned_To__c/fields/Capability__c.field-meta.xml
<CustomField>
    <fullName>Capability__c</fullName>
    <label>Capability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Scope_of_Work</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job_Assigned_To__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Jobs Assigned To</relationshipLabel>
    <relationshipName>Assigned_To</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job_Assigned_To__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Jobs Assigned To</relationshipLabel>
    <relationshipName>Jobs_Assigned</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
            <value>
                <fullName>Pennsylvania</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Work__c</fullName>
    <label>Scope of Work</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Electrical Vehicle Charging Equipment</fullName>
            </value>
            <value>
                <fullName>Electrical Work</fullName>
            </value>
            <value>
                <fullName>Ground Mount</fullName>
            </value>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Low Voltage(Thermostat)</fullName>
            </value>
            <value>
                <fullName>Main Panel Upgrade</fullName>
            </value>
            <value>
                <fullName>O&amp;M</fullName>
            </value>
            <value>
                <fullName>Permit and Installation</fullName>
            </value>
            <value>
                <fullName>Permitting</fullName>
            </value>
            <value>
                <fullName>Pest Abatement</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>PV Installation</fullName>
            </value>
            <value>
                <fullName>Rafter / Structural Upgrades</fullName>
            </value>
            <value>
                <fullName>Re-Roof</fullName>
            </value>
            <value>
                <fullName>Roofing</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Tree Removal</fullName>
            </value>
            <value>
                <fullName>Trenching</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Build Partner</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TriggerConfiguration__c/TriggerConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Configuration</label>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor</relationshipLabel>
    <relationshipName>Vendor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Partner_Scope_of_Work.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Business Development</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Vehicle Charging Equipment</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Work</fullName>
    </customValue>
    <customValue>
        <fullName>Ground Mount</fullName>
    </customValue>
    <customValue>
        <fullName>Inspection</fullName>
    </customValue>
    <customValue>
        <fullName>Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Low Voltage (Thermostat)</fullName>
    </customValue>
    <customValue>
        <fullName>Main Panel Upgrade</fullName>
    </customValue>
    <customValue>
        <fullName>O&amp;M</fullName>
    </customValue>
    <customValue>
        <fullName>Permit and Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Permitting</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Abatement</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>PV Installation</fullName>
    </customValue>
    <customValue>
        <fullName>Rafter / Structural Upgrades</fullName>
    </customValue>
    <customValue>
        <fullName>Roofing</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Tree Removal</fullName>
    </customValue>
    <customValue>
        <fullName>Trenching</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Design</fullName>
    </customValue>
    <customValue>
        <fullName>Site Survey</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Warranty &amp; Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>Inspections</fullName>
        <isActive>false</isActive>
        <label>Inspections</label>
    </customValue>
    <masterLabel>Partner Scope of Work</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/JobAssignedToHandlerTest.cls
@isTest
public class JobAssignedToHandlerTest {
    @isTest
    private static void testPreventCreationWrongScopeOfWork() {
        // Test data setup
        TriggerConfiguration__c jobApiCall = new TriggerConfiguration__c();
        jobApiCall.Name = 'Job Assignment API Trigger';
        jobApiCall.Active__c = true;
        insert jobApiCall;
        
        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;

        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        bpAccount.Scope_of_work__c = 'Installation;Inspection';
        insert bpAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;
        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Pennsylvania';
        insert objOpportunity;
        
        Id contractProcessingId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Job_Close_Out').getRecordTypeId();
        Job__c objJob = new Job__c();
        objJob.Opportunity__c = objOpportunity.Id;
        objJob.RecordTypeId = contractProcessingId;
        objJob.Type__c = 'Job Close Out';
        objJob.Automation__c = true;
        insert objJob;

        // Actual test
        Test.startTest();
        try{
            Job_Assigned_To__c objJobAssignment = new Job_Assigned_To__c(
            Vendor__c = buildPartner.Id,
            Job__c = objJob.Id,
            Capability__c = 'Permitting'
            );
            insert objJobAssignment;
            System.assert(false, 'An exception should have been thrown by the trigger but was not.');
        }catch(Exception e){
            Test.stopTest();
            // Asserts
            System.assert(e.getMessage().contains(System.Label.Wrong_scope_of_work), 'The exception thrown was not the expected one');
        }
    
    } 

    @isTest
    private static void testPreventUpdateWrongScopeOfWork() {
        // Test data setup
        TriggerConfiguration__c jobApiCall = new TriggerConfiguration__c();
        jobApiCall.Name = 'Job Assignment API Trigger';
        jobApiCall.Active__c = true;
        insert jobApiCall;

        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;
 
        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        bpAccount.Scope_of_work__c = 'Installation;Inspection';
        insert bpAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;

        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Pennsylvania';
        insert objOpportunity;
         
        Id contractProcessingId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Job_Close_Out').getRecordTypeId();
        Job__c objJob = new Job__c();
        objJob.Opportunity__c = objOpportunity.Id;
        objJob.RecordTypeId = contractProcessingId;
        objJob.Type__c = 'Job Close Out';
        objJob.Automation__c = true;
        insert objJob;
 
        Job_Assigned_To__c objJobAssignment = new Job_Assigned_To__c(
        Vendor__c = buildPartner.Id,
        Job__c = objJob.Id,
        Capability__c = 'Inspection'
        );
        insert objJobAssignment;
        // Actual test
        Test.startTest();
        try{
            objJobAssignment.Capability__c = 'Permitting';
            update objJobAssignment;
            System.assert(false, 'An exception should have been thrown by the trigger but was not.');
        }catch(Exception e){
            Test.stopTest();
            // Asserts
            System.assert(e.getMessage().contains(System.Label.Wrong_scope_of_work), 'The exception thrown was not the expected one');
        }
    }
}