unpackaged/main/default/objects/Account/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner</label>
</RecordType>

unpackaged/main/default/objects/AccountTeamMember/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Created to identify the Build Partner Market Manager and Regional Director</description>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
            <value>
                <fullName>Pennsylvania</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Build Partner</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor</relationshipLabel>
    <relationshipName>Vendor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <customValue>
        <fullName>New Jersey</fullName>
    </customValue>
    <customValue>
        <fullName>Pennsylvania</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountTeamMemberHandlerTest.cls
@isTest
public with sharing class AccountTeamMemberHandlerTest {
    @isTest
    private static void testOppTMisCreatedOnAccTMInsert() {
        Test.setMock(HttpCalloutMock.class, new HomeMockHttpResponseGenerator());
        // Test data setup
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='opptriggertestuser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='opptriggertestuser@testorg.com');
        insert u;
        
        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        insert bpAccount;

        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;

        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Pennsylvania';
        objOpportunity.Vendor__c = buildPartner.Id;
        insert objOpportunity;
        
        AccountTeamMember objATM = new AccountTeamMember(UserId = u.Id, AccountId = bpAccount.Id, TeamMemberRole = 'Market Manager', State__c = 'Alabama;Connecticut;Pennsylvania');
        Test.startTest();
        insert objATM;
        Test.stopTest();

        OpportunityTeamMember objOTM;
        objOTM = [SELECT Id, TeamMemberRole, OpportunityId FROM OpportunityTeamMember WHERE OpportunityId = :objOpportunity.Id];

        System.assertNotEquals(null, objOTM, 'Opp team member was not created');
        System.assertEquals('Market Manager', objOTM.TeamMemberRole, 'Opp team member was not created');
        System.assertEquals(objOpportunity.Id, objOTM.OpportunityId, 'Opp team member was not created');
    }

    @isTest
    private static void testOppTMisDeletedOnAccTMDeletion() {
        Test.setMock(HttpCalloutMock.class, new HomeMockHttpResponseGenerator());
        // Test data setup
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='opptriggertestuser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='opptriggertestuser@testorg.com');
        insert u;
        
        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        insert bpAccount;

        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;

        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Pennsylvania';
        objOpportunity.Vendor__c = buildPartner.Id;
        insert objOpportunity;
        
        AccountTeamMember objATM = new AccountTeamMember(UserId = u.Id, AccountId = bpAccount.Id, TeamMemberRole = 'Market Manager', State__c = 'Alabama;Connecticut;Pennsylvania');
        insert objATM;
        List<OpportunityTeamMember> objOTM = new List<OpportunityTeamMember>();
        objOTM = [SELECT Id FROM OpportunityTeamMember WHERE OpportunityId = :objOpportunity.Id];
        Test.startTest();
        delete objATM;
        Test.stopTest();

        List<OpportunityTeamMember> upObjOTM = new List<OpportunityTeamMember>();
        upObjOTM = [SELECT Id FROM OpportunityTeamMember WHERE OpportunityId = :objOpportunity.Id];

        System.assertEquals(1, objOTM.size(), 'Opp team member needed for test was not created');
        System.assertEquals(true, upObjOTM.isEmpty(), 'Opp team member was not deleted properly');
    }

    @isTest
    private static void testAccTeamMemberAddState() {
        Test.setMock(HttpCalloutMock.class, new HomeMockHttpResponseGenerator());
        // Test data setup
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='opptriggertestuser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='opptriggertestuser@testorg.com');
        insert u;
        
        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        insert bpAccount;

        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;

        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Alabama';
        objOpportunity.Vendor__c = buildPartner.Id;
        insert objOpportunity;
        
        AccountTeamMember objATM = new AccountTeamMember(UserId = u.Id, AccountId = bpAccount.Id, TeamMemberRole = 'Market Manager', State__c = 'Connecticut;Pennsylvania');
        insert objATM; 

        // Actual test
        Test.startTest();
        objATM.State__c = 'Alabama;Connecticut;Pennsylvania';
        update objATM;
        Test.stopTest();
    
        // Asserts
        List<OpportunityTeamMember> objOTM = new List<OpportunityTeamMember>();
        objOTM = [SELECT Id, TeamMemberRole, OpportunityId FROM OpportunityTeamMember WHERE OpportunityId = :objOpportunity.Id];

        System.assertEquals(1, objOTM.size(),'Opp team member was not created');
        System.assertEquals('Market Manager', objOTM[0].TeamMemberRole,'Opp team member was not created');
        System.assertEquals(objOpportunity.Id, objOTM[0].OpportunityId,'Opp team member was not created');
    }

    @isTest
    private static void testAccTeamMemberRemoveState() {
        Test.setMock(HttpCalloutMock.class, new HomeMockHttpResponseGenerator());
        // Test data setup
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='opptriggertestuser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='opptriggertestuser@testorg.com');
        insert u;
        
        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        insert bpAccount;

        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;

        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Alabama';
        objOpportunity.Vendor__c = buildPartner.Id;
        insert objOpportunity;
        
        AccountTeamMember objATM = new AccountTeamMember(UserId = u.Id, AccountId = bpAccount.Id, TeamMemberRole = 'Market Manager', State__c = 'Alabama;Connecticut;Pennsylvania');
        insert objATM;

        List<OpportunityTeamMember> objOTM = new List<OpportunityTeamMember>();
        objOTM = [SELECT Id FROM OpportunityTeamMember WHERE OpportunityId = :objOpportunity.Id];

        // Actual test
        Test.startTest();
        objATM.State__c = 'Connecticut;Pennsylvania';
        update objATM;
        Test.stopTest();
    
        // Asserts
        List<OpportunityTeamMember> upObjOTM = new List<OpportunityTeamMember>();
        upObjOTM = [SELECT Id FROM OpportunityTeamMember WHERE OpportunityId = :objOpportunity.Id];

        System.assertEquals(1, objOTM.size(), 'Opp team member needed for test was not created');
        System.assertEquals(true, upObjOTM.isEmpty(), 'Opp team member was not deleted properly');
    }

    @isTest
    private static void testAccTeamMemberChangeRoleToMarketManager() {
        Test.setMock(HttpCalloutMock.class, new HomeMockHttpResponseGenerator());
        // Test data setup
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='opptriggertestuser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='opptriggertestuser@testorg.com');
        insert u;
        
        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        insert bpAccount;

        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;

        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Alabama';
        objOpportunity.Vendor__c = buildPartner.Id;
        insert objOpportunity;
        
        AccountTeamMember objATM = new AccountTeamMember(UserId = u.Id, AccountId = bpAccount.Id, TeamMemberRole = 'Project Manager', State__c = 'Alabama;Connecticut;Pennsylvania');
        insert objATM; 

        // Actual test
        Test.startTest();
        objATM.TeamMemberRole = 'Market Manager';
        update objATM;
        Test.stopTest();
    
        // Asserts
        List<OpportunityTeamMember> objOTM = new List<OpportunityTeamMember>();
        objOTM = [SELECT Id, TeamMemberRole, OpportunityId FROM OpportunityTeamMember WHERE OpportunityId = :objOpportunity.Id];

        System.assertEquals(1, objOTM.size(),'Opp team member was not created');
        System.assertEquals('Market Manager', objOTM[0].TeamMemberRole,'Opp team member was not created');
        System.assertEquals(objOpportunity.Id, objOTM[0].OpportunityId,'Opp team member was not created');
    }

    @isTest
    private static void testAccTeamMemberChangeRoleFromMarketManager() {
        Test.setMock(HttpCalloutMock.class, new HomeMockHttpResponseGenerator());
        // Test data setup
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='opptriggertestuser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='opptriggertestuser@testorg.com');
        insert u;
        
        Id buildPartnerId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Partner').getRecordTypeId();
        Account bpAccount = TestDataFactory.createAccount('Test Acc', buildPartnerId);
        insert bpAccount;

        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;

        Vendor__c buildPartner = new Vendor__c(Name = 'Test BP', Account__c = bpAccount.Id);
        insert buildPartner;

        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'SunRun';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'Pennsylvania';
        objOpportunity.Vendor__c = buildPartner.Id;
        insert objOpportunity;
        
        AccountTeamMember objATM = new AccountTeamMember(UserId = u.Id, AccountId = bpAccount.Id, TeamMemberRole = 'Market Manager', State__c = 'Alabama;Connecticut;Pennsylvania');
        insert objATM;

        List<OpportunityTeamMember> objOTM = new List<OpportunityTeamMember>();
        objOTM = [SELECT Id FROM OpportunityTeamMember WHERE OpportunityId = :objOpportunity.Id];

        // Actual test
        Test.startTest();
        objATM.TeamMemberRole = 'Project Manager';
        update objATM;
        Test.stopTest();
    
        // Asserts
        List<OpportunityTeamMember> upObjOTM = new List<OpportunityTeamMember>();
        upObjOTM = [SELECT Id FROM OpportunityTeamMember WHERE OpportunityId = :objOpportunity.Id];

        System.assertEquals(1, objOTM.size(), 'Opp team member needed for test was not created');
        System.assertEquals(true, upObjOTM.isEmpty(), 'Opp team member was not deleted properly');
    }
}