unpackaged/main/default/objects/Lead/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <label>Appointment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Sub_Market__c.field-meta.xml
<CustomField>
    <fullName>Sub_Market__c</fullName>
    <label>Sub-Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ann Arbor</fullName>
            </value>
            <value>
                <fullName>Atlanta</fullName>
            </value>
            <value>
                <fullName>Boston Metro</fullName>
            </value>
            <value>
                <fullName>Bronx</fullName>
            </value>
            <value>
                <fullName>Brooklyn</fullName>
            </value>
            <value>
                <fullName>Cape</fullName>
            </value>
            <value>
                <fullName>Charleston</fullName>
            </value>
            <value>
                <fullName>Charlotte</fullName>
            </value>
            <value>
                <fullName>Columbia</fullName>
            </value>
            <value>
                <fullName>Detroit</fullName>
            </value>
            <value>
                <fullName>Greenville</fullName>
            </value>
            <value>
                <fullName>Hilton Head</fullName>
            </value>
            <value>
                <fullName>Jacksonville</fullName>
            </value>
            <value>
                <fullName>Knoxville</fullName>
            </value>
            <value>
                <fullName>Long Island</fullName>
            </value>
            <value>
                <fullName>MA - Metrowest</fullName>
            </value>
            <value>
                <fullName>Manhattan</fullName>
            </value>
            <value>
                <fullName>MA - North Shore</fullName>
            </value>
            <value>
                <fullName>MA - South Shore</fullName>
            </value>
            <value>
                <fullName>MA - Western</fullName>
            </value>
            <value>
                <fullName>Memphis</fullName>
            </value>
            <value>
                <fullName>Miami</fullName>
            </value>
            <value>
                <fullName>Myrtle Beach</fullName>
            </value>
            <value>
                <fullName>Nashville</fullName>
            </value>
            <value>
                <fullName>New Orleans</fullName>
            </value>
            <value>
                <fullName>NJ - Central</fullName>
            </value>
            <value>
                <fullName>NJ - North</fullName>
            </value>
            <value>
                <fullName>NJ - South</fullName>
            </value>
            <value>
                <fullName>North Augusta</fullName>
            </value>
            <value>
                <fullName>Orlando</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Utility_Provider__c.field-meta.xml
<CustomField>
    <fullName>Utility_Provider__c</fullName>
    <label>Utility Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A &amp; N Electric Coop</fullName>
            </value>
            <value>
                <fullName>Abbeville City of</fullName>
            </value>
            <value>
                <fullName>Aiken Electric Coop Inc</fullName>
            </value>
            <value>
                <fullName>Alger-Delta Coop Electric Assn</fullName>
            </value>
            <value>
                <fullName>Alpena Power Co</fullName>
            </value>
            <value>
                <fullName>Bamberg Board of Public Works</fullName>
            </value>
            <value>
                <fullName>Bath Electric Gas &amp; Water Sys</fullName>
            </value>
            <value>
                <fullName>Belmont Light</fullName>
            </value>
            <value>
                <fullName>Berkeley Electric Co-op</fullName>
            </value>
            <value>
                <fullName>Berkeley Electric Coop Inc</fullName>
            </value>
            <value>
                <fullName>Black River Electric Co-op</fullName>
            </value>
            <value>
                <fullName>Blue Ridge Electric Coop Inc</fullName>
            </value>
            <value>
                <fullName>Braintree Electric Light Department</fullName>
            </value>
            <value>
                <fullName>Broad River Electric Coop, Inc</fullName>
            </value>
            <value>
                <fullName>Central Electric Power Co-op</fullName>
            </value>
            <value>
                <fullName>Chicopee City of</fullName>
            </value>
            <value>
                <fullName>City of Camden</fullName>
            </value>
            <value>
                <fullName>City of Georgetown</fullName>
            </value>
            <value>
                <fullName>City of Gladstone</fullName>
            </value>
            <value>
                <fullName>City of Marquette</fullName>
            </value>
            <value>
                <fullName>City of Newberry</fullName>
            </value>
            <value>
                <fullName>City of Rock Hill</fullName>
            </value>
            <value>
                <fullName>City of Russell</fullName>
            </value>
            <value>
                <fullName>City of Union</fullName>
            </value>
            <value>
                <fullName>City of Westminster</fullName>
            </value>
            <value>
                <fullName>Cleco Power LLC</fullName>
            </value>
            <value>
                <fullName>Clinton Combined Utility Sys</fullName>
            </value>
            <value>
                <fullName>Clinton Village of</fullName>
            </value>
            <value>
                <fullName>Coastal Electric Coop, Inc</fullName>
            </value>
            <value>
                <fullName>Concord Municipal Light Plant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Lead_Test.cls
@isTest
private Class Lead_Test 
{
    static testMethod void Test_LeadConvert(){
        Lead testLead = new Lead(
            FirstName='Demo10',
            LastName = 'Demo10 UnitTest',
            Email = 'test@gmail.com',
            Status='Open',
            company='x',
            street='1211 E I-40 Service Rd',
            city='Columbus',
            State='Ohio',
            Country = 'United States',
            LeadSource = '3rd Party Provider',
            Sub_Market__c = 'Atlanta',
            Utility_Provider__c = 'A & N Electric Coop',
            Appointment_Date__c = date.ValueOf('2019-03-09')
        );
        insert  testLead;
        testlead.Status = 'Convert';
        update testLead;
    }
}