unpackaged/main/default/objects/Case/fields/CaseType__c.field-meta.xml
<CustomField>
    <fullName>CaseType__c</fullName>
    <label>Type(C)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Additional Adder Coordination</fullName>
            </value>
            <value>
                <fullName>Alchemy</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Customer Complaint</fullName>
            </value>
            <value>
                <fullName>Customer Experience</fullName>
            </value>
            <value>
                <fullName>Customer Failing to Action</fullName>
            </value>
            <value>
                <fullName>Customer Requested</fullName>
            </value>
            <value>
                <fullName>Customer Requested Cancellation</fullName>
            </value>
            <value>
                <fullName>Customer Requested Change</fullName>
            </value>
            <value>
                <fullName>Customer Unresponsive</fullName>
            </value>
            <value>
                <fullName>Customer On Hold</fullName>
            </value>
            <value>
                <fullName>Delay in Stage</fullName>
            </value>
            <value>
                <fullName>Design Review</fullName>
            </value>
            <value>
                <fullName>Disqualification</fullName>
            </value>
            <value>
                <fullName>Document Collection</fullName>
            </value>
            <value>
                <fullName>Document Collection - CRC</fullName>
            </value>
            <value>
                <fullName>Electrical Review</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Expected offset / Savings</fullName>
            </value>
            <value>
                <fullName>Financier Compliance</fullName>
            </value>
            <value>
                <fullName>Financing</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Ground Mount Coordination</fullName>
            </value>
            <value>
                <fullName>Incentives</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>Sales Op</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Check_Request_Date__c.field-meta.xml
<CustomField>
    <fullName>Check_Request_Date__c</fullName>
    <label>Check Request Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Company_Cost__c.field-meta.xml
<CustomField>
    <fullName>Company_Cost__c</fullName>
    <label>Company Cost</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <formula>Text(Opportunity__r.Financing_Tool__c)</formula>
    <label>Financing Tool</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Phone_Textey__c.field-meta.xml
<CustomField>
    <fullName>Phone_Textey__c</fullName>
    <formula>Opportunity__r.Phone_Textey__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone Textey</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_1__c.field-meta.xml
<CustomField>
    <fullName>Reason_1__c</fullName>
    <label>Reason 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Management Support</fullName>
            </value>
            <value>
                <fullName>AHJ Assigned Pending Customer E-Sign</fullName>
            </value>
            <value>
                <fullName>AHJ Assigned Pending Customer Wet Sign</fullName>
            </value>
            <value>
                <fullName>AHJ Assigned Pending Palmetto</fullName>
            </value>
            <value>
                <fullName>AHJ Pending Research</fullName>
            </value>
            <value>
                <fullName>Austin Rebate</fullName>
            </value>
            <value>
                <fullName>Bill of Materials</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Contract Received - Documents Pending Review</fullName>
            </value>
            <value>
                <fullName>Crew</fullName>
            </value>
            <value>
                <fullName>CT Green Bank</fullName>
            </value>
            <value>
                <fullName>Customer Complaint</fullName>
            </value>
            <value>
                <fullName>Customer Sales Claim</fullName>
            </value>
            <value>
                <fullName>Data Communication Error</fullName>
            </value>
            <value>
                <fullName>Design Plan Set</fullName>
            </value>
            <value>
                <fullName>Document Changes Needed</fullName>
            </value>
            <value>
                <fullName>Electrical One Line</fullName>
            </value>
            <value>
                <fullName>Electrical Review</fullName>
            </value>
            <value>
                <fullName>Electrical Stamp</fullName>
            </value>
            <value>
                <fullName>Equipment Failure</fullName>
            </value>
            <value>
                <fullName>expected offset</fullName>
            </value>
            <value>
                <fullName>Failed Rescheduled Inspection</fullName>
            </value>
            <value>
                <fullName>Financing</fullName>
            </value>
            <value>
                <fullName>Full Survey</fullName>
            </value>
            <value>
                <fullName>Home damage</fullName>
            </value>
            <value>
                <fullName>IL ABP</fullName>
            </value>
            <value>
                <fullName>Incentives</fullName>
            </value>
            <value>
                <fullName>Initial Design QC</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>PTO Delay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>CX</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Incentives</fullName>
            </value>
            <value>
                <fullName>Delays/Extended Timelines</fullName>
            </value>
            <value>
                <fullName>Equipment/Workmanship</fullName>
            </value>
            <value>
                <fullName>Negative Review</fullName>
            </value>
            <value>
                <fullName>Solar Performance Expectations</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
                <isActive>false</isActive>
                <label>Fee</label>
            </value>
            <value>
                <fullName>Gift</fullName>
                <isActive>false</isActive>
                <label>Gift</label>
            </value>
            <value>
                <fullName>Reimbursement</fullName>
                <isActive>false</isActive>
                <label>Reimbursement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Reimbursement.recordType-meta.xml
<RecordType>
    <fullName>Reimbursement</fullName>
    <active>true</active>
    <businessProcess>Reimbursement Support Process</businessProcess>
    <label>Reimbursement</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrator Contact</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Office Manager</fullName>
            </value>
            <value>
                <fullName>Ops Manager</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Partner - Ambassador</fullName>
            </value>
            <value>
                <fullName>Partner - Community Lead</fullName>
            </value>
            <value>
                <fullName>Survey Recipient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Additional_Alchemy_Products__c.field-meta.xml
<CustomField>
    <fullName>Additional_Alchemy_Products__c</fullName>
    <label>Additional Alchemy Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Promo UB6</fullName>
            </value>
            <value>
                <fullName>Promo UB3</fullName>
            </value>
            <value>
                <fullName>Solar Stimulus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of contact associated with opportunity</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Phone_Textey__c.field-meta.xml
<CustomField>
    <fullName>Phone_Textey__c</fullName>
    <label>Phone_Textey</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/PTO_Processed__c.field-meta.xml
<CustomField>
    <fullName>PTO_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PTO Processed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BatchToCreatePTOCase.cls
global class BatchToCreatePTOCase implements Database.Batchable<SObject>, Database.AllowsCallouts, Schedulable
{
    global void execute(SchedulableContext sc){
        BatchToCreatePTOCase objBatchToCreatePTOCase = new BatchToCreatePTOCase();
        Database.executeBatch(objBatchToCreatePTOCase, 1);
    }
    
    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        String query = 'select Id, Installation_Complete_Date__c, AccountId, Contact__c, Contact__r.Email, Phone_Textey__c from Opportunity '; 
        query += 'where StageName != \'22. PTO\' AND StageName != \'Closed Won\' AND RecordType.DeveloperName = \'X3rd_Party_Design_Sales\' ';
        query += 'AND Installation_Complete_Date__c != null AND Financing_Tool__c IN (\'Sunlight\', \'Loan Pal\', \'Loanpal\') ';
        query += 'AND PTO_Processed__c = false AND Additional_Alchemy_Products__c EXCLUDES (\'Promo UB6\') ';
        System.debug('>>>>>>>'+query);
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Opportunity> lstOpportunity) {
        Opportunity objOpp = lstOpportunity[0];
        Case objCase;
        Group objGroup = [select Id from Group where DeveloperName = 'Customer_Care' and type = 'queue'];
        OrgWideEmailAddress objOrgWideAddress = [select Id, Address FROM OrgWideEmailAddress WHERE Address = 'customer.care@palmetto.com' LIMIT 1];
        EmailTemplate objTemplate = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'PTO_Reimbursment'];
        
        Id reimbursementId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Reimbursement').getRecordTypeId();
        List<simplesms.Invocable_SendMessage.SendMessageRequest> lstMessageRequest = new List<simplesms.Invocable_SendMessage.SendMessageRequest>();
        List<Messaging.SingleEmailMessage> lstSingleEmail = new List<Messaging.SingleEmailMessage>();
        
        if(objOpp.Installation_Complete_Date__c.addDays(60) == Date.today()){
            objCase = getCaseData(objOpp, objGroup.Id, reimbursementId, 'Delayed PTO - First payment');
            if(String.isNotBlank(objOpp.Phone_Textey__c)){
                lstMessageRequest.add(getMessageRequest(objOpp, 'Contact-1429'));
            }
        }
        if(objOpp.Installation_Complete_Date__c.addDays(90) == Date.today()){
            objCase = getCaseData(objOpp, objGroup.Id, reimbursementId, 'Delayed PTO - Second payment');
            if(String.isNotBlank(objOpp.Phone_Textey__c)){
                lstMessageRequest.add(getMessageRequest(objOpp, 'Contact-8096'));
            }
        }
        if(objOpp.Installation_Complete_Date__c.addDays(120) == Date.today()){
            objCase = getCaseData(objOpp, objGroup.Id, reimbursementId, 'Delayed PTO - Third payment');
            if(String.isNotBlank(objOpp.Phone_Textey__c)){
                lstMessageRequest.add(getMessageRequest(objOpp, 'Contact-6846'));
            }
        }
        
        if(objOpp.Installation_Complete_Date__c.addDays(150) == Date.today())
            objCase = getCaseData(objOpp, objGroup.Id, reimbursementId, 'Delayed PTO - Fourth payment');
        if(objOpp.Installation_Complete_Date__c.addDays(180) == Date.today())
            objCase = getCaseData(objOpp, objGroup.Id, reimbursementId, 'Delayed PTO - Fifth payment');
        if(objOpp.Installation_Complete_Date__c.addDays(210) == Date.today())
            objCase = getCaseData(objOpp, objGroup.Id, reimbursementId, 'Delayed PTO - Sixth payment');
        
        if(objOpp.Installation_Complete_Date__c.addDays(45) == Date.today() 
            || objOpp.Installation_Complete_Date__c.addDays(75) == Date.today()
            || objOpp.Installation_Complete_Date__c.addDays(105) == Date.today())
        {
            if(String.isNotBlank(objOpp.COntact__r.Email)){
                lstSingleEmail.add(getSingleEmail(objTemplate.Id, objOrgWideAddress.Id, objOpp));
            }
        }
        try{
            if(!lstMessageRequest.isEmpty())
                simplesms.Invocable_SendMessage.sendMessage(lstMessageRequest);
        } catch(Exception e){}
        
        if(!lstSingleEmail.isEmpty())
            Messaging.sendEmail(lstSingleEmail);
        if(objCase != null)
            insert objCase;
    }
    
    private Messaging.SingleEmailMessage getSingleEmail(Id templateId, Id orgWideId, Opportunity objOpp){
        Messaging.SingleEmailMessage objSingleEmail = new Messaging.SingleEmailMessage();
        objSingleEmail.setTemplateId(templateId);
        objSingleEmail.setTargetObjectId(objOpp.Contact__c);
        objSingleEmail.setWhatId(objOpp.Id);
        objSingleEmail.setOrgWideEmailAddressId(orgWideId);
        
        return objSingleEmail;
    }
    
    private simplesms.Invocable_SendMessage.SendMessageRequest getMessageRequest(Opportunity objOpp, String templateCode){
        simplesms.Invocable_SendMessage.SendMessageRequest objMessageRequest = new simplesms.Invocable_SendMessage.SendMessageRequest();
        objMessageRequest.fromNumber = '8437018055';
        objMessageRequest.parentId = objOpp.Id;
        objMessageRequest.ownerId = '0052L000003HoWsQAK';
        objMessageRequest.toNumber = objOpp.Phone_Textey__c;
        objMessageRequest.templateCode = templateCode;
        
        return objMessageRequest;
    }
    
    private Case getCaseData(Opportunity objOpp, Id ownerId, Id reimbursementId, String subject){
        Case objCase = new Case();
        objCase.AccountId = objOpp.AccountId;
        objCase.Check_Request_Date__c = Date.today();
        objCase.CaseType__c = 'Sales Op';
        objCase.Company_Cost__c = 'Yes';
        objCase.ContactId = objOpp.Contact__c;
        objCase.Opportunity__c = objOpp.Id;
        objCase.OwnerID = ownerId;
        objCase.Reason_1__c = 'PTO Delay';
        objCase.RecordTypeId = reimbursementId;
        objCase.Status = 'New';
        objCase.Subject = subject;
        objCase.Type__c = 'Delays/Extended Timelines';

        return objCase;
    }
    
    global void finish(Database.BatchableContext context) {
        
    }
}