unpackaged/main/default/objects/Case/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CaseType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New-Case Created</fullName>
            </value>
            <value>
                <fullName>Reimburement Under Review</fullName>
            </value>
            <value>
                <fullName>Reimburement Approved</fullName>
            </value>
            <value>
                <fullName>Reimburesment Declined</fullName>
            </value>
            <value>
                <fullName>Roof Review Required</fullName>
            </value>
            <value>
                <fullName>Roof Review Pending Site Visit</fullName>
            </value>
            <value>
                <fullName>Re-Roof Required Pending Quote</fullName>
            </value>
            <value>
                <fullName>Customer Accepted- Pending Coordination</fullName>
            </value>
            <value>
                <fullName>Re-Roof Underway</fullName>
            </value>
            <value>
                <fullName>Re-Roof Complete- Pending JCO</fullName>
            </value>
            <value>
                <fullName>Roof Complete- Ready for invoice</fullName>
            </value>
            <value>
                <fullName>Roof Reviewed- Re-Roof Not Needed</fullName>
            </value>
            <value>
                <fullName>Electrical Review Required</fullName>
            </value>
            <value>
                <fullName>Electrical Review Pending Site Visit</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade Required Pending Quote</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade Pending Utility Disconnect</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade Scheduled</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade at Installation</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade Complete</fullName>
            </value>
            <value>
                <fullName>Electrical Reviewed- No Upgrade Required</fullName>
            </value>
            <value>
                <fullName>Structural Review Required</fullName>
            </value>
            <value>
                <fullName>Structural Review Pending Site Visit</fullName>
            </value>
            <value>
                <fullName>Structural Upgrade Required Pending Quote</fullName>
            </value>
            <value>
                <fullName>Structural Upgrade Scheduled</fullName>
            </value>
            <value>
                <fullName>Structural Upgrade at Installation</fullName>
            </value>
            <value>
                <fullName>Structural Upgrade Complete</fullName>
            </value>
            <value>
                <fullName>Structural Reviewed- No Upgrade Needed</fullName>
            </value>
            <value>
                <fullName>Trenching Review Required</fullName>
            </value>
            <value>
                <fullName>Trenching Review Pending Site Visit</fullName>
            </value>
            <value>
                <fullName>Trenching Required Pending Quote</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Confirmed Delivered to Site</fullName>
            </value>
            <value>
                <fullName>Redelivered</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Retention.recordType-meta.xml
<RecordType>
    <fullName>Retention</fullName>
    <active>true</active>
    <businessProcess>Standard Support Process</businessProcess>
    <label>Retention</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Supply_Chain.recordType-meta.xml
<RecordType>
    <fullName>Supply_Chain</fullName>
    <active>true</active>
    <businessProcess>Design Process</businessProcess>
    <label>Supply Chain</label>
</RecordType>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Supply_Chain.recordType-meta.xml
<RecordType>
    <fullName>Supply_Chain</fullName>
    <active>true</active>
    <label>Supply Chain</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of contact associated with opportunity</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Open_Retention_Case__c.field-meta.xml
<CustomField>
    <fullName>Open_Retention_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Open Retention Case?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CaseHandler.cls
public class CaseHandler
{
    //This method is called on before insert event of trigger.
    public void onBeforeInsert(List<Case> lstCase){
        populateOpp(lstCase);
        populateContactData(lstCase);
    }
    
    //This method is called on after insert event of trigger.
    public void onAfterInsert(List<case> lstCase){
        markOpenRetentionCase(lstCase, null);
    }
    
    //This method is called on after update event of trigger.
    public void onAfterUpdate(List<case> lstCase, Map<Id, Case> mapIdToOldCase){
        markOpenRetentionCase(lstCase, mapIdToOldCase);
    }
    
    //This method is called on before update event of trigger.
    public void onBeforeUpdate(List<Case> lstCase, Map<Id, Case> mapIdToOldCase){
        autoCloseCase(lstCase, mapIdToOldCase);
    }
    
    //This method is used to auto-close the supply chain case.
    private void autoCloseCase(List<Case> lstCase, Map<Id, Case> mapIdToOldCase){
        Id supplyChainId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Supply_Chain').getRecordTypeId();
        
        Set<String> setFlowStatus = new Set<String>();
        setFlowStatus.add('Confirmed');
        setFlowStatus.add('Redelivered');
        setFlowStatus.add('Confirmed Delivered to Site');
        
        for(Case objCase : lstCase){
            Case objOldCase = mapIdToOldCase.get(objCase.Id);
            if(objCase.Flow_Status__c != objOldCase.Flow_Status__c && setFlowStatus.contains(objCase.Flow_Status__c) 
                && objCase.RecordTypeId == supplyChainId)
            {
                objCase.Status = 'Closed';
            }
        }
    }
    
    //This method is used to populate opp on cases.
    private void populateOpp(List<Case> lstCase){
        Map<Id, List<Case>> mapJobIdToLstCase = new Map<Id, List<Case>>();
        for(Case objCase : lstCase){
            if(objCase.Job__c != null && objCase.Opportunity__c == null){
                if(mapJobIdToLstCase.containsKey(objCase.Job__c)){
                    mapJobIdToLstCase.get(objCase.Job__c).add(objCase);
                } else{
                    mapJobIdToLstCase.put(objCase.Job__c, new List<Case>{objCase});
                }
            }
        }
        System.debug('>>>>>'+mapJobIdToLstCase);
        if(!mapJobIdToLstCase.isEmpty()){
            for(Job__c objJob : [select Id, Opportunity__c from Job__c where Id in :mapJobIdToLstCase.keyset()]){
                for(Case objCase : mapJobIdToLstCase.get(objJob.Id)){
                    objCase.Opportunity__c = objJob.Opportunity__c;
                }    
            }
        }
    }
    
    //This method is used to populate Contact data.
    private void populateContactData(List<Case> lstCase){
        Map<Id, List<Case>> mapOppIdToLstCase = new Map<Id, List<Case>>();
        for(Case objCase : lstCase){
            if(objCase.Opportunity__c != null){
                if(mapOppIdToLstCase.containsKey(objCase.Opportunity__c)){
                    mapOppIdToLstCase.get(objCase.Opportunity__c).add(objCase);
                } else{
                    mapOppIdToLstCase.put(objCase.Opportunity__c, new List<Case>{objCase});
                }
            }
        }
        System.debug('>>>>>'+mapOppIdToLstCase);
        if(!mapOppIdToLstCase.isEmpty()){
            for(Opportunity objOpp : [select Id, AccountId, Contact__c from Opportunity where Id in :mapOppIdToLstCase.keyset()]){
                for(Case objCase : mapOppIdToLstCase.get(objOpp.Id)){
                    objCase.AccountId = objOpp.AccountId;
                    objCase.ContactId = objOpp.Contact__c;
                }    
            }
        }
    }
    
    private void markOpenRetentionCase(List<Case> lstCase, Map<Id, Case> mapIdToOldCase){
        Id retentionId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Retention').getRecordTypeId();
        Set<Id> setOpportunityId = new Set<Id>();
        for(Case objCase : lstCase){
            if(objCase.RecordTypeId == retentionId && objCase.Opportunity__c != null){
                if(mapIdToOldCase == null){
                    setOpportunityId.add(objCase.Opportunity__c);
                } else{
                    Case objOldCase = mapIdToOldCase.get(objCase.Id);
                    if(objCase.IsClosed != objOldCase.IsClosed){
                        setOpportunityId.add(objCase.Opportunity__c);
                    }
                }
            }
        }
    
        if(!setOpportunityId.isEmpty()){
            List<Opportunity> lstOppToUpdate = new List<Opportunity>();
            for(Opportunity objOpp : [SELECT Id, Open_Retention_Case__c, 
                    (SELECT Id FROM Cases__r 
                    WHERE RecordType.DeveloperName = 'Retention' 
                    AND IsClosed = false)
                    FROM Opportunity WHERE Id IN :setOpportunityId])
            {
                if(objOpp.Cases__r.size() > 0 && objOpp.Open_Retention_Case__c == false){
                    objOpp.Open_Retention_Case__c = true;
                    lstOppToUpdate.add(objOpp);
                } else if(objOpp.Cases__r.size() == 0 && objOpp.Open_Retention_Case__c == true){
                    objOpp.Open_Retention_Case__c = false;
                    lstOppToUpdate.add(objOpp);
                }
            }
    
            if(!lstOppToUpdate.isEmpty())
                update lstOppToUpdate;
        }
    }
}