unpackaged/main/default/objects/Trade_Licensing__c/Trade_Licensing__c.object-meta.xml
<CustomObject>
    <label>Trade Licensing</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Licensing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Trade_Licensing__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Licenses/Certifications</relationshipLabel>
    <relationshipName>Trade_Licensing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Onboarding Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Interview Complete</fullName>
            </value>
            <value>
                <fullName>App Complete</fullName>
            </value>
            <value>
                <fullName>Doc Review</fullName>
            </value>
            <value>
                <fullName>Docs Failed</fullName>
            </value>
            <value>
                <fullName>MSA Signed</fullName>
            </value>
            <value>
                <fullName>Ready for Orientation</fullName>
            </value>
            <value>
                <fullName>Ready to Schedule</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Approved not Active</fullName>
            </value>
            <value>
                <fullName>Do not Schedule</fullName>
            </value>
            <value>
                <fullName>Off Boarded</fullName>
            </value>
            <value>
                <fullName>Docs Approved</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Do Not Contact</fullName>
            </value>
            <value>
                <fullName>Pending Background Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vendor__c/fields/Trade_Licensing__c.field-meta.xml
<CustomField>
    <fullName>Trade_Licensing__c</fullName>
    <label>Trade Licensing</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electrical License</fullName>
            </value>
            <value>
                <fullName>General Contractor</fullName>
            </value>
            <value>
                <fullName>Special Trade License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SendExpirationEmailToBP.cls
public class SendExpirationEmailToBP {   
    public SendExpirationEmailToBP(){}
    /*
    public void execute(SchedulableContext sc){
        sendEmail();
     
    //This method is used to send expiration Email to BP.
    private void sendEmail() 
        List<Messaging.SingleEmailMessage> lstSingleEmail = new List<Messaging.SingleEmailMessage>();
        List<Vendor__c> lstVendorToUpdate = new List<Vendor__c>();
        for(Vendor__c objVendor : [SELECT Id, Email__c, (select Id, Expiration_Date__c from Trade_Licensing__r) from Vendor__c 
                WHERE Email__c != null AND Stage__c != 'Do not Schedule'])
                 
            Boolean sendExpirationNotification = (objVendor.Trade_Licensing__r.size() == 0?false:true);
            for(Trade_Licensing__c objTradeLicensing : objVendor.Trade_Licensing__r){
                if(objTradeLicensing.Expiration_Date__c > Date.today()){
                    sendExpirationNotSendExpirationEmailToBPification = false;
                    break;
                }
                 
            if(sendExpirationNotification){
                String htmlBody = '<p>To our Valued Build Partner:</p>';
                htmlBody += '<p>Maintaining your license(s) and insurance coverage is an important part of our ongoing partnership. Please provide your updated document(s) to: buildpartners@palmetto.com to avoid any disruption of work opportunities.</p>';
                htmlBody += '<p>Thank you,</p>';
                htmlBody += '<p>Palmetto Build Partner Team</p>';
                String subject = 'Trade License Expiring notification'             
                Messaging.SingleEmailMessage objSingleEmail = new Messaging.SingleEmailMessage();
                objSingleEmail.setHTMLBody(htmlBody);
                objSingleEmail.setSubject(subject);
                objSingleEmail.setToAddresses(new List<String>{objVendor.Email__c});
                lstSingleEmail.add(objSingleEmail)             
                objVendor.Stage__c = 'Do not Schedule';
                lstVendorToUpdate.add(objVendor);
            }
             
        if(!lstSingleEmail.isEmpty())
            Messaging.sendEmail(lstSingleEmail);
        if(!lstVendorToUpdate.isEmpty())
            update lstVendorToUpdate;
    }
    */
}