unpackaged/main/default/objects/Trade_Licensing__c/Trade_Licensing__c.object-meta.xml
<CustomObject>
    <label>Trade Licensing</label>
    <nameField>
        <label>License Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Licensing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Trade_Licensing__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Licenses/Certifications</relationshipLabel>
    <relationshipName>Trade_Licensing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/fields/Trade_Licensing__c.field-meta.xml
<CustomField>
    <fullName>Trade_Licensing__c</fullName>
    <label>Trade Licensing</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electrical License</fullName>
            </value>
            <value>
                <fullName>General Contractor</fullName>
            </value>
            <value>
                <fullName>Special Trade License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SendExpirationEmailToBPTest.cls
@isTest
public class SendExpirationEmailToBPTest
{
    
    static testMethod void unitTest(){
        /*
        Vendor__c objVendor = new Vendor__c();
        objVendor.Name = 'Test';
        objVendor.Email__c = 'test@test.com';
        insert objVendor     
        Trade_Licensing__c objTradeLicensing = new Trade_Licensing__c();
        objTradeLicensing.Name = 'test';
        objTradeLicensing.Vendor__c = objVendor.Id;
        objTradeLicensing.Expiration_Date__c = Date.today();
        insert objTradeLicensing     
        new SendExpirationEmailToBP().execute(null);
        */
        SendExpirationEmailToBP test = new SendExpirationEmailToBP();


    }
}