unpackaged/main/default/objects/Commission_Plan__c/Commission_Plan__c.object-meta.xml
<CustomObject>
    <label>Commission Plan</label>
    <nameField>
        <label>Commission Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commission_Plan__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory 
{	
	public static Opportunity createOpportunity(string reportTypeId,string opp_name,string account_id,string stage,string location)
    {
        Opportunity opp_obj = new Opportunity();
        opp_obj.RecordTypeId = reportTypeId;
        opp_obj.Name = opp_name;
        opp_obj.AccountId = account_id;
        opp_obj.StageName = stage;
        opp_obj.Location__c = location;
        opp_obj.CloseDate = system.Date.today() + 2;
        return opp_obj;
        
    }
    
    public static Account createAccount(string name, string recordType)
    {
        account acc_obj = new Account();
        acc_obj.Name = name;
        acc_obj.RecordTypeId = recordType;
        return acc_obj;
    }
    
    public static Contact createContact(string first_name, string last_name,string account_id)
    {
        Contact cont_obj = new Contact();
    	cont_obj.FirstName = first_name;
        cont_obj.LastName = last_name;
        cont_obj.AccountId = account_id;
        return cont_obj;
    }
    
    public static Commission_Plan__c createCommissionPlan(string name)
    {
        Commission_Plan__c commission_plan_obj = new Commission_Plan__c();
        commission_plan_obj.Name = name;
        return commission_plan_obj;
    }
    
    public List< User > createUsers( integer count )
    {
        system.assert( count > 0 );
        List< User > userList = new List< User >();
        Profile stdProfile = [ select id from profile where name= 'System Admin - Developer' ];
        while( count-- > 0 )
        {
            userList.add( new User( ProfileId = stdProfile.Id, Alias = 'u' + count, IsActive = true, username = 'u@test.com' + count, email = 'u@test.com' + count, LastName = 'u' + count,TimeZonesIdKey = 'GMT', EmailEncodingKey = 'UTF-8', LanguageLocaleKey='en_US', LocalesIdKey = 'en_US' ) );
        }
        insert userList;
        return userList;
    }
}