unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
            <value>
                <fullName>Start Date for Materials Delivery Committed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Fulfillment_Method__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Method__c</fullName>
    <label>Fulfillment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct to Job</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Materials_Direct_To_Site_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Materials_Direct_To_Site_Confirmation__c</fullName>
    <inlineHelpText>select whether the customer has accepted (yes) or rejected (no) Direct-to-Site materials delivery.</inlineHelpText>
    <label>Materials-Direct-To-Site Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Materials_Direct_To_Site_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Materials_Direct_To_Site_Instructions__c</fullName>
    <label>Materials-Direct-To-Site Instructions</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/NetSuite_Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Inventory_Location__c</fullName>
    <label>NetSuite Inventory Location</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Site Approval</fullName>
            </value>
            <value>
                <fullName>Virtual Survey</fullName>
            </value>
            <value>
                <fullName>Physical Survey</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MA SMART)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (IL ABP)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (RI ReGrowth)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (CT Green Bank)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (PennAEPS)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NJ TREC)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MD)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NV)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (Austin TX)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (San Antonio TX)</fullName>
            </value>
            <value>
                <fullName>Contract Processing- Document Verification</fullName>
            </value>
            <value>
                <fullName>Document Verification</fullName>
            </value>
            <value>
                <fullName>Job Close Out</fullName>
            </value>
            <value>
                <fullName>HOA</fullName>
            </value>
            <value>
                <fullName>Permit Issuance</fullName>
            </value>
            <value>
                <fullName>Interconnection</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>Loan except Sunnova</fullName>
            </value>
            <value>
                <fullName>Sunnova</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
            <value>
                <fullName>Installation Scheduling</fullName>
            </value>
            <value>
                <fullName>System Activation</fullName>
            </value>
            <value>
                <fullName>PV Materials Verification</fullName>
            </value>
            <value>
                <fullName>Additional Adder Coordination</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade</fullName>
            </value>
            <value>
                <fullName>Ground Mount Coordination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Design.recordType-meta.xml
<RecordType>
    <fullName>Design</fullName>
    <active>true</active>
    <label>Site Approval</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Installation_Scheduling.recordType-meta.xml
<RecordType>
    <fullName>Installation_Scheduling</fullName>
    <active>true</active>
    <label>Installation Scheduling</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Supply_Chain.recordType-meta.xml
<RecordType>
    <fullName>Supply_Chain</fullName>
    <active>true</active>
    <label>Supply Chain</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of contact associated with opportunity</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fulfillment_Method__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Method__c</fullName>
    <label>Fulfillment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct to Job</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Materials_Direct_To_Site_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Materials_Direct_To_Site_Confirmation__c</fullName>
    <inlineHelpText>select whether the customer has accepted (yes) or rejected (no) Direct-to-Site materials delivery.</inlineHelpText>
    <label>Materials-Direct-To-Site Confirmation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Materials_Direct_To_Site_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Materials_Direct_To_Site_Instructions__c</fullName>
    <inlineHelpText>The customer provides a description where on their property materials can be staged and any additional information regarding delivery.</inlineHelpText>
    <label>Materials-Direct-To-Site Instructions</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NetSuite_Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Inventory_Location__c</fullName>
    <inlineHelpText>The NetSuite inventory location that will fulfil this job.

Custom Fields</inlineHelpText>
    <label>NetSuite Inventory Location</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Milestone__c/fields/Design_Completed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Design_Completed_Milestone__c</fullName>
    <label>Design Completed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateProjectMilestoneV3.cls
global class BatchToUpdateProjectMilestoneV3 implements Database.Batchable<SObject>
{   
    String oppId;
    global BatchToUpdateProjectMilestoneV3(String oppId){
        this.oppId = oppId;
    }

    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        String query = System.Label.Project_Milestone_V3;
        if(String.isNotBlank(oppId)){
            query += ' AND Opportunity__c =: oppId';
        }
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Project_Milestone__c> lstProjectMilestone) {
        Project_Milestone__c objProjectMilestone = lstProjectMilestone[0];
        if(objProjectMilestone.Opportunity__c != null){
            List<Job__c> lstInstallationJob = [SELECT Id, Installation_Start_Date__c 
                    FROM Job__c 
                    WHERE Opportunity__c = :objProjectMilestone.Opportunity__c
                    AND RecordType.DeveloperName = 'Installation_Scheduling'];
            
            String flowStatus = '';
            if(objProjectMilestone.Design_Completed_Milestone__c == null){
                flowStatus = 'Awaiting Design';
            }
            
            if(objProjectMilestone.Design_Completed_Milestone__c != null){
                if(lstInstallationJob == null || lstInstallationJob.isEmpty()){
                    flowStatus = 'Design / BOM Complete';
                } else{
                    if(lstInstallationJob[0].Installation_Start_Date__c == null){
                        flowStatus = 'Design / BOM Complete';
                    } else{
                        flowStatus = 'Start Date for Materials Delivery Committed';
                    }
                }
            }
            
        
            Id supplyChainId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Supply_Chain').getRecordTypeId();   
            
            String jobName = (String.isNotBlank(objProjectMilestone.Opportunity__r.Contact__c)?(objProjectMilestone.Opportunity__r.Contact__r.Name + ' - '):'') + 'Supply Chain';
            Job__c objJob = new Job__c();
            objJob.Name = jobName;
            objJob.RecordTypeId = supplyChainId;
            objJob.Job_Status__c = 'New';
            objJob.Opportunity__c = objProjectMilestone.Opportunity__c;
            objJob.OwnerId = (objProjectMilestone.Opportunity__r.Owner.IsActive == true?objProjectMilestone.Opportunity__r.OwnerId:Userinfo.getUserId());
            objJob.Type__c = 'PV Materials Verification';
            objJob.Flow_Status__c = flowStatus;
            objJob.Fulfillment_Method__c = objProjectMilestone.Opportunity__r.Fulfillment_Method__c;
            objJob.Materials_Direct_To_Site_Instructions__c = objProjectMilestone.Opportunity__r.Materials_Direct_To_Site_Instructions__c;
            objJob.Materials_Direct_To_Site_Confirmation__c = objProjectMilestone.Opportunity__r.Materials_Direct_To_Site_Confirmation__c;
            objJob.NetSuite_Inventory_Location__c = objProjectMilestone.Opportunity__r.NetSuite_Inventory_Location__c;
            
            insert objJob;
        }
    }
    
    global void finish(Database.BatchableContext context) {
        
    }
}