unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Automation__c.field-meta.xml
<CustomField>
    <fullName>Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <formula>Opportunity__r.Installation_Complete_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>TEXT(Opportunity__r.Location__c)</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Site Approval</fullName>
            </value>
            <value>
                <fullName>Virtual Survey</fullName>
            </value>
            <value>
                <fullName>Physical Survey</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MA SMART)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (IL ABP)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (RI ReGrowth)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (CT Green Bank)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (PennAEPS)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NJ TREC)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MD)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NV)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (Austin TX)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (San Antonio TX)</fullName>
            </value>
            <value>
                <fullName>Contract Processing- Document Verification</fullName>
            </value>
            <value>
                <fullName>Document Verification</fullName>
            </value>
            <value>
                <fullName>Job Close Out</fullName>
            </value>
            <value>
                <fullName>HOA</fullName>
            </value>
            <value>
                <fullName>Permit Issuance</fullName>
            </value>
            <value>
                <fullName>Interconnection</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>Loan except Sunnova</fullName>
            </value>
            <value>
                <fullName>Sunnova</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
            <value>
                <fullName>Installation Scheduling</fullName>
            </value>
            <value>
                <fullName>System Activation</fullName>
            </value>
            <value>
                <fullName>PV Materials Verification</fullName>
            </value>
            <value>
                <fullName>Additional Adder Coordination</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade</fullName>
            </value>
            <value>
                <fullName>Ground Mount Coordination</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Business_Processing.recordType-meta.xml
<RecordType>
    <fullName>Business_Processing</fullName>
    <active>true</active>
    <label>Contract Processing</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Design.recordType-meta.xml
<RecordType>
    <fullName>Design</fullName>
    <active>true</active>
    <label>Site Approval</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Supply_Chain.recordType-meta.xml
<RecordType>
    <fullName>Supply_Chain</fullName>
    <active>true</active>
    <label>Supply Chain</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Milestone__c/fields/Contract_Signed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_Milestone__c</fullName>
    <label>Contract Signed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Design_Completed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Design_Completed_Milestone__c</fullName>
    <label>Design Completed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateProjectMilestoneV3Test.cls
@isTest
private class BatchToUpdateProjectMilestoneV3Test
{   
    static testMethod void unitTest(){
        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;
        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'Sunlight';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'New Jersey';
        insert objOpportunity;
        
        Id contractProcessingId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Business_Processing').getRecordTypeId();
        Job__c objJob = new Job__c();
        objJob.Opportunity__c = objOpportunity.Id;
        objJob.RecordTypeId = contractProcessingId;
        objJob.Type__c = 'Contract Processing- Document Verification';
        objJob.Automation__c = true;
        insert objJob;
        
        System.debug('>>>>>'+[SELECT Id, RecordType.DeveloperName FROM Job__c]);
        delete [SELECT Id from Job__c WHERE RecordType.DeveloperName = 'Supply_Chain' and Opportunity__c = :objOpportunity.Id];
        
        Project_Milestone__c objMilestone = [SELECT Id, Contract_Signed_Milestone__c FROM Project_Milestone__c WHERE Opportunity__c = :objOpportunity.Id];
        System.debug('>>>>>'+objMilestone);
        objMilestone.Design_Completed_Milestone__c = Datetime.now();
        update objMilestone;
        
        Database.executeBatch(new BatchToUpdateProjectMilestoneV3(objOpportunity.Id), 1);
    }
}