unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Design.recordType-meta.xml
<RecordType>
    <fullName>Design</fullName>
    <active>true</active>
    <label>Site Approval</label>
</RecordType>

unpackaged/main/default/classes/PermitJobOpportunityControllerTest.cls
@isTest
public class PermitJobOpportunityControllerTest {
    //Note: name of tests: whatDoesTheTest_WhatExpectToReceive
    @IsTest
    static void insertBuildOnlyOpportunity_GetPermittingJob(){
        Id buildOnlyId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Build Only').getRecordTypeId();
        Account anAccount = TestDataFactory.createAccount('Test Acc', buildOnlyId);
        INSERT anAccount;
        
        Id buildOnlyOppId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Build Only').getRecordTypeId();
        Opportunity anOpportunity = TestDataFactory.createOpportunity(buildOnlyOppId, 'Test Opp', anAccount.Id, '13. Engineering Design Complete', 'Alabama');
        anOpportunity.CloseDate = Date.today().addDays(5);
        INSERT anOpportunity;
        
        anOpportunity.StageName = '14. Permit Sent';
        UPDATE anOpportunity;
        
        Test.startTest();
        anOpportunity.StageName = '13. Engineering Design Complete';
        UPDATE anOpportunity;

        Job__c permittingJob = [SELECT ID FROM Job__c WHERE Opportunity__c = :anOpportunity.Id LIMIT 1];

        Opportunity verifyOpp = PermitJobOpportunityController.getOpportunities(permittingJob.Id);

        Test.stopTest();

        System.assertEquals(anOpportunity.Id, verifyOpp.Id);
    }
}