unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
            <value>
                <fullName>Survey Complete - Confirmed</fullName>
            </value>
            <value>
                <fullName>Contract Processing Completed</fullName>
            </value>
            <value>
                <fullName>Permit Received</fullName>
            </value>
            <value>
                <fullName>Permit Submitted</fullName>
            </value>
            <value>
                <fullName>Installation Scheduled</fullName>
            </value>
            <value>
                <fullName>Installation Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <formula>Opportunity__r.Installation_Complete_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>TEXT(Opportunity__r.Location__c)</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Site Approval</fullName>
            </value>
            <value>
                <fullName>Virtual Survey</fullName>
            </value>
            <value>
                <fullName>Physical Survey</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MA SMART)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (IL ABP)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (RI ReGrowth)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (CT Green Bank)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (PennAEPS)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NJ TREC)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MD)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NV)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (Austin TX)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (San Antonio TX)</fullName>
            </value>
            <value>
                <fullName>Contract Processing- Document Verification</fullName>
            </value>
            <value>
                <fullName>Document Verification</fullName>
            </value>
            <value>
                <fullName>Job Close Out</fullName>
            </value>
            <value>
                <fullName>HOA</fullName>
            </value>
            <value>
                <fullName>Permit Issuance</fullName>
            </value>
            <value>
                <fullName>Interconnection</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>Loan except Sunnova</fullName>
            </value>
            <value>
                <fullName>Sunnova</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
            <value>
                <fullName>Installation Scheduling</fullName>
            </value>
            <value>
                <fullName>System Activation</fullName>
            </value>
            <value>
                <fullName>PV Materials Verification</fullName>
            </value>
            <value>
                <fullName>Additional Adder Coordination</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade</fullName>
            </value>
            <value>
                <fullName>Ground Mount Coordination</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Usage_Verification_Complete__c.field-meta.xml
<CustomField>
    <fullName>Usage_Verification_Complete__c</fullName>
    <label>Usage Verification Complete</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Business_Processing.recordType-meta.xml
<RecordType>
    <fullName>Business_Processing</fullName>
    <active>true</active>
    <label>Contract Processing</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Design.recordType-meta.xml
<RecordType>
    <fullName>Design</fullName>
    <active>true</active>
    <label>Site Approval</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Document_Verification.recordType-meta.xml
<RecordType>
    <fullName>Document_Verification</fullName>
    <active>true</active>
    <description>Document Processing</description>
    <label>Document Verification</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Installation_Scheduling.recordType-meta.xml
<RecordType>
    <fullName>Installation_Scheduling</fullName>
    <active>true</active>
    <label>Installation Scheduling</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Permitting.recordType-meta.xml
<RecordType>
    <fullName>Permitting</fullName>
    <active>true</active>
    <label>Permitting</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/PTO.recordType-meta.xml
<RecordType>
    <fullName>PTO</fullName>
    <active>true</active>
    <label>PTO</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/SiteSurvey.recordType-meta.xml
<RecordType>
    <fullName>SiteSurvey</fullName>
    <active>true</active>
    <label>Site Survey</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchToCreateProjectMilestoneTest.cls
@isTest(seeAllData=true)
private class BatchToCreateProjectMilestoneTest
{
    static testMethod void unitTest(){
        System.Test.startTest();
        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        insert objAccount;
        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', objAccount.Id, '1. Appointment Set', 'Alabama');
        objOpportunity.Financing_Tool__c = 'Sunlight';
        objOpportunity.Installation_Complete_Date__c = Date.today().addDays(5);
        objOpportunity.Location__c = 'New Jersey';
        insert objOpportunity;
        
        delete [SELECT Id FROM Project_Milestone__c LIMIT 1000];
        
        Id contractProcessingId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Business_Processing').getRecordTypeId();
        Job__c objJob = new Job__c();
        objJob.Opportunity__c = objOpportunity.Id;
        objJob.RecordTypeId = contractProcessingId;
        objJob.Type__c = 'Contract Processing- Document Verification';
        insert objJob;
        
        objJob.Flow_Status__c = 'Contract Processing Completed';
        update objJob;
        
        Id siteSurveyId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('SiteSurvey').getRecordTypeId();
        Job__c objSiteSurveyJob = new Job__c();
        objSiteSurveyJob.Opportunity__c = objOpportunity.Id;
        objSiteSurveyJob.RecordTypeId = siteSurveyId;
        insert objSiteSurveyJob;
        
        objSiteSurveyJob.Type__c = 'Virtual Survey';
        objSiteSurveyJob.Flow_Status__c = 'Survey Complete - Confirmed';
        update objSiteSurveyJob;
        
        
        Id documentVerId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Document_Verification').getRecordTypeId();
        Job__c objDocVerJob = new Job__c();
        objDocVerJob.Opportunity__c = objOpportunity.Id;
        objDocVerJob.RecordTypeId = documentVerId;
        insert objDocVerJob;
        
        objDocVerJob.Usage_Verification_Complete__c = Date.today();
        update objDocVerJob;
        
        Id PermittingId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Permitting').getRecordTypeId();    
        Job__c objPermittingJob = new Job__c();
        objPermittingJob.Name = 'test';
        objPermittingJob.Opportunity__c = objOpportunity.Id;
        objPermittingJob.RecordTypeId = PermittingId;
        try{
            insert objPermittingJob;
        }catch(Exception e){}
        
        Id siteApprovalId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Design').getRecordTypeId();    
        Job__c objSiteApprovalJob = new Job__c();
        objSiteApprovalJob.Flow_Status__c = 'Site Approved';
        objSiteApprovalJob.RecordTypeId = siteApprovalId;
        objSiteApprovalJob.Opportunity__c = objOpportunity.Id;
        insert objSiteApprovalJob;
        
        objPermittingJob = new Job__c();
        try{
            objPermittingJob.RecordTypeId = PermittingId;
            objPermittingJob.Opportunity__c = objOpportunity.Id;
            objPermittingJob.Flow_Status__c = 'Permit Received';
            insert objPermittingJob;
        }catch(Exception e){}
        /*
        objPermittingJob.Flow_Status__c = 'Permit Submitted';
        insert objPermittingJob;
        
        objPermittingJob.Flow_Status__c = 'Permit Received';
        update objPermittingJob;
        */
        objOpportunity.StageName = '17. Install Ready';
        update objOpportunity;
        Database.executeBatch(new BatchToCreateProjectMilestone(), 1);
        System.Test.stopTest();

        Id installationSchedulingId = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Installation_Scheduling').getRecordTypeId(); 
        Job__c objInstallationJob = new Job__c();//[SELECT Id FROM Job__c WHERE RecordType.DeveloperName = 'Installation_Scheduling' LIMIT 1];
        objInstallationJob.RecordTypeId = installationSchedulingId;
        objInstallationJob.Opportunity__c = objOpportunity.Id;
        objInstallationJob.Flow_Status__c = 'Installation Scheduled';
        objInstallationJob.Installation_Start_Date__c = Date.today();
        insert objInstallationJob;
        
        objInstallationJob.Flow_Status__c = 'Installation Complete';
        update objInstallationJob;
        
        objOpportunity.StageName = '19. Install Completed';
        update objOpportunity;
        
        Database.executeBatch(new BatchToUpdateProjectMilestone(objOpportunity.Id), 1);
    }
    
    static testMethod void unitTest2(){
        Job__c objJob = [SELECT Id, Opportunity__c FROM Job__c WHERE RecordType.DeveloperName = 'PTO' AND Opportunity__c != null LIMIT 1];
        delete [SELECT Id FROM Project_Milestone__c WHERE Opportunity__c = :objJob.Opportunity__c];
        
        Project_Milestone__c objMilestone = new Project_Milestone__c();
        objMilestone.Name = 'test';
        objMilestone.Opportunity__c = objJob.Opportunity__c;
        insert objMilestone;
        
        Database.executeBatch(new BatchToUpdateProjectMilestone(objJob.Opportunity__c), 1);
    }
}