unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account_Balance__c.field-meta.xml
<CustomField>
    <fullName>Account_Balance__c</fullName>
    <label>Account Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inspection</fullName>
            </value>
            <value>
                <fullName>Site Approval</fullName>
            </value>
            <value>
                <fullName>Virtual Survey</fullName>
            </value>
            <value>
                <fullName>Physical Survey</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MA SMART)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (IL ABP)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (RI ReGrowth)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (CT Green Bank)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (PennAEPS)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NJ TREC)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (MD)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (NV)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (Austin TX)</fullName>
            </value>
            <value>
                <fullName>Incentive Submittal (San Antonio TX)</fullName>
            </value>
            <value>
                <fullName>Contract Processing- Document Verification</fullName>
            </value>
            <value>
                <fullName>Document Verification</fullName>
            </value>
            <value>
                <fullName>Job Close Out</fullName>
            </value>
            <value>
                <fullName>HOA</fullName>
            </value>
            <value>
                <fullName>Permit Issuance</fullName>
            </value>
            <value>
                <fullName>Interconnection</fullName>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>Loan except Sunnova</fullName>
            </value>
            <value>
                <fullName>Sunnova</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
            <value>
                <fullName>Installation Scheduling</fullName>
            </value>
            <value>
                <fullName>System Activation</fullName>
            </value>
            <value>
                <fullName>PV Materials Verification</fullName>
            </value>
            <value>
                <fullName>Additional Adder Coordination</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade</fullName>
            </value>
            <value>
                <fullName>Ground Mount Coordination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Financing.recordType-meta.xml
<RecordType>
    <fullName>Financing</fullName>
    <active>true</active>
    <label>Financing</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Date__c</fullName>
    <label>Contract Received Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SA_Approved__c.field-meta.xml
<CustomField>
    <fullName>SA_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>System Activation (M2) Approved</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CreateFinanceJobBatch.cls
global class CreateFinanceJobBatch implements Database.Batchable<SObject> {
    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        Date startDate = Date.newInstance(2020, 7, 1);
        String query = 'select Id, Amount, Account.celigo_sfnsio__Account_Balance__c from Opportunity '; 
        query += 'where Contract_Received_Date__c >= :startDate ';
        query += 'AND Financing_Tool__c IN (\'Loanpal\') ';
        query += 'AND SA_Approved__c = false ';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Opportunity> lstOpportunity) {
        List<Job__c> lstJobToInsert = new List<Job__c>();
        
        Id financingId = Schema.SObjectType.Job__c.getRecordTypeInfosByName().get('Financing').getRecordTypeId();
        Group objGroup = [select Id from Group where Name = 'FinOps' and type = 'Queue'];
        for(Opportunity objOpportunity : lstOpportunity){
            Job__c objJob = new Job__c();
            objJob.Name = 'Financial Operations (FinOps) Job';
            objJob.RecordTypeId = financingId;
            objJob.Opportunity__c = objOpportunity.Id;
            objJob.OwnerId = objGroup.Id;
            objJob.Type__c = 'Loan except Sunnova';
            //objJob.Amount__c = objOpportunity.Amount;
            objJob.Account_Balance__c = objOpportunity.Account.celigo_sfnsio__Account_Balance__c;

            lstJobToInsert.add(objJob);
        }

        if(!lstJobToInsert.isEmpty())
            insert lstJobToInsert;
    }
    
    global void finish(Database.BatchableContext context) {}
}