unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Automation__c.field-meta.xml
<CustomField>
    <fullName>Automation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
            <value>
                <fullName>Installation Scheduled</fullName>
            </value>
            <value>
                <fullName>Installation Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <formula>Opportunity__r.Installation_Complete_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Design.recordType-meta.xml
<RecordType>
    <fullName>Design</fullName>
    <active>true</active>
    <label>Site Approval</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Installation_Scheduling.recordType-meta.xml
<RecordType>
    <fullName>Installation_Scheduling</fullName>
    <active>true</active>
    <label>Installation Scheduling</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateInstallationCompleteTest.cls
@isTest
public with sharing class BatchToUpdateInstallationCompleteTest {
    @IsTest
    static void methodName(){
        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account anAccount = TestDataFactory.createAccount('Palmetto Acc', designSalesId);
        insert anAccount;
        
        Id oppDesignSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity anOpportunity = TestDataFactory.createOpportunity(oppDesignSalesId, 'Test Opp', anAccount.Id, '17. Install Ready', 'Alabama');
        insert anOpportunity;

        Id intallationJob = Schema.SObjectType.Job__c
        .getRecordTypeInfosByDeveloperName()
        .get('Installation_Scheduling')
        .getRecordTypeId();

        Job__c aJob = new Job__c(
            Name = 'Test Job Installation_Scheduling',
            Opportunity__c = anOpportunity.Id,
            RecordTypeId = intallationJob,
            Flow_Status__c = 'Installation Scheduled',
            Installation_Start_Date__c = DateTime.now().date().addDays(-2),
            Automation__c = true
        );
        insert aJob;

        aJob.Flow_Status__c = 'Installation Complete';
        update aJob;

        anOpportunity.Installation_Complete_Date__c = null;
        anOpportunity.StageName = '20. Inspection Scheduled';
        update anOpportunity;    

        Test.startTest();
        Database.executeBatch(new BatchToUpdateInstallationComplete());
        Test.stopTest();
        
        Opportunity updatedOpp = [SELECT Id, Installation_Complete_Date__c FROM Opportunity WHERE Id = :anOpportunity.Id];
        System.assertNotEquals(null, updatedOpp.Installation_Complete_Date__c, 'The opportunity installation complete date was not updated');
    }
}