unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
            <value>
                <fullName>Survey Complete - Confirmed</fullName>
            </value>
            <value>
                <fullName>Contract Processing Completed</fullName>
            </value>
            <value>
                <fullName>Permit Received</fullName>
            </value>
            <value>
                <fullName>Permit Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>PTO Granted</fullName>
            </value>
            <value>
                <fullName>New- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Installation Scheduled</fullName>
            </value>
            <value>
                <fullName>Installation Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <formula>Opportunity__r.Installation_Complete_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Start_Date_Observed__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date_Observed__c</fullName>
    <inlineHelpText>First "Installation Start Date" to have elapsed without being rescheduled, called off, or cancelled within 1 calendar day.</inlineHelpText>
    <label>Installation Start Date - Observed</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Usage_Verification_Complete__c.field-meta.xml
<CustomField>
    <fullName>Usage_Verification_Complete__c</fullName>
    <label>Usage Verification Complete</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Business_Processing.recordType-meta.xml
<RecordType>
    <fullName>Business_Processing</fullName>
    <active>true</active>
    <label>Contract Processing</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Design.recordType-meta.xml
<RecordType>
    <fullName>Design</fullName>
    <active>true</active>
    <label>Site Approval</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Document_Verification.recordType-meta.xml
<RecordType>
    <fullName>Document_Verification</fullName>
    <active>true</active>
    <description>Document Processing</description>
    <label>Document Verification</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Installation_Scheduling.recordType-meta.xml
<RecordType>
    <fullName>Installation_Scheduling</fullName>
    <active>true</active>
    <label>Installation Scheduling</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Permitting.recordType-meta.xml
<RecordType>
    <fullName>Permitting</fullName>
    <active>true</active>
    <label>Permitting</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/PTO.recordType-meta.xml
<RecordType>
    <fullName>PTO</fullName>
    <active>true</active>
    <label>PTO</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/SiteSurvey.recordType-meta.xml
<RecordType>
    <fullName>SiteSurvey</fullName>
    <active>true</active>
    <label>Site Survey</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Milestone__c/fields/Contract_Received_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Milestone__c</fullName>
    <label>Contract Received - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Contract_Signed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_Milestone__c</fullName>
    <label>Contract Signed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Design_Completed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Design_Completed_Milestone__c</fullName>
    <label>Design Completed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Energy_Bill_checked__c.field-meta.xml
<CustomField>
    <fullName>Energy_Bill_checked__c</fullName>
    <label>Usage Verification Complete</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Inspection_Complete_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Complete_Milestone__c</fullName>
    <label>Inspection Complete - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Inspection_Scheduled_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Scheduled_Milestone__c</fullName>
    <label>Inspection Scheduled - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Installation_Completed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Installation_Completed_Milestone__c</fullName>
    <label>Installation Completed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Installation_Ready_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Installation_Ready_Milestone__c</fullName>
    <label>Installation Ready - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Installation_Scheduled_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Installation_Scheduled_Milestone__c</fullName>
    <label>Installation Scheduled - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Installation_Started_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Installation_Started_Milestone__c</fullName>
    <label>Installation Started - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Permit_Received_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Permit_Received_Milestone__c</fullName>
    <label>Permit Approved - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Permit_Submitted_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Permit_Submitted_Milestone__c</fullName>
    <label>Permit Submitted - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/PTO_Complete_Milestone__c.field-meta.xml
<CustomField>
    <fullName>PTO_Complete_Milestone__c</fullName>
    <label>PTO Complete - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/PTO_Submitted_Milestone__c.field-meta.xml
<CustomField>
    <fullName>PTO_Submitted_Milestone__c</fullName>
    <label>PTO Submitted - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Survey_Complete_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Survey_Complete_Confirmed__c</fullName>
    <label>Survey Complete Confirmed</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateProjectMilestone.cls
global class BatchToUpdateProjectMilestone implements Database.Batchable<SObject>
{   
    String oppId;
    global BatchToUpdateProjectMilestone(String oppId){
        this.oppId = oppId;
    }

    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        String query = System.Label.Project_Milestone_Query_2;
        if(String.isNotBlank(oppId)){
            query += ' WHERE Opportunity__c =: oppId';
        }
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Project_Milestone__c> lstProjectMilestone) {
        Project_Milestone__c objProjectMilestone = lstProjectMilestone[0];
        if(objProjectMilestone.Opportunity__c != null){
            Set<Id> setJobId = new Set<Id>();
            Map<String, Job__c> mapRecordTypeNameToJob = new Map<String, Job__c>();
            for(Job__c objJob : [
                    SELECT Id, Flow_Status__c, Installation_Start_Date__c, RecordType.DeveloperName, 
                    CreatedDate, Usage_Verification_Complete__c
                    FROM Job__c 
                    WHERE Opportunity__c = :objProjectMilestone.Opportunity__c])
            {
                setJobId.add(objJob.Id);
                mapRecordTypeNameToJob.put(objJob.RecordType.DeveloperName, objJob);
            }
            
            if(!setJobId.isEmpty()){
                Map<Id, List<Job__History>> mapJobIdToLstFlowStatusHistory = new Map<Id, List<Job__History>>();
                Set<String> setUniqueCombo = new Set<String>();
                for(Job__History objJobHistory : [
                        SELECT Id, ParentId, CreatedDate, Field, OldValue, NewValue 
                        FROM Job__History 
                        WHERE Field = 'Flow_Status__c'
                        AND ParentId IN :setJobId
                        ORDER By Createddate])
                {
                    String uniqueCombo = objJobHistory.ParentId + '::' + objJobHistory.NewValue;
                    
                    if(!setUniqueCombo.contains(uniqueCombo)){
                        if(mapJobIdToLstFlowStatusHistory.containsKey(objJobHistory.ParentId)){
                            mapJobIdToLstFlowStatusHistory.get(objJobHistory.ParentId).add(objJobHistory);
                        } else{
                            mapJobIdToLstFlowStatusHistory.put(objJobHistory.ParentId, new List<Job__History>{objJobHistory});        
                        }
                        
                        setUniqueCombo.add(uniqueCombo);
                    }
                }
                /*
                Map<Id, Job__History> mapJobIdToInstallationHistory = new Map<Id, Job__History>();
                for(Job__History objJobHistory : [
                        SELECT Id, ParentId, CreatedDate, Field, OldValue, NewValue 
                        FROM Job__History 
                        WHERE Field = 'Installation_Start_Date__c'
                        AND ParentId IN :setJobId 
                        ORDER BY CreatedDate desc])
                {
                    if(objProjectMilestone.Opportunity__r.Installation_Complete_Date__c == null){
                        mapJobIdToInstallationHistory.put(objJobHistory.ParentId, objJobHistory);    
                        break;
                    } else if(objProjectMilestone.Opportunity__r.Installation_Complete_Date__c >= objJobHistory.CreatedDate){
                        mapJobIdToInstallationHistory.put(objJobHistory.ParentId, objJobHistory);    
                        break;
                    }
                }*/
                
                //Code to populate the milestone fields.
                Boolean updateMilestone = false;
                if(objProjectMilestone.Contract_Signed_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Business_Processing') != null){
                        Job__c objContractProcessingJob = mapRecordTypeNameToJob.get('Business_Processing');
                        objProjectMilestone.Contract_Signed_Milestone__c = objContractProcessingJob.CreatedDate;
                        updateMilestone = true;
                    }
                }
                
                if(objProjectMilestone.Contract_Received_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Business_Processing') != null){
                        Job__c objContractProcessingJob = mapRecordTypeNameToJob.get('Business_Processing');
                        if(mapJobIdToLstFlowStatusHistory.get(objContractProcessingJob.Id) != null){
                            Datetime receivedMilestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objContractProcessingJob.Id)){
                                if(objJobHistory.NewValue == 'Contract Processing Completed'){
                                    receivedMilestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(receivedMilestoneVal != null){
                                objProjectMilestone.Contract_Received_Milestone__c = receivedMilestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.Survey_Complete_Confirmed__c == null){
                    if(mapRecordTypeNameToJob.get('SiteSurvey') != null){
                        Job__c objSiteSurveyJob = mapRecordTypeNameToJob.get('SiteSurvey');
                        if(mapJobIdToLstFlowStatusHistory.get(objSiteSurveyJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objSiteSurveyJob.Id)){
                                if(objJobHistory.NewValue == 'Survey Complete - Confirmed'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.Survey_Complete_Confirmed__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.Energy_Bill_checked__c == null){
                    if(mapRecordTypeNameToJob.get('Document_Verification') != null){
                        Job__c objDocVerificationJob = mapRecordTypeNameToJob.get('Document_Verification');
                        objProjectMilestone.Energy_Bill_checked__c = objDocVerificationJob.Usage_Verification_Complete__c;
                        updateMilestone = true;
                    }
                }
                
                
                if(objProjectMilestone.Design_Completed_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Design') != null){
                        Job__c objSiteApprovalJob = mapRecordTypeNameToJob.get('Design');
                        if(mapJobIdToLstFlowStatusHistory.get(objSiteApprovalJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objSiteApprovalJob.Id)){
                                if(objJobHistory.NewValue == 'Site Approved'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.Design_Completed_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.Permit_Submitted_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Permitting') != null){
                        Job__c objPermittingJob = mapRecordTypeNameToJob.get('Permitting');
                        if(mapJobIdToLstFlowStatusHistory.get(objPermittingJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objPermittingJob.Id)){
                                if(objJobHistory.NewValue == 'Permit Submitted'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.Permit_Submitted_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.Permit_Received_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Permitting') != null){
                        Job__c objPermittingJob = mapRecordTypeNameToJob.get('Permitting');
                        if(mapJobIdToLstFlowStatusHistory.get(objPermittingJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objPermittingJob.Id)){
                                if(objJobHistory.NewValue == 'Permit Received' || objJobHistory.NewValue == 'Permit Received, Pending Issuance'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.Permit_Received_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                
                if(objProjectMilestone.Installation_Ready_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Installation_Scheduling') != null){
                        Job__c objInstallationSchedulingJob = mapRecordTypeNameToJob.get('Installation_Scheduling');
                        if(mapJobIdToLstFlowStatusHistory.get(objInstallationSchedulingJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objInstallationSchedulingJob.Id)){
                                if(objJobHistory.NewValue == 'New- Pending Scheduling'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.Installation_Ready_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.Installation_Scheduled_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Installation_Scheduling') != null){
                        Job__c objInstallationSchedulingJob = mapRecordTypeNameToJob.get('Installation_Scheduling');
                        if(mapJobIdToLstFlowStatusHistory.get(objInstallationSchedulingJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objInstallationSchedulingJob.Id)){
                                if(objJobHistory.NewValue == 'Installation Scheduled'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.Installation_Scheduled_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.Installation_Completed_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Installation_Scheduling') != null){
                        Job__c objInstallationSchedulingJob = mapRecordTypeNameToJob.get('Installation_Scheduling');
                        if(mapJobIdToLstFlowStatusHistory.get(objInstallationSchedulingJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objInstallationSchedulingJob.Id)){
                                if(objJobHistory.NewValue == 'Installation Complete'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.Installation_Completed_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.Inspection_Scheduled_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Inspection') != null){
                        Job__c objInspectionJob = mapRecordTypeNameToJob.get('Inspection');
                        if(mapJobIdToLstFlowStatusHistory.get(objInspectionJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objInspectionJob.Id)){
                                if(objJobHistory.NewValue == 'Inspection Scheduled'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.Inspection_Scheduled_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.Inspection_Complete_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Inspection') != null){
                        Job__c objInspectionJob = mapRecordTypeNameToJob.get('Inspection');
                        if(mapJobIdToLstFlowStatusHistory.get(objInspectionJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objInspectionJob.Id)){
                                if(objJobHistory.NewValue == 'Inspection Complete'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.Inspection_Complete_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.PTO_Submitted_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('PTO') != null){
                        Job__c objPTOJob = mapRecordTypeNameToJob.get('PTO');
                        if(mapJobIdToLstFlowStatusHistory.get(objPTOJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objPTOJob.Id)){
                                if(objJobHistory.NewValue == 'Submitted'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.PTO_Submitted_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.PTO_Complete_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('PTO') != null){
                        Job__c objPTOJob = mapRecordTypeNameToJob.get('PTO');
                        if(mapJobIdToLstFlowStatusHistory.get(objPTOJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objPTOJob.Id)){
                                if(objJobHistory.NewValue == 'PTO Granted'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(milestoneVal != null){
                                objProjectMilestone.PTO_Complete_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
                
                if(objProjectMilestone.Installation_Started_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Installation_Scheduling') != null){
                        Job__c objInstallationSchedulingJob = mapRecordTypeNameToJob.get('Installation_Scheduling');
                        if(objInstallationSchedulingJob != null && objInstallationSchedulingJob.Installation_Start_Date__c != null){
                            //objProjectMilestone.Installation_Started_Milestone__c = mapJobIdToInstallationHistory.get(objInstallationSchedulingJob.Id).CreatedDate;
                            objProjectMilestone.Installation_Started_Milestone__c = objInstallationSchedulingJob.Installation_Start_Date__c;
                            updateMilestone = true;     
                        }
                    }
                }
                
                List<Job__c> lstJobToUpdate = new List<Job__c>();
                if(mapRecordTypeNameToJob.get('Installation_Scheduling') != null){
                    Job__c objInstallationSchedulingJob = mapRecordTypeNameToJob.get('Installation_Scheduling');
                    objInstallationSchedulingJob.Installation_Start_Date_Observed__c = objInstallationSchedulingJob.Installation_Start_Date__c;
                    update objInstallationSchedulingJob;
                }
               
                if(updateMilestone){
                    update objProjectMilestone;
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext context) {
        
    }
}