unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Financing.recordType-meta.xml
<RecordType>
    <fullName>Financing</fullName>
    <active>true</active>
    <label>Financing</label>
</RecordType>

unpackaged/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Milestone__c/fields/Contract_Received_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Milestone__c</fullName>
    <label>Contract Received - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Contract_Signed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Contract_Signed_Milestone__c</fullName>
    <label>Contract Signed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Energy_Bill_checked__c.field-meta.xml
<CustomField>
    <fullName>Energy_Bill_checked__c</fullName>
    <label>Usage Verification Complete</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Survey_Complete_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Survey_Complete_Confirmed__c</fullName>
    <label>Survey Complete Confirmed</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateProjectMilestoneV2Test.cls
@isTest(seeAllData=true)
private class BatchToUpdateProjectMilestoneV2Test
{   
    static testMethod void unitTest3(){
        Job__c objJob = [SELECT Id, Opportunity__c FROM Job__c WHERE RecordType.DeveloperName = 'Financing' 
            AND Opportunity__c != null AND Flow_Status__c = 'M1 - Approved' LIMIT 1];
        delete [SELECT Id FROM Project_Milestone__c WHERE Opportunity__c = :objJob.Opportunity__c];
        
        Project_Milestone__c objMilestone = new Project_Milestone__c();
        objMilestone.Name = 'test';
        objMilestone.Opportunity__c = objJob.Opportunity__c;
        objMilestone.Contract_Signed_Milestone__c = Datetime.now();
        objMilestone.Survey_Complete_Confirmed__c = Datetime.now();
        objMilestone.Energy_Bill_checked__c = Datetime.now();
        objMilestone.Contract_Received_Milestone__c = Datetime.now();
        insert objMilestone;
        
        Database.executeBatch(new BatchToUpdateProjectMilestoneV2(objJob.Opportunity__c), 1);
    }
}