unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
            <value>
                <fullName>Materials Delivery Exception</fullName>
            </value>
            <value>
                <fullName>Materials Delivery Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Start_Date_Observed__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date_Observed__c</fullName>
    <inlineHelpText>First "Installation Start Date" to have elapsed without being rescheduled, called off, or cancelled within 1 calendar day.</inlineHelpText>
    <label>Installation Start Date - Observed</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Installation_Scheduling.recordType-meta.xml
<RecordType>
    <fullName>Installation_Scheduling</fullName>
    <active>true</active>
    <label>Installation Scheduling</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Supply_Chain.recordType-meta.xml
<RecordType>
    <fullName>Supply_Chain</fullName>
    <active>true</active>
    <label>Supply Chain</label>
</RecordType>

unpackaged/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Milestone__c/fields/Installation_Started_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Installation_Started_Milestone__c</fullName>
    <label>Installation Started - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateInstallationObserved.cls
global class BatchToUpdateInstallationObserved implements Database.Batchable<SObject>, Schedulable
{
    global void execute(SchedulableContext sc){
        BatchToUpdateInstallationObserved objBatchToUpdateInstallationObserved = new BatchToUpdateInstallationObserved();
        Database.executeBatch(objBatchToUpdateInstallationObserved, 1);
    }
    
    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        Datetime compareDate = Datetime.now().addDays(-5);
        
        String query = 'SELECT Id, Opportunity__c, Installation_Start_Date__c, Installation_Start_Date_Observed__c FROM Job__c ';
        query += 'WHERE Opportunity__c != null AND Installation_Start_Date__c != null ';
        query += 'AND RecordType.DeveloperName = \'Installation_Scheduling\' ';
        //query += 'AND Installation_Start_Date__c > :compareDate';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Job__c> lstJob) {
        Job__c objJob = lstJob[0];
        Boolean firstCriteria = false, secondcriteria = false;
        if(objJob.Installation_Start_Date_Observed__c == null){
            firstCriteria = true;
        }
        
        
        Boolean updateJob = false;
        if(objJob.Installation_Start_Date_Observed__c != null){
            if(objJob.Installation_Start_Date__c != Date.today().addDays(-1) && objJob.Installation_Start_Date__c > Date.today()){
                objJob.Installation_Start_Date_Observed__c = null;
                updateJob = true;
            }
        }
        
        if(objJob.Installation_Start_Date__c == Date.today() && objJob.Installation_Start_Date_Observed__c == null){
            objJob.Installation_Start_Date_Observed__c = Date.today();
            updateJob = true;
            
            if(firstCriteria){
                secondcriteria = true;
            }
        }
        
        List<Project_Milestone__c> lstProjectMilestone = [
                        SELECT Id, Installation_Started_Milestone__c 
                        FROM Project_Milestone__c
                        WHERE Opportunity__c = :objJob.Opportunity__c
                        LIMIT 1];
                        
        if(lstProjectMilestone != null && !lstProjectMilestone.isEmpty()){
            Project_Milestone__c objProjectMilestone = lstProjectMilestone[0];
            //if(objJob.Installation_Start_Date_Observed__c != null){
                objProjectMilestone.Installation_Started_Milestone__c = objJob.Installation_Start_Date_Observed__c;
                update objProjectMilestone;
            //}
        }
        
        if(secondcriteria){
            List<Job__c> lstSupplyChainJob = [
                        SELECT Id, Flow_Status__c 
                        FROM Job__c
                        WHERE RecordType.DeveloperName = 'Supply_Chain'
                        AND Opportunity__c = :objJob.Opportunity__c
                        AND Flow_Status__c != 'Materials Delivery Confirmed'
                        AND Flow_Status__c != 'Materials Delivery Exception'
                        AND Flow_Status__c != 'Fulfilled'];
                        
            if(lstSupplyChainJob != null && !lstSupplyChainJob.isEmpty()){
                lstSupplyChainJob[0].Flow_Status__c = 'Materials Delivery Confirmed';
                update lstSupplyChainJob[0];
            }
        }
        
        if(updateJob){
            update objJob;
        }
    }
    
    global void finish(Database.BatchableContext context) {
        
    }
}