unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Financing.recordType-meta.xml
<RecordType>
    <fullName>Financing</fullName>
    <active>true</active>
    <label>Financing</label>
</RecordType>

unpackaged/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Milestone__c/fields/Contract_Received_Confirmed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed_Milestone__c</fullName>
    <label>Contract Received/Confirmed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Contract_Received_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Milestone__c</fullName>
    <label>Contract Received - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Energy_Bill_checked__c.field-meta.xml
<CustomField>
    <fullName>Energy_Bill_checked__c</fullName>
    <label>Usage Verification Complete</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Energy_Usage_Verification_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Energy_Usage_Verification_Milestone__c</fullName>
    <label>Energy Usage Verification - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Lease_Loan_M1_Approval_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Lease_Loan_M1_Approval_Milestone__c</fullName>
    <label>Lease/Loan M1 Approval - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Site_Survey_Completed_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Site_Survey_Completed_Milestone__c</fullName>
    <label>Site Survey Completed - Milestone</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Survey_Complete_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Survey_Complete_Confirmed__c</fullName>
    <label>Survey Complete Confirmed</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateProjectMilestoneV2.cls
global class BatchToUpdateProjectMilestoneV2 implements Database.Batchable<SObject>
{   
    String oppId;
    global BatchToUpdateProjectMilestoneV2(String oppId){
        this.oppId = oppId;
    }

    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        String query = System.Label.Project_Milestone_Query_3;
        if(String.isNotBlank(oppId)){
            query += ' AND Opportunity__c =: oppId';
        }
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Project_Milestone__c> lstProjectMilestone) {
        Project_Milestone__c objProjectMilestone = lstProjectMilestone[0];
        if(objProjectMilestone.Opportunity__c != null){
            Boolean updateMilestone = false;
            if(objProjectMilestone.Site_Survey_Completed_Milestone__c == null 
                && objProjectMilestone.Survey_Complete_Confirmed__c != null)
            {
                objProjectMilestone.Site_Survey_Completed_Milestone__c = objProjectMilestone.Survey_Complete_Confirmed__c;
                updateMilestone = true;
            }
            
            if(objProjectMilestone.Energy_Usage_Verification_Milestone__c == null 
                && objProjectMilestone.Energy_Bill_checked__c != null)
            {
                objProjectMilestone.Energy_Usage_Verification_Milestone__c = objProjectMilestone.Energy_Bill_checked__c;
                updateMilestone = true;
            }
            
            if(objProjectMilestone.Contract_Received_Confirmed_Milestone__c == null 
                && objProjectMilestone.Contract_Received_Milestone__c != null)
            {
                objProjectMilestone.Contract_Received_Confirmed_Milestone__c = objProjectMilestone.Contract_Received_Milestone__c;
                updateMilestone = true;
            }
            
            Set<Id> setJobId = new Set<Id>();
            Map<String, Job__c> mapRecordTypeNameToJob = new Map<String, Job__c>();
            for(Job__c objJob : [
                    SELECT Id, RecordType.DeveloperName
                    FROM Job__c 
                    WHERE Opportunity__c = :objProjectMilestone.Opportunity__c
                    AND RecordType.DeveloperName = 'Financing'])
            {
                setJobId.add(objJob.Id);
                mapRecordTypeNameToJob.put(objJob.RecordType.DeveloperName, objJob);
            }
            
            if(!setJobId.isEmpty()){
                Map<Id, List<Job__History>> mapJobIdToLstFlowStatusHistory = new Map<Id, List<Job__History>>();
                Set<String> setUniqueCombo = new Set<String>();
                for(Job__History objJobHistory : [
                        SELECT Id, ParentId, CreatedDate, Field, OldValue, NewValue 
                        FROM Job__History 
                        WHERE Field = 'Flow_Status__c'
                        AND ParentId IN :setJobId
                        ORDER By Createddate])
                {
                    String uniqueCombo = objJobHistory.ParentId + '::' + objJobHistory.NewValue;
                    
                    if(!setUniqueCombo.contains(uniqueCombo)){
                        if(mapJobIdToLstFlowStatusHistory.containsKey(objJobHistory.ParentId)){
                            mapJobIdToLstFlowStatusHistory.get(objJobHistory.ParentId).add(objJobHistory);
                        } else{
                            mapJobIdToLstFlowStatusHistory.put(objJobHistory.ParentId, new List<Job__History>{objJobHistory});        
                        }
                        
                        setUniqueCombo.add(uniqueCombo);
                    }
                }
                
                if(objProjectMilestone.Lease_Loan_M1_Approval_Milestone__c == null){
                    if(mapRecordTypeNameToJob.get('Financing') != null){
                        Job__c objFinancingJob = mapRecordTypeNameToJob.get('Financing');
                        if(mapJobIdToLstFlowStatusHistory.get(objFinancingJob.Id) != null){
                            Datetime milestoneVal;
                            for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(objFinancingJob.Id)){
                                if(objJobHistory.NewValue == 'M1 - Approved'){
                                    milestoneVal = objJobHistory.CreatedDate;
                                    break;
                                }
                            }   
                            
                            if(objFinancingJob != null){
                                objProjectMilestone.Lease_Loan_M1_Approval_Milestone__c = milestoneVal;
                                updateMilestone = true;
                            }                     
                        }
                    }
                }
            }
            
            if(updateMilestone){
                update objProjectMilestone;
            }
        }
    }
    
    global void finish(Database.BatchableContext context) {
        
    }
}