unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>IF(ISBLANK(Opportunity__c), ( Build_Only__r.Street__c  +  BR() +  Build_Only__r.City__c  + ', ' +  TEXT(Build_Only__r.State__c)  +  ' ' +  Build_Only__r.Zip_Code__c ) , (Opportunity__r.Account.BillingStreet +  BR() + Opportunity__r.Account.BillingCity + ', ' + Opportunity__r.Account.BillingState + ', ' + ' ' + Opportunity__r.Account.BillingPostalCode))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <formula>Opportunity__r.Installation_Complete_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Installation_Scheduling.recordType-meta.xml
<RecordType>
    <fullName>Installation_Scheduling</fullName>
    <active>true</active>
    <label>Installation Scheduling</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Account.BillingStreet+BR()  +   Account.BillingCity+BR()  +   Account.BillingState+BR()  +  Account.BillingPostalCode+BR()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Used for Salesforce Marketing Cloud. Do not Delete</description>
    <formula>Contact__r.FirstName + " " +  Contact__r.LastName</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Guaranteed_Substantial_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Guaranteed_Substantial_Completion_Date__c</fullName>
    <label>Guaranteed Substantial Completion Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Project_Address__c.field-meta.xml
<CustomField>
    <fullName>Project_Address__c</fullName>
    <label>Project Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Project_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Date__c</fullName>
    <label>Project Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Project_Price__c.field-meta.xml
<CustomField>
    <fullName>Project_Price__c</fullName>
    <label>Project Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/OrderHandler.cls
public class OrderHandler
{
    //This method is called on before insert event of trigger.
    public void onBeforeInsert(List<Order> lstOrder){
        populateFields(lstOrder);
    }
    
    //This method is used to populate the fields.
    private void populateFields(List<Order> lstOrder){
        Map<Id, Opportunity> mapIdToOpp = new Map<Id, Opportunity>();
        for(Order objOrder : lstOrder){
            if(objOrder.OpportunityId != null){
                mapIdToOpp.put(objOrder.OpportunityId, null);
            }
        }
        
        if(!mapIdToOpp.isEmpty()){
            
            for(Opportunity objOpp : [
                    SELECT Id, Amount, Customer_Name__c, Address__c,
                        (SELECT Id, Installation_Start_Date__c, Installation_Complete_Date__c 
                        FROM Jobs__r
                        WHERE RecordType.DeveloperName = 'Installation_Scheduling')
                    FROM Opportunity
                    WHERE Id IN :mapIdToOpp.keyset()])
            {
                mapIdToOpp.put(objOpp.Id, objOpp);
            }
            
            
            for(Order objOrder : lstOrder){
                if(objOrder.OpportunityId != null && mapIdToOpp.get(objOrder.OpportunityId) != null){
                    Opportunity objOpp = mapIdToOpp.get(objOrder.OpportunityId);
                    objOrder.Project_Price__c = objOpp.Amount;
                    objOrder.Customer_Name__c = objOpp.Customer_Name__c;
                    if(String.isNotBlank(objOpp.Address__c)){
                        String address = objOpp.Address__c.replaceAll('<br>', '\n');
                        objOrder.Project_Address__c = address;
                    }
                    
                    if(objOpp.Jobs__r != null && !objOpp.Jobs__r.isEmpty()){
                        Job__c objJob = objOpp.Jobs__r[0];
                        
                        objOrder.Project_Date__c = objJob.Installation_Start_Date__c;
                        objOrder.Guaranteed_Substantial_Completion_Date__c = objJob.Installation_Complete_Date__c;
                    }
                }
            }
        }
    }
}