unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Flow_Status__c.field-meta.xml
<CustomField>
    <fullName>Flow_Status__c</fullName>
    <label>Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Pending Customer Self Activation</fullName>
            </value>
            <value>
                <fullName>Change Order Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submission Not Required (Non Carolina Markets)</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Preparing</fullName>
            </value>
            <value>
                <fullName>Sent for Signature</fullName>
            </value>
            <value>
                <fullName>Submitted/Sent to HO</fullName>
            </value>
            <value>
                <fullName>Change Order Complete</fullName>
            </value>
            <value>
                <fullName>Design Outsourced</fullName>
            </value>
            <value>
                <fullName>Professional Engineering Stamp</fullName>
            </value>
            <value>
                <fullName>Final Review</fullName>
            </value>
            <value>
                <fullName>Site Approved</fullName>
            </value>
            <value>
                <fullName>Installation Complete- Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Customer</fullName>
            </value>
            <value>
                <fullName>Scheduling Pending As-Builts/Redesign</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Inspector</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Affidavit</fullName>
            </value>
            <value>
                <fullName>Inspection Pending Utility</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduling Blocked</fullName>
            </value>
            <value>
                <fullName>Inspection Scheduled</fullName>
            </value>
            <value>
                <fullName>Inspection Failed</fullName>
            </value>
            <value>
                <fullName>Pending Remediation/Corrections</fullName>
            </value>
            <value>
                <fullName>Inspection Complete</fullName>
            </value>
            <value>
                <fullName>Inspection Complete- Pending Inspection Documentation</fullName>
            </value>
            <value>
                <fullName>Inspection Complete-Pending WO Close Out</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Sent to Customer</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Received- Pending Review</fullName>
            </value>
            <value>
                <fullName>Additional Photos Needed</fullName>
            </value>
            <value>
                <fullName>Physical Survey Required - Palmetto Requested</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Interconnection Approved</fullName>
            </value>
            <value>
                <fullName>Net Metering Approved</fullName>
            </value>
            <value>
                <fullName>Utility Approval for Install</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Interconnection.recordType-meta.xml
<RecordType>
    <fullName>Interconnection</fullName>
    <active>true</active>
    <label>Interconnection</label>
</RecordType>

unpackaged/main/default/objects/Project_Milestone__c/Project_Milestone__c.object-meta.xml
<CustomObject>
    <label>Project Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Milestone__c/fields/Interconnection_Application_Approved__c.field-meta.xml
<CustomField>
    <fullName>Interconnection_Application_Approved__c</fullName>
    <label>Interconnection Application Approved</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Interconnection_Application_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Interconnection_Application_Submitted__c</fullName>
    <inlineHelpText>Original Interconnection Application Submitted</inlineHelpText>
    <label>Original Intcon Application Submitted</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Interconnection_Process_Initiated__c.field-meta.xml
<CustomField>
    <fullName>Interconnection_Process_Initiated__c</fullName>
    <inlineHelpText>Original Interconnnection Process Initiated</inlineHelpText>
    <label>Original Intcon Process Initiated</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Net_Metering_Application_Approved__c.field-meta.xml
<CustomField>
    <fullName>Net_Metering_Application_Approved__c</fullName>
    <label>Net Metering Application Approved</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Milestones</relationshipLabel>
    <relationshipName>Project_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Project_Milestone__c/fields/Utility_Approval_for_Installation__c.field-meta.xml
<CustomField>
    <fullName>Utility_Approval_for_Installation__c</fullName>
    <inlineHelpText>Original Utility Approval for Installation</inlineHelpText>
    <label>Original Utility Approval for Install</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateProjectMilestoneV4.cls
global class BatchToUpdateProjectMilestoneV4 implements Database.Batchable<SObject>
{   
    String oppId;
    global BatchToUpdateProjectMilestoneV4(String oppId){
        this.oppId = oppId;
    }

    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        String query = System.Label.Project_Milestone_V5;
        if(String.isNotBlank(oppId)){
            query += ' AND Opportunity__c =: oppId';
        }
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Project_Milestone__c> lstProjectMilestone) {
        Project_Milestone__c objProjectMilestone = lstProjectMilestone[0];
        if(objProjectMilestone.Opportunity__c != null){
            Boolean updateMilestone = false;
            List<Job__c> lstJob = new List<Job__c>();
            Map<String, Job__c> mapRecordTypeNameToJob = new Map<String, Job__c>();
            for(Job__c objJob : [
                    SELECT Id, Flow_Status__c, CreatedDate
                    FROM Job__c 
                    WHERE Opportunity__c = :objProjectMilestone.Opportunity__c
                    AND RecordType.DeveloperName = 'Interconnection'])
            {
                lstJob.add(objJob);
                objProjectMilestone.Interconnection_Process_Initiated__c = objJob.CreatedDate;
                updateMilestone = true;
            }
            
            if(!lstJob.isEmpty()){
                Id jobId = lstJob[0].Id;
                Map<Id, List<Job__History>> mapJobIdToLstFlowStatusHistory = new Map<Id, List<Job__History>>();
                Set<String> setUniqueCombo = new Set<String>();
                for(Job__History objJobHistory : [
                        SELECT Id, ParentId, CreatedDate, Field, OldValue, NewValue 
                        FROM Job__History 
                        WHERE Field = 'Flow_Status__c'
                        AND ParentId = :jobId
                        ORDER By Createddate])
                {
                    String uniqueCombo = objJobHistory.ParentId + '::' + objJobHistory.NewValue;
                    
                    if(!setUniqueCombo.contains(uniqueCombo)){
                        if(mapJobIdToLstFlowStatusHistory.containsKey(objJobHistory.ParentId)){
                            mapJobIdToLstFlowStatusHistory.get(objJobHistory.ParentId).add(objJobHistory);
                        } else{
                            mapJobIdToLstFlowStatusHistory.put(objJobHistory.ParentId, new List<Job__History>{objJobHistory});        
                        }
                        
                        setUniqueCombo.add(uniqueCombo);
                    }
                }
                                
                if(objProjectMilestone.Interconnection_Application_Submitted__c == null){
                    if(mapJobIdToLstFlowStatusHistory.get(jobId) != null){
                        Datetime milestoneVal;
                        for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(jobId)){
                            if(objJobHistory.NewValue == 'Submitted'){
                                milestoneVal = objJobHistory.CreatedDate;
                                break;
                            }
                        }   
                        
                        if(milestoneVal != null){
                            objProjectMilestone.Interconnection_Application_Submitted__c = milestoneVal;
                            updateMilestone = true;
                        }                     
                    }
                }
                
                if(objProjectMilestone.Interconnection_Application_Approved__c == null){
                    if(mapJobIdToLstFlowStatusHistory.get(jobId) != null){
                        Datetime milestoneVal;
                        for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(jobId)){
                            if(objJobHistory.NewValue == 'Interconnection Approved'){
                                milestoneVal = objJobHistory.CreatedDate;
                                break;
                            }
                        }   
                        
                        if(milestoneVal != null){
                            objProjectMilestone.Interconnection_Application_Approved__c = milestoneVal;
                            updateMilestone = true;
                        }                     
                    }
                }
                
                if(objProjectMilestone.Net_Metering_Application_Approved__c == null){
                    if(mapJobIdToLstFlowStatusHistory.get(jobId) != null){
                        Datetime milestoneVal;
                        for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(jobId)){
                            if(objJobHistory.NewValue == 'Net Metering Approved'){
                                milestoneVal = objJobHistory.CreatedDate;
                                break;
                            }
                        }   
                        
                        if(milestoneVal != null){
                            objProjectMilestone.Net_Metering_Application_Approved__c = milestoneVal;
                            updateMilestone = true;
                        }                     
                    }
                }
                
                if(objProjectMilestone.Utility_Approval_for_Installation__c == null){
                    if(mapJobIdToLstFlowStatusHistory.get(jobId) != null){
                        Datetime milestoneVal;
                        for(Job__History objJobHistory : mapJobIdToLstFlowStatusHistory.get(jobId)){
                            if(objJobHistory.NewValue == 'Utility Approval for Install'){
                                milestoneVal = objJobHistory.CreatedDate;
                                break;
                            }
                        }   
                        
                        if(milestoneVal != null){
                            objProjectMilestone.Utility_Approval_for_Installation__c = milestoneVal;
                            updateMilestone = true;
                        }                     
                    }
                }
                
               
                if(updateMilestone){
                    update objProjectMilestone;
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext context) {
        
    }
}