unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <formula>Opportunity__r.Installation_Complete_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Job__c/recordTypes/Inspection.recordType-meta.xml
<RecordType>
    <fullName>Inspection</fullName>
    <active>true</active>
    <label>Inspection</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/Installation_Scheduling.recordType-meta.xml
<RecordType>
    <fullName>Installation_Scheduling</fullName>
    <active>true</active>
    <label>Installation Scheduling</label>
</RecordType>

unpackaged/main/default/objects/Job__c/recordTypes/PTO.recordType-meta.xml
<RecordType>
    <fullName>PTO</fullName>
    <active>true</active>
    <label>PTO</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateOppFromStageHistory.cls
global with sharing class BatchToUpdateOppFromStageHistory implements Database.Batchable<SObject>{

    global Database.QueryLocator start(Database.BatchableContext context) {
        Set<String> oppStages = new Set<String>();
        oppStages.add('20. Inspection Scheduled');
        oppStages.add('21. Inspection Complete');
        oppStages.add('22. PTO');
        oppStages.add('Closed Won');
        oppStages.add('Cancelled');
        oppStages.add('Closed Lost');

        Id intallationJob = Schema.SObjectType.Job__c
        .getRecordTypeInfosByDeveloperName()
        .get('Installation_Scheduling')
        .getRecordTypeId();

        String query = 'SELECT Id,Installation_Complete_Date__c, ' +
        '(SELECT Id, CreatedDate, newValue ' +
        'FROM Histories ' +
        'WHERE Field = \'StageName\') ' +
        'FROM Opportunity ' +
        'WHERE StageName IN :oppStages ' +
        'AND Installation_Complete_Date__c = null';

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext context, List<Opportunity> scope) {
        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        for(Opportunity opp : scope){
            if(!opp.Histories.isEmpty()){
                for(OpportunityFieldHistory ofh : opp.Histories){
                    if(ofh.newValue == '19. Install Completed'){
                        opp.Installation_Complete_Date__c = ofh.CreatedDate.date();
                        oppsToUpdate.add(opp);
                    }
                }
            }
        }

        if(!oppsToUpdate.isEmpty()){
            update oppsToUpdate;
        }
    }

    global void finish(Database.BatchableContext context) {
        
    }
}