unpackaged/main/default/objects/Dealer_Fee_Product__c/Dealer_Fee_Product__c.object-meta.xml
<CustomObject>
    <label>Dealer Fee Product</label>
    <nameField>
        <label>Dealer Fee Product	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Fee Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Dealer_Fee_Product__c/fields/APR__c.field-meta.xml
<CustomField>
    <fullName>APR__c</fullName>
    <label>APR %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.99%</fullName>
            </value>
            <value>
                <fullName>1.49%</fullName>
            </value>
            <value>
                <fullName>1.99%</fullName>
            </value>
            <value>
                <fullName>2.99%</fullName>
            </value>
            <value>
                <fullName>3.49%</fullName>
            </value>
            <value>
                <fullName>3.99%</fullName>
            </value>
            <value>
                <fullName>4.99%</fullName>
            </value>
            <value>
                <fullName>5.49%</fullName>
            </value>
            <value>
                <fullName>5.99%</fullName>
            </value>
            <value>
                <fullName>7.99%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Dealer_Fee_Product__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Fee Products</relationshipLabel>
    <relationshipName>Dealer_Fee_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dealer_Fee_Product__c/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Dealer_Fee_Product__c/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Dealer_Fee_Product__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/APR__c.field-meta.xml
<CustomField>
    <fullName>APR__c</fullName>
    <label>APR %</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.99%</fullName>
            </value>
            <value>
                <fullName>1.49%</fullName>
            </value>
            <value>
                <fullName>1.99%</fullName>
            </value>
            <value>
                <fullName>2.99%</fullName>
            </value>
            <value>
                <fullName>3.49%</fullName>
            </value>
            <value>
                <fullName>3.99%</fullName>
            </value>
            <value>
                <fullName>4.99%</fullName>
            </value>
            <value>
                <fullName>5.49%</fullName>
            </value>
            <value>
                <fullName>5.99%</fullName>
            </value>
            <value>
                <fullName>7.99%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Channel Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Date__c</fullName>
    <label>Contract Received Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Internal_Dealer_Fee_Product2__c.field-meta.xml
<CustomField>
    <fullName>Internal_Dealer_Fee_Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Internal Dealer Fee Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Dealer_Fee_Product__c.Classification__c</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer_Fee_Product__c</referenceTo>
    <relationshipLabel>Opportunities (Internal Dealer Fee Product)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateDealerProduct.cls
global class BatchToUpdateDealerProduct implements Database.Batchable<SObject>
{   
    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        String query = System.Label.Opp_Commission_Query;
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Opportunity> lstOpp) 
    {    
        Set<String> setUniqueCombo = new Set<String>();
        Set<String> setCashUniqueCombo = new Set<String>();
        List<Opportunity> lstOppToProcess = new List<Opportunity>();
        List<Opportunity> lstCashOppToProcess = new List<Opportunity>();
        for(Opportunity objOpp : lstOpp){
            String uniqueCombo = objOpp.Financing_Tool__c + ':' + objOpp.APR__c + ':' +  objOpp.Loan_Term__c;
            if(String.isNotBlank(objOpp.Financing_Tool__c) && String.isNotBlank(objOpp.Location__c))
            {
                if(objOpp.Financing_Tool__c == 'Cash' || objOpp.Financing_Tool__c == 'SunRun' 
                            || objOpp.Financing_Tool__c == 'Sunnova Lease')
                {
                    lstCashOppToProcess.add(objOpp);
                    setCashUniqueCombo.add(objOpp.Financing_Tool__c);
                } else if(String.isNotBlank(objOpp.APR__c) && String.isNotBlank(objOpp.Loan_Term__c)){
                    lstOppToProcess.add(objOpp);
                    setUniqueCombo.add(uniqueCombo);
                }
            }
        }
        
        if(!lstOppToProcess.isEmpty()){
            List<Opportunity> lstOppToUpdate = new List<Opportunity>();
            Map<String, List<Dealer_Fee_Product__c>> mapUniqueComboToLstProduct = new Map<String, List<Dealer_Fee_Product__c>>();
            for(Dealer_Fee_Product__c objProduct : [SELECT Id, Unique_Combo__c, State__c, Classification__c, Start_Date__c, End_Date__c, Channel_Partner__c
                    FROM Dealer_Fee_Product__c
                    WHERE Unique_Combo__c IN :setUniqueCombo
                    ORDER BY Start_Date__c])
            {
                String uniqueCombo = objProduct.Unique_Combo__c;
                if(objProduct.Channel_Partner__c != null){
                    uniqueCombo += ':' + objProduct.Channel_Partner__c;
                }
                
                if(mapUniqueComboToLstProduct.containsKey(uniqueCombo)){
                    mapUniqueComboToLstProduct.get(uniqueCombo).add(objProduct);
                } else{
                    mapUniqueComboToLstProduct.put(uniqueCombo, new List<Dealer_Fee_Product__c>{objProduct});
                }
            }
            
            System.debug('>>>>>>>'+mapUniqueComboToLstProduct);
            for(Opportunity objOpp : lstOppToProcess){
                String uniqueCombo1 = objOpp.Financing_Tool__c + ':' + objOpp.APR__c + ':' +  objOpp.Loan_Term__c;
                String uniqueCombo2 = uniqueCombo1 + ':' + objOpp.Channel_Partner__c;
                Id internalDealerId;
                //Code to populate internal dealer.
                if(mapUniqueComboToLstProduct.containsKey(uniqueCombo2))
                    internalDealerId = populateDealerId(objOpp, mapUniqueComboToLstProduct.get(uniqueCombo2), 'Internal');
                if(internalDealerId == null && mapUniqueComboToLstProduct.containsKey(uniqueCombo1))
                    internalDealerId = populateDealerId(objOpp, mapUniqueComboToLstProduct.get(uniqueCombo1), 'Internal');
                
                if(internalDealerId != null){
                    objOpp.Internal_Dealer_Fee_Product2__c = internalDealerId;
                    lstOppToUpdate.add(objOpp);
                }
            }

            if(!lstOppToUpdate.isEmpty())
                update lstOppToUpdate;
        }
        
        //Code for Cash/Sunrun and Sunnova Lease Opps.
        if(!lstCashOppToProcess.isEmpty()){
            List<Opportunity> lstOppToUpdate = new List<Opportunity>();
            Map<String, List<Dealer_Fee_Product__c>> mapUniqueComboToLstProduct = new Map<String, List<Dealer_Fee_Product__c>>();
            for(Dealer_Fee_Product__c objProduct : [
                    SELECT Id, State__c, Classification__c, Start_Date__c, End_Date__c, Channel_Partner__c, Financing_Tool__c
                    FROM Dealer_Fee_Product__c
                    WHERE Financing_Tool__c IN :setCashUniqueCombo
                    ORDER BY Start_Date__c])
            {
                String uniqueCombo = objProduct.Financing_Tool__c;
                if(objProduct.Channel_Partner__c != null){
                    uniqueCombo += ':' + objProduct.Channel_Partner__c;
                }
                
                if(mapUniqueComboToLstProduct.containsKey(uniqueCombo)){
                    mapUniqueComboToLstProduct.get(uniqueCombo).add(objProduct);
                } else{
                    mapUniqueComboToLstProduct.put(uniqueCombo, new List<Dealer_Fee_Product__c>{objProduct});
                }
            }
            
            System.debug('>>>>>>>'+mapUniqueComboToLstProduct);
            for(Opportunity objOpp : lstCashOppToProcess){
                String uniqueCombo1 = objOpp.Financing_Tool__c;
                String uniqueCombo2 = uniqueCombo1 + ':' + objOpp.Channel_Partner__c;
                Id internalDealerId;
                //Code to populate internal dealer.
                if(mapUniqueComboToLstProduct.containsKey(uniqueCombo2))
                    internalDealerId = populateDealerId(objOpp, mapUniqueComboToLstProduct.get(uniqueCombo2), 'Internal');
                if(internalDealerId == null && mapUniqueComboToLstProduct.containsKey(uniqueCombo1))
                    internalDealerId = populateDealerId(objOpp, mapUniqueComboToLstProduct.get(uniqueCombo1), 'Internal');
                
                if(internalDealerId != null){
                    objOpp.Internal_Dealer_Fee_Product2__c = internalDealerId;
                    lstOppToUpdate.add(objOpp);
                }
            }

            if(!lstOppToUpdate.isEmpty())
                update lstOppToUpdate;
        }
    }

    //This method is used to find out the dealer fee commission record.
    private Id populateDealerId(Opportunity objOpp, List<Dealer_Fee_Product__c> lstProduct, String classification){
        Id dealerId;
        for(Dealer_Fee_Product__c objProduct : lstProduct){
            if(String.isNotBlank(objProduct.State__c) && objProduct.State__c.containsIgnoreCase(objOpp.Location__c)){
                if(((objProduct.Start_Date__c == null || objProduct.Start_Date__c <= objOpp.Contract_Received_Date__c) && (objProduct.End_Date__c == null || objProduct.End_Date__c >= objOpp.Contract_Received_Date__c)) || (objProduct.Start_Date__c != null && objProduct.End_Date__c != null && objOpp.Contract_Received_Date__c >= objProduct.Start_Date__c && objOpp.Contract_Received_Date__c <= objProduct.End_Date__c)){
                    if(objProduct.Classification__c == classification){
                        dealerId = objProduct.Id;  
                    } 
                }
            }
        }  
        
        return dealerId;      
    }
    
    global void finish(Database.BatchableContext context) {
        
    }
}