unpackaged/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Commision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/X3rd_Party_Partner__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Partner__c</fullName>
    <formula>Text(Opportunity__r.X3rd_Party_Partner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>3rd Party Partner</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opp_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Opp_Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Do NOT designate CUSTOMER contact.</inlineHelpText>
    <label>Opp Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Opp Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X3rd_Party_Partner__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Partner__c</fullName>
    <label>3rd Party Partner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100 better built</fullName>
            </value>
            <value>
                <fullName>10x Solutions LLC</fullName>
            </value>
            <value>
                <fullName>1nnov8tive LLC</fullName>
            </value>
            <value>
                <fullName>1UP Solar</fullName>
            </value>
            <value>
                <fullName>1UP Solar LLC</fullName>
            </value>
            <value>
                <fullName>25th Hour Solutions LLC</fullName>
            </value>
            <value>
                <fullName>320 Solar LLC</fullName>
            </value>
            <value>
                <fullName>361 Technologies LLC</fullName>
            </value>
            <value>
                <fullName>365 Solar Energy</fullName>
            </value>
            <value>
                <fullName>3rd Rock Solar Discounters</fullName>
            </value>
            <value>
                <fullName>413Solar</fullName>
            </value>
            <value>
                <fullName>413Solar LLC</fullName>
            </value>
            <value>
                <fullName>4Season Real Estate Solutions LLC</fullName>
            </value>
            <value>
                <fullName>528 Lumen</fullName>
            </value>
            <value>
                <fullName>A3nergy Solutions</fullName>
            </value>
            <value>
                <fullName>ABC PRO GRP, LLC</fullName>
            </value>
            <value>
                <fullName>Absolute Sustainability LLC</fullName>
            </value>
            <value>
                <fullName>Active Care Connections</fullName>
            </value>
            <value>
                <fullName>Adorno Consulting LLC</fullName>
            </value>
            <value>
                <fullName>Advanced Exteriors, LLC</fullName>
            </value>
            <value>
                <fullName>Advanced Exteriors LLC</fullName>
            </value>
            <value>
                <fullName>Advisors Solar Group Inc.</fullName>
            </value>
            <value>
                <fullName>AE Contracting Services LLC</fullName>
            </value>
            <value>
                <fullName>AE Solar</fullName>
            </value>
            <value>
                <fullName>Ageint Security</fullName>
            </value>
            <value>
                <fullName>Alamo Smart Home</fullName>
            </value>
            <value>
                <fullName>Aligned Energy Partners</fullName>
            </value>
            <value>
                <fullName>Alliance Service Professionals LLC</fullName>
            </value>
            <value>
                <fullName>All in One Exterior and Construction</fullName>
            </value>
            <value>
                <fullName>Aloha Sun Power</fullName>
            </value>
            <value>
                <fullName>LGCY Power</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TriggerConfiguration__c/TriggerConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Configuration</label>
</CustomObject>

unpackaged/main/default/classes/CommissionTriggerHandler.cls
public class CommissionTriggerHandler
{
    //This method is called on after update event of trigger.
    public void onAfterUpdate(List<Commission__c> lstCommission, Map<Id, Commission__c> mapIdToOldCommission){
        TriggerConfiguration__c objTriggerConfigurationCS = TriggerConfiguration__c.getInstance('LGCY API trigger');
        if(objTriggerConfigurationCS != null && objTriggerConfigurationCS.Active__c == true){
            sendCommissionData(lstCommission);
        }
    }
    
    //This method is used to send the commission data to LGCY end-point.
    private void sendCommissionData(List<Commission__c> lstCommission){
        Set<Id> setCommissionId = new Set<Id>();
        for(Commission__c objCommission : lstCommission){
            if(objCommission.X3rd_Party_Partner__c == 'LGCY Power'){
                setCommissionId.add(objCommission.Id);
            }
        }
        
        if(!setCommissionId.isEmpty()){
            Set<Id> setCommissionId2 = new Set<Id>();//and Opportunity__r.Opp_Primary_Contact__r.AccountId = '0012L000012GUMjQAO'
            for(Commission__c objCommission : [select Id from Commission__c 
                where Id in :setCommissionId ])
            {
                setCommissionId2.add(objCommission.Id);
            }
            
            if(!setCommissionId2.isEmpty()){
                PalmettoAPIService.sendCommissionData(setCommissionId2);
            }
        }
    }
}