unpackaged/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Commision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commission__c/fields/Balance_Due_Commissions__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due_Commissions__c</fullName>
    <formula>CASE( Lead_Source_Type__c , 
"Independent", IA_Total_Commissions_Value__c,Total_Commissions__c)

- Total_Commissions_Paid_To_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commissions Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Commission_Plan__c.field-meta.xml
<CustomField>
    <fullName>Commission_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commission Plan</label>
    <referenceTo>Commission_Plan__c</referenceTo>
    <relationshipName>Commisions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Contract_Received_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed_Date__c</fullName>
    <formula>Opportunity__r.Contract_Received_Confirmed_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Received Confirmed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/CP_Base_5kW_Program__c.field-meta.xml
<CustomField>
    <fullName>CP_Base_5kW_Program__c</fullName>
    <formula>IF( Commission_Plan__r.Base_6kW__c = 0,

     IF( Opportunity__r.System_Size_Calculated_kW__c &lt; 5,    
     Commission_Plan__r.X5K__c   *  Opportunity__r.System_Size_Calculated_kW__c, 
     Commission_Plan__r.X5kW__c    *  Opportunity__r.System_Size_Calculated_kW__c),

0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CP Base - 5kW Program</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/CP_Base_6kW_Program__c.field-meta.xml
<CustomField>
    <fullName>CP_Base_6kW_Program__c</fullName>
    <formula>IF( Commission_Plan__r.X5kW__c = 0,
    
     IF( Commission_Plan__r.X9kW__c = 0,
     

     IF( Opportunity__r.System_Size_Calculated_kW__c &gt;= 6,  
     Commission_Plan__r.Base_6kW__c *  Opportunity__r.System_Size_Calculated_kW__c,
     Commission_Plan__r.X6kW__c  *  Opportunity__r.System_Size_Calculated_kW__c), 
     
     IF(Opportunity__r.System_Size_Calculated_kW__c &gt; 9,  
          Commission_Plan__r.X9kW__c *  Opportunity__r.System_Size_Calculated_kW__c,
          IF(Opportunity__r.System_Size_Calculated_kW__c &lt; 6,
           Commission_Plan__r.X6kW__c  *  Opportunity__r.System_Size_Calculated_kW__c,
           Commission_Plan__r.Base_6kW__c *  Opportunity__r.System_Size_Calculated_kW__c)
           )
     ),

     0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CP Base - 6kW Program</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Dividend_Dealer_Fees__c.field-meta.xml
<CustomField>
    <fullName>Dividend_Dealer_Fees__c</fullName>
    <formula>Case(  Opportunity__r.Financing_Tool__c , 

"Dividend Loan", 
      0.11 *  Opportunity__r.Amount ,

0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dividend Dealer Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/IA_M1_Amount__c.field-meta.xml
<CustomField>
    <fullName>IA_M1_Amount__c</fullName>
    <formula>CASE( Loan_Pal__c , "Loan Pal", 0, 

CASE( Lead_Source_Type__c , 
"Independent", IA_Total_Commissions_Value__c * Commission_Plan__r.Milestone_1_Percent__c  , 

0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IA - M1 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/IA_M1_Paid__c.field-meta.xml
<CustomField>
    <fullName>IA_M1_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IA - M1 Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/IA_M2_Amount__c.field-meta.xml
<CustomField>
    <fullName>IA_M2_Amount__c</fullName>
    <formula>CASE( Loan_Pal__c , "Loan Pal", IA_Total_Commissions_Value__c, 

CASE( Lead_Source_Type__c , 
"Independent", IA_Total_Commissions_Value__c * Commission_Plan__r.Milestone_2_Percent__c   , 

0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IA - M2 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/IA_M2_Paid__c.field-meta.xml
<CustomField>
    <fullName>IA_M2_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IA - M2 Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/IA_M3_Amount__c.field-meta.xml
<CustomField>
    <fullName>IA_M3_Amount__c</fullName>
    <formula>CASE( Loan_Pal__c , "Loan Pal", 0, 

CASE( Lead_Source_Type__c , 
"Independent", IA_Total_Commissions_Value__c * Commission_Plan__r.Milestone_3_Percent__c , 

0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IA - M3 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/IA_M3_Paid__c.field-meta.xml
<CustomField>
    <fullName>IA_M3_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IA - M3 Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/IA_Total_Commisions__c.field-meta.xml
<CustomField>
    <fullName>IA_Total_Commisions__c</fullName>
    <formula>0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IA - Total Commisions</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Lead_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Type__c</fullName>
    <formula>TEXT(Opportunity__r.Lead_Source_Type__c)</formula>
    <label>Lead Source Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Loan_Pal__c.field-meta.xml
<CustomField>
    <fullName>Loan_Pal__c</fullName>
    <formula>Text(Opportunity__r.Financing_Tool__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Finance Tool</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Loan_Pal_Dealer_Fees__c.field-meta.xml
<CustomField>
    <fullName>Loan_Pal_Dealer_Fees__c</fullName>
    <formula>Case( Opportunity__r.Financing_Tool__c , "Loanpal",


CASE ( Opportunity__r.Loan_Term__c, "10", 0.215 * Opportunity__r.Amount,
"12", 0.215 * Opportunity__r.Amount,
"15", 0.215 * Opportunity__r.Amount,
"20", 0.215 * Opportunity__r.Amount,
0),

0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Pal Dealer Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/M1_Clawback_Applied_Paid__c.field-meta.xml
<CustomField>
    <fullName>M1_Clawback_Applied_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>M1 Clawback Applied to Balance (Paid)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/M1_Clawback_Complete__c.field-meta.xml
<CustomField>
    <fullName>M1_Clawback_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>M1 Clawback Processed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_1_Amount_Actual_Paid__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Amount_Actual_Paid__c</fullName>
    <description>Actual Milestone 1 Amount Paid - To be used for comparison if price changes after initial M1 payment</description>
    <label>Milestone 1 Amount (Actual Paid)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_2_Paid__c.field-meta.xml
<CustomField>
    <fullName>Milestone_2_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone 2 Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Process_Early_M3_Payment__c.field-meta.xml
<CustomField>
    <fullName>Process_Early_M3_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Process Early M3 Payment</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Total_Commissions__c.field-meta.xml
<CustomField>
    <fullName>Total_Commissions__c</fullName>
    <formula>Opportunity_Amount__c +  Downpayment__c - CP_Base__c - Dealer_Fees__c - Total_Adders__c - Structural_Electrical_Upgrade_Adder__c - Other_Misc_Adders__c - M3_Early_Payment_Fee__c +  CT_GreenBank_AdderValue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Commissions</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Total_Commissions_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Commissions_Value__c</fullName>
    <label>Total Commissions Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/X5_watt_M1_Amount__c.field-meta.xml
<CustomField>
    <fullName>X5_watt_M1_Amount__c</fullName>
    <formula>CASE(   Loan_Pal__c  , "Loan Pal",  IF(Opportunity__r.Contract_Received_Confirmed_Date__c &lt;  DATE(2019,3,18) ,0, X5_Watt_Total_Commissions__c * Commission_Plan__r.Milestone_1_Percent__c),

X5_Watt_Total_Commissions__c * Commission_Plan__r.Milestone_1_Percent__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>$5/watt M1 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/X5_Watt_Total_Commissions__c.field-meta.xml
<CustomField>
    <fullName>X5_Watt_Total_Commissions__c</fullName>
    <formula>Total_Commissions__c -  Price_5_Watt__c - CT_GreenBank_AdderValue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>&lt;$5/Watt Total Commissions</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/X5_Watt_Total_Commissions_Value__c.field-meta.xml
<CustomField>
    <fullName>X5_Watt_Total_Commissions_Value__c</fullName>
    <label>&lt;$5/Watt Total Commissions Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission_Plan__c/Commission_Plan__c.object-meta.xml
<CustomObject>
    <label>Commission Plan</label>
    <nameField>
        <label>Commission Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commission_Plan__c/fields/Milestone_1_Percent__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Percent__c</fullName>
    <label>Milestone 1 %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Commission_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commission Plans</relationshipLabel>
    <relationshipName>Commission_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed_Date__c</fullName>
    <label>Contract Received Confirmed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lead_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Type__c</fullName>
    <label>Lead Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>Self-Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OpportunityService.cls
public class OpportunityService
{
    public static void refreshCommission(Set<Id> setOppId){
        List<Commission__c> lstCommissionToUpdate = new List<Commission__c>();
        for(Commission__c objCommission : [
                SELECT Id, X5_Watt_Total_Commissions_Value__c, X5_Watt_Total_Commissions__c, Total_Commissions__c, X5_watt_M1_Amount__c,
                Opportunity__r.StageName, M1_Clawback_Applied_Paid__c, Milestone_1_Amount_Actual_Paid__c, M1_Clawback_Complete__c,
                Lead_Source_Type__c, Total_Commissions_Value__c, Commission_Plan__r.Milestone_1_Percent__c, Balance_Due_Commissions__c,
                CP_Base_5kW_Program__c, CP_Base_6kW_Program__c, Dividend_Dealer_Fees__c, IA_M3_Paid__c, IA_M1_Amount__c, IA_M2_Amount__c,
                IA_M3_Amount__c, IA_Total_Commisions__c, IA_M1_Paid__c, IA_M2_Paid__c, Loan_Pal__c, Milestone_2_Paid__c,
                Opportunity__r.Financing_Tool__c, Opportunity__r.Contract_Received_Confirmed_Date__c, Loan_Pal_Dealer_Fees__c,
                Process_Early_M3_Payment__c, Milestone_3_Amount__c
                FROM Commission__c 
                WHERE Opportunity__c IN :setOppId])
        {
            objCommission.X5_Watt_Total_Commissions_Value__c = objCommission.X5_Watt_Total_Commissions__c;
            objCommission.Total_Commissions_Value__c = objCommission.Total_Commissions__c;
            objCommission.X5_watt_M1_Value__c = objCommission.X5_watt_M1_Amount__c;
            objCommission.CP_Base_5kW_Program_Value__c = objCommission.CP_Base_5kW_Program__c;
            objCommission.CP_Base_6kW_Program_Value__c = objCommission.CP_Base_6kW_Program__c;
            objCommission.Dividend_Dealer_Value__c = objCommission.Dividend_Dealer_Fees__c;
            objCommission.Loan_Pal_Dealer_Value__c = objCommission.Loan_Pal_Dealer_Fees__c;
            
            if(objCommission.Opportunity__r.StageName == 'Cancelled'){
                objCommission.M1_Clawback_Amount__c = objCommission.Milestone_1_Amount_Actual_Paid__c;
            }
            if(objCommission.M1_Clawback_Applied_Paid__c == true && 
                (objCommission.Opportunity__r.StageName == 'Cancelled' || objCommission.Opportunity__r.StageName == '9. Change Order Pending') )
            {
                objCommission.Milestone_1_Amount_Actual_Paid__c = null;
            }
            if(objCommission.M1_Clawback_Complete__c == true && objCommission.M1_Clawback_Applied_Paid__c == false &&
                (objCommission.Opportunity__r.StageName == 'Cancelled' || objCommission.Opportunity__r.StageName == '9. Change Order Pending') )
            {
                objCommission.Clawback_Amount_Actual__c = objCommission.Milestone_1_Amount_Actual_Paid__c;
            }
            if(objCommission.Lead_Source_Type__c == 'Channel'){
                objCommission.CP_Milestone_1_Value__c = (objCommission.Total_Commissions_Value__c == null?0:objCommission.Total_Commissions_Value__c) * (objCommission.Commission_Plan__r.Milestone_1_Percent__c == null?0:objCommission.Commission_Plan__r.Milestone_1_Percent__c);
                objCommission.Commissions_Payable_Value__c = objCommission.Balance_Due_Commissions__c;
            }
            if(objCommission.IA_M3_Paid__c == true){
                //objCommission.IA_M3_Paid_Date__c = Date.today();
            }
            if(objCommission.Lead_Source_Type__c == 'Independent'){
                objCommission.IA_M1_Amount_Value__c = objCommission.IA_M1_Amount__c;
                objCommission.IA_M2_Amount_Value__c = objCommission.IA_M2_Amount__c;
                objCommission.IA_M3_Amount_Value__c = objCommission.IA_M3_Amount__c;
                objCommission.IA_Total_Commissions_Value__c = objCommission.IA_Total_Commisions__c;
                objCommission.Commissions_Payable_Value__c = objCommission.Balance_Due_Commissions__c;
            }
            if(objCommission.IA_M1_Paid__c == true){
                //objCommission.IA_M1_Paid_Date__c = Date.today();
            }
            if(objCommission.IA_M2_Paid__c == true){
                //objCommission.IA_M2_Paid_Date__c = Date.today();
            }
            
            if(objCommission.Milestone_2_Paid__c == true && (objCommission.Opportunity__r.Financing_Tool__c == 'Loan Pal' || objCommission.Opportunity__r.Financing_Tool__c == 'Loanpal')
                && objCommission.Opportunity__r.Contract_Received_Confirmed_Date__c <= Date.newInstance(2019, 3, 15))
            {
                objCommission.Milestone_3_Processed__c = true;
                objCommission.Milestone_3_Paid__c = true;
            }
            
            if(objCommission.M1_Clawback_Complete__c == true && (objCommission.Loan_Pal__c == 'Loan Pal' || objCommission.Loan_Pal__c == 'Loanpal') &&
                objCommission.Milestone_1_Amount_Actual_Paid__c == null)
            {
                objCommission.M1_Clawback_Applied_Paid__c = true;
            }
            
            if(objCommission.M1_Clawback_Complete__c == true){
                //objCommission.M1_Clawback_Processed_Date__c = Date.today();
            }
                       
            if(objCommission.Process_Early_M3_Payment__c == true){
                objCommission.M3_Early_Payment_Fee__c = (0.1 * (objCommission.Balance_Due_Commissions__c == null?0:objCommission.Balance_Due_Commissions__c));
                objCommission.Milestone_3_Processed__c = true;
                objCommission.Milestone_3_Actual_Paid__c = objCommission.Milestone_3_Amount__c;
                //objCommission.Milestone_3_Processed_Date__c = Date.today();
            }
             
                
            lstCommissionToUpdate.add(objCommission);
        }
        
        if(!lstCommissionToUpdate.isEmpty())
            update lstCommissionToUpdate;
    }
}