unpackaged/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Commision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Last_Refreshed_Commissions__c.field-meta.xml
<CustomField>
    <fullName>Last_Refreshed_Commissions__c</fullName>
    <label>Last Refreshed Commissions</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/TriggerConfiguration__c/TriggerConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Configuration</label>
</CustomObject>

unpackaged/main/default/classes/OpportunityRefreshBatch.cls
global class OpportunityRefreshBatch implements Database.Batchable<SObject>, Schedulable {
    global void execute(SchedulableContext sc){
        TriggerConfiguration__c objTriggerConfigurationRCCS = TriggerConfiguration__c.getInstance('Refresh Commissions');
        if(objTriggerConfigurationRCCS != null && objTriggerConfigurationRCCS.Active__c == true){
            Database.executeBatch(new OpportunityRefreshBatch(), 1);
        }
    }
    
    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        String query = 'select Id, Amount from Opportunity '; 
        query += 'where Id in (select Opportunity__c from Commission__c) AND LastModifiedDate = TODAY';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Opportunity> lstOpportunity) {
        TriggerConfiguration__c objTriggerConfigurationCS = TriggerConfiguration__c.getInstance('HomeCustomerUpdate');
        if(objTriggerConfigurationCS != null){
            objTriggerConfigurationCS.Active__c = false;
            update objTriggerConfigurationCS;
        }
        
        TriggerConfiguration__c objAlTriggerConfigurationCS = TriggerConfiguration__c.getInstance('LGCY API trigger');
        if(objAlTriggerConfigurationCS != null){
            objAlTriggerConfigurationCS.Active__c = false;
            update objAlTriggerConfigurationCS;
        }
    
        Set<Id> setOppId = new Set<Id>();
        for(Opportunity objOpp : lstOpportunity){
            setOppId.add(objOpp.Id);
            objOpp.Last_Refreshed_Commissions__c = Datetime.now();
        }
        
        if(!lstOpportunity.isEmpty())
            update lstOpportunity;
            
        OpportunityService.refreshCommission(setOppId);
    }
    
    global void finish(Database.BatchableContext context) {
        TriggerConfiguration__c objTriggerConfigurationCS = TriggerConfiguration__c.getInstance('HomeCustomerUpdate');
        if(objTriggerConfigurationCS != null){
            objTriggerConfigurationCS.Active__c = true;
            update objTriggerConfigurationCS;
        }
        
        TriggerConfiguration__c objAlTriggerConfigurationCS = TriggerConfiguration__c.getInstance('LGCY API trigger');
        if(objAlTriggerConfigurationCS != null){
            objAlTriggerConfigurationCS.Active__c = true;
            update objAlTriggerConfigurationCS;
        }
    }
}