unpackaged/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Commision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commission__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <formula>Opportunity__r.Cancellation_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Contract_Received_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed_Date__c</fullName>
    <formula>Opportunity__r.Contract_Received_Confirmed_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Received Confirmed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Contract_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Date__c</fullName>
    <formula>Opportunity__r.Contract_Received_Date__c</formula>
    <label>Contract Received Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/M1_Clawback_Complete__c.field-meta.xml
<CustomField>
    <fullName>M1_Clawback_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>M1 Clawback Processed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/M1_Clawback_Processed_Date__c.field-meta.xml
<CustomField>
    <fullName>M1_Clawback_Processed_Date__c</fullName>
    <label>M1 Clawback Processed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/M3__c.field-meta.xml
<CustomField>
    <fullName>M3__c</fullName>
    <label>M3 %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_1_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Amount__c</fullName>
    <formula>CASE( Lead_Source_Type__c, 

"Independent", IA_M1_Amount_Value__c,

 X5_watt_M1_Value__c) - M1_Sales_Rep_Payroll_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Milestone 1 Amount (Calc)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_1_Amount_Actual_Paid__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Amount_Actual_Paid__c</fullName>
    <description>Actual Milestone 1 Amount Paid - To be used for comparison if price changes after initial M1 payment</description>
    <label>Milestone 1 Amount (Actual Paid)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_1_Date_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Date_Calculated__c</fullName>
    <formula>CASE(  Opportunity__r.X3rd_Party_Partner__c , "Commonwealth Energy MA, Inc",  

IF( Contract_Received_Date__c &gt; Date(2021,3,31),Contract_Received_Date__c, Opportunity__r.Contract_Received_Confirmed_Date__c),


Opportunity__r.Contract_Received_Confirmed_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Milestone 1 Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_1_Paid__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone 1 Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_1_Processed__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone 1 Processed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_1_Processed_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_1_Processed_Date__c</fullName>
    <label>Milestone 1 Processed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_2_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_2_Amount__c</fullName>
    <formula>CASE( Loan_Pal__c , "Loan Pal", IF(Opportunity__r.Contract_Received_Confirmed_Date__c &lt; DATE(2019,3,18) , True_Total_Commissions_Value__c, X5_Watt_Total_Commissions_Value__c * Commission_Plan__r.Milestone_2_Percent__c),


CASE( Lead_Source_Type__c , 
"Independent", IA_M2_Amount_Value__c, 

(X5_Watt_Total_Commissions_Value__c * Commission_Plan__r.Milestone_2_Percent__c)))



+ Milestone_2_Commission_True_Up__c

+ 	CT_GreenBank_AdderValue__c 

- M2_Sales_Rep_Payroll_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Milestone 2 Amount (Calc)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_2_Amount_Actual_Paid__c.field-meta.xml
<CustomField>
    <fullName>Milestone_2_Amount_Actual_Paid__c</fullName>
    <description>Actual Milestone 2 Amount Paid - To be used for comparison if price changes after initial M2 payment</description>
    <label>Milestone 2 Amount (Actual Paid)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_2_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_2_Date__c</fullName>
    <formula>CASE( Opportunity__r.X3rd_Party_Partner__c , "Commonwealth Energy MA, Inc",

IF( Contract_Received_Date__c &gt; Date(2021,3,31), Contract_Received_Confirmed_Date__c + 30, Installation_Complete_Date__c),

Installation_Complete_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Milestone 2 Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_2_Paid__c.field-meta.xml
<CustomField>
    <fullName>Milestone_2_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone 2 Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_2_Processed__c.field-meta.xml
<CustomField>
    <fullName>Milestone_2_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone 2 Processed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_2_Processed_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_2_Processed_Date__c</fullName>
    <label>Milestone 2 Processed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_3_Actual_Paid__c.field-meta.xml
<CustomField>
    <fullName>Milestone_3_Actual_Paid__c</fullName>
    <label>Milestone 3 Actual Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_3_Amount__c.field-meta.xml
<CustomField>
    <fullName>Milestone_3_Amount__c</fullName>
    <formula>CASE( Lead_Source_Type__c , 
"Independent", IA_M3_Amount_Value__c,

     IF(   AND(Loan_Pal__c  = "Loan Pal",Opportunity__r.Contract_Received_Confirmed_Date__c &lt; DATE(2019,3,18)),
          0, ((X5_Watt_Total_Commissions_Value__c * Commission_Plan__r.Milestone_3_Percent__c ) +  Price_5_Watt__c)
        )  
  )

+ Milestone_3_Commission_True_Up__c -  M3_Early_Payment_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Milestone 3 Amount (Calc)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_3_Date_PTO_3_Days__c.field-meta.xml
<CustomField>
    <fullName>Milestone_3_Date_PTO_3_Days__c</fullName>
    <formula>IF(Opportunity__r.Net_Meter_Install_Date__c &gt; DATE(2020,8,26), Opportunity__r.Net_Meter_Install_Date__c,

Case( Loan_Pal__c , 

"Sunnova Lease", IF( Opportunity__r.Contract_Received_Confirmed_Date__c &lt; Date(2019,4,1),Opportunity__r.Net_Meter_Install_Date__c + 15, Opportunity__r.Net_Meter_Install_Date__c + 3),

Opportunity__r.Net_Meter_Install_Date__c + 3)

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Milestone 3 Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_3_Paid__c.field-meta.xml
<CustomField>
    <fullName>Milestone_3_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone 3 Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_3_Processed__c.field-meta.xml
<CustomField>
    <fullName>Milestone_3_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone 3 Processed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Milestone_3_Processed_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_3_Processed_Date__c</fullName>
    <label>Milestone 3 Processed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <label>Cancellation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Auto populates the "Close Date"date that only the Project Admin/Coordinator (currently Sid) or Project Manager (currently Kevin) can check.</description>
    <label>Contract Received Confirmed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed_Date__c</fullName>
    <label>Contract Received Confirmed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Date__c</fullName>
    <label>Contract Received Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/CommissionHandler.cls
public class CommissionHandler {
    
    public static Set<Id> setOppId;
    
    public CommissionHandler()
    {
        
    }
    public static void ProcessM1MileStone()
    {
        //Opportunity__r.Contract_Received_Confirmed__c = true
        String M1 = '';
        string where_clause = '';
        DateTime start_date = dateTime.now().addDays(-360);
        DateTime end_date = System.Datetime.now().addDays(-1);
        where_clause = 'WHERE';
        M1 = string.format('((Milestone_1_Date_Calculated__c >={0} AND Milestone_1_Date_Calculated__c <= {1}) AND Opportunity__r.Contract_Received_Confirmed_Date__c != null AND Opportunity__r.StageName NOT IN({2}) AND Milestone_1_Processed__c = false AND Milestone_1_Paid__c = false)',
                           new string[]{start_date.format('yyyy-MM-dd'),
                               end_date.format('yyyy-MM-dd'),
                               '\'9. Change Order Pending\',\'Cancelled\''
                               });
                               
         if(setOppId != null && !setOppId.isEmpty()){
             M1 += ' AND Opportunity__c IN :setOppId ';
         } 
         
         string soql = string.format('SELECT Milestone_1_Amount__c,Milestone_1_Amount_Actual_Paid__c,Milestone_1_Processed_Date__c from Commission__c {0} ({1})',new string[]
                                    {where_clause,M1});
         system.debug('soql:'+soql);
         List<Commission__c> commission_list = (List<Commission__c>)Database.query(soql);
         system.debug('M1 Size:'+commission_list.size());
         for(Commission__c item:commission_list)
         {
           item.Milestone_1_Processed_Date__c = System.date.today();
           item.Milestone_1_Amount_Actual_Paid__c = item.Milestone_1_Amount__c;
           item.Milestone_1_Processed__c = true;
         }
        
         update commission_list;
    }
    
    public static void ProcessM2MileStone()
    {
        String M2 = '';
        string where_clause = '';
        DateTime start_date = dateTime.now().addDays(-360);
        DateTime end_date = System.Datetime.now().addDays(-1);
        where_clause = 'WHERE';
        M2 = string.format('((Milestone_2_Date__c >={0} AND Milestone_2_Date__c <={1} ) AND Milestone_1_Paid__c = true AND Milestone_2_Paid__c = false AND Milestone_2_Processed__c = false)',
                               new string[]{
                                   start_date.format('yyyy-MM-dd'),
                                       end_date.format('yyyy-MM-dd')
                                       });
        string soql = string.format('SELECT Milestone_2_Amount__c,Milestone_2_Amount_Actual_Paid__c,Milestone_2_Processed_Date__c' +
                                    ' from Commission__c {0} ({1})',new string[]
                                    {
                                        where_clause,M2
                                    });
       List<Commission__c> commission_list = (List<Commission__c>)Database.query(soql);
        system.debug('M2 Size:'+commission_list.size());        
         for(Commission__c item:commission_list)
         {
           item.Milestone_2_Processed_Date__c = System.date.today();
           item.Milestone_2_Amount_Actual_Paid__c = item.Milestone_2_Amount__c;
           item.Milestone_2_Processed__c = true;
         }
        
         update commission_list;
    }
    
    public static void ProcessM3MileStone()
    {
        //(M3__c != null AND M3__c != 0)
        String M3 = '';
        string where_clause = '';
        DateTime start_date = dateTime.now().addDays(-360);
        DateTime end_date = System.Datetime.now().addDays(-1);
        where_clause = 'WHERE';
        M3 = string.format('((Milestone_3_Date_PTO_3_Days__c >={0} AND Milestone_3_Date_PTO_3_Days__c<={1} ) AND Milestone_3_Processed__c = false AND Milestone_3_Paid__c = false AND Milestone_2_Paid__c = true AND Milestone_3_Amount__c != 0 AND Milestone_3_Amount__c != -0.01 AND Milestone_3_Amount__c != 0.01)',
                               new string[]{
                                   start_date.format('yyyy-MM-dd'),
                                       end_date.format('yyyy-MM-dd')
                                       });
        string soql = string.format('SELECT Milestone_3_Amount__c,Milestone_3_Actual_Paid__c,Milestone_3_Processed_Date__c' +
                                    ' from Commission__c {0} ({1})',new string[]
                                    {
                                        where_clause,M3
                                    });
                                    
        soql += ' AND Contract_Received_Date__c >= 2020-01-01';
       List<Commission__c> commission_list = (List<Commission__c>)Database.query(soql);
        system.debug('M3 Size:'+commission_list.size());
         for(Commission__c item:commission_list)
         {
           item.Milestone_3_Processed_Date__c = System.date.today();
           item.Milestone_3_Actual_Paid__c = item.Milestone_3_Amount__c;
           item.Milestone_3_Processed__c = true;
         }
        
         update commission_list;
    }
    
    public static void ProcessClawBackMileStone()
    {
         String claw_back = '';
        string where_clause = '';
        DateTime start_date = dateTime.now().addDays(-360);
        DateTime end_date = System.Datetime.now().addDays(-1);
        where_clause = 'WHERE';
        claw_back = string.format(' ((Opportunity__r.Cancellation_Date__c >={0} AND Opportunity__r.Cancellation_Date__c<={1}) AND Milestone_1_Paid__c = true AND M1_Clawback_Complete__c = false)'
                                      ,new string[]{
                                          start_date.format('yyyy-MM-dd'),
                                              end_date.format('yyyy-MM-dd')
                                              }
                                     );
       string soql = string.format('SELECT M1_Clawback_Processed_Date__c from Commission__c {0} ({1})',new string[]
                                    {
                                        where_clause,claw_back
                                    });
       List<Commission__c> commission_list = (List<Commission__c>)Database.query(soql);
       system.debug('claw_back Size:'+commission_list.size());
       for(Commission__c item:commission_list)
       {
          item.M1_Clawback_Processed_Date__c = System.date.today();
          item.M1_Clawback_Complete__c = true;
       }
        
         update commission_list;
    }
    
    public static void sendErrorEmail( string emailAddress,Exception e)
    {
        if ( e == null )
        {
            return;
        }
        string subject = 'Commision to be processed failed';
        string body =
                'Dear ' + Userinfo.getName() + ',<br/>' +
                '<br/>' +
                'Error details in Commission to be processor Schedular:<br/>' +
                'Error: ' + e.getCause() + '|' + e.getLineNumber() + '|' + e.getMessage() + '|' + e.getStackTraceString() + '|' + e.getTypeName() + '<br/>' +
                'Regards,<br/>' +
                '<br/>' +
                'Infinity Creation';
        sendEmail( emailAddress, subject, body );
    }
    private static void sendEmail( string emailAddress, string subject, string body )
    {
        try
        {
            if ( emailAddress == null )
            {
                return;
            }

            Messaging.reserveSingleEmailCapacity( 1 );
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            List< string > toAddresses = new List< string>();
            toAddresses.add( emailAddress );

            mail.setToAddresses( toAddresses );
            mail.setReplyTo( 'jawad@infinitycreation.com' );
            mail.setSenderDisplayName( 'Infinity Creation' );
            mail.setSubject( subject );
            mail.setBccSender( false );
            mail.setUseSignature( false );
            mail.setPlainTextBody( body );
            mail.setHtmlBody( body );
            Messaging.sendEmail( new Messaging.SingleEmailMessage[] { mail } );
        }
        catch( Exception ex )
        {
            system.debug( LoggingLevel.Error, 'Failed to send email' );
            system.debug( 'Failed to processed'+ex.getStackTRaceString() );
            
        }
    }
}