unpackaged/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Commision Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commission__c/fields/Contract_Received_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed_Date__c</fullName>
    <formula>Opportunity__r.Contract_Received_Confirmed_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Received Confirmed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Lead_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Type__c</fullName>
    <formula>TEXT(Opportunity__r.Lead_Source_Type__c)</formula>
    <label>Lead Source Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <formula>VALUE(Text(Opportunity__r.Loan_Term__c))</formula>
    <label>Loan Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Commission__c/fields/X3rd_Party_Partner__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Partner__c</fullName>
    <formula>Text(Opportunity__r.X3rd_Party_Partner__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>3rd Party Partner</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Commission_Plan__c/Commission_Plan__c.object-meta.xml
<CustomObject>
    <label>Commission Plan</label>
    <nameField>
        <label>Commission Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Commission_Plan__c/fields/X3rd_Party_Partner__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Partner__c</fullName>
    <label>3rd Party Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10x Solutions, LLC</fullName>
            </value>
            <value>
                <fullName>10x Solutions LLC</fullName>
            </value>
            <value>
                <fullName>180 South Solar</fullName>
            </value>
            <value>
                <fullName>1nnov8tivellc</fullName>
            </value>
            <value>
                <fullName>1UP Solar</fullName>
            </value>
            <value>
                <fullName>360 Total Solutions LLC</fullName>
            </value>
            <value>
                <fullName>Absolute Sustainability LLC</fullName>
            </value>
            <value>
                <fullName>Accept Solar</fullName>
            </value>
            <value>
                <fullName>Ace Solar and Roofing</fullName>
            </value>
            <value>
                <fullName>Activation Department</fullName>
            </value>
            <value>
                <fullName>Adorno Consulting LLC</fullName>
            </value>
            <value>
                <fullName>Advanced Exteriors, LLC</fullName>
            </value>
            <value>
                <fullName>Alectrona Solar LLC</fullName>
            </value>
            <value>
                <fullName>Alliance Service Professionals LLC</fullName>
            </value>
            <value>
                <fullName>Alpha Solar</fullName>
            </value>
            <value>
                <fullName>Alpha Sol LLC</fullName>
            </value>
            <value>
                <fullName>Altezza Solar LLC</fullName>
            </value>
            <value>
                <fullName>Anders Jacobson LLC dba Zero Energy</fullName>
            </value>
            <value>
                <fullName>Antares Energy Solutions</fullName>
            </value>
            <value>
                <fullName>A Plus Business Solutions</fullName>
            </value>
            <value>
                <fullName>Aten Concepts</fullName>
            </value>
            <value>
                <fullName>Aten Concepts Inc</fullName>
            </value>
            <value>
                <fullName>ATJ, LLC</fullName>
            </value>
            <value>
                <fullName>Atlas Capital</fullName>
            </value>
            <value>
                <fullName>Authentic Solar Power, LLC</fullName>
            </value>
            <value>
                <fullName>AUTOMATCH, LLC</fullName>
            </value>
            <value>
                <fullName>Avantalo Inc.</fullName>
            </value>
            <value>
                <fullName>Barry Enterprises</fullName>
            </value>
            <value>
                <fullName>Blanton Group</fullName>
            </value>
            <value>
                <fullName>Booth Enterprises</fullName>
            </value>
            <value>
                <fullName>Harbor Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Auto populates the "Close Date"date that only the Project Admin/Coordinator (currently Sid) or Project Manager (currently Kevin) can check.</description>
    <label>Contract Received Confirmed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Confirmed_Date__c</fullName>
    <label>Contract Received Confirmed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Engineering_Created__c.field-meta.xml
<CustomField>
    <fullName>Engineering_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BOM Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Final_Design_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Design_Created_Date__c</fullName>
    <label>BOM Created Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lead_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Type__c</fullName>
    <label>Lead Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>Self-Generated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loan_Term__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term__c</fullName>
    <label>Loan Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Number_of_Arrays__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Arrays__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Number of Arrays</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Number_of_Solar_Panels__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Solar_Panels__c</fullName>
    <inlineHelpText>Source of truth is Alchemy</inlineHelpText>
    <label>Number of Solar Panels</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Panel_Type__c.field-meta.xml
<CustomField>
    <fullName>Panel_Type__c</fullName>
    <label>Panel Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LG 310N1C-G4</fullName>
            </value>
            <value>
                <fullName>LG 320 Black/Black</fullName>
            </value>
            <value>
                <fullName>LG335N1C-A5</fullName>
            </value>
            <value>
                <fullName>LG 335W</fullName>
            </value>
            <value>
                <fullName>LG 360W</fullName>
            </value>
            <value>
                <fullName>Q-Peak G4.1 305</fullName>
            </value>
            <value>
                <fullName>Q.PEAK Duo BLK-G5 310</fullName>
            </value>
            <value>
                <fullName>Q.PEAK-G4.1 300</fullName>
            </value>
            <value>
                <fullName>Q Cells 310W Q.Peak Duo</fullName>
            </value>
            <value>
                <fullName>Silfab 300W - All black</fullName>
            </value>
            <value>
                <fullName>Trina 300TSM-DD05A.08(II)</fullName>
            </value>
            <value>
                <fullName>Axitec 300 AXIblackpremium</fullName>
            </value>
            <value>
                <fullName>Yingli 310D-30b</fullName>
            </value>
            <value>
                <fullName>Hanwha 315w</fullName>
            </value>
            <value>
                <fullName>330W All Black Module</fullName>
            </value>
            <value>
                <fullName>Qcell 340W</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Proposal_Created__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proposal Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X3rd_Party_Partner__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Partner__c</fullName>
    <label>3rd Party Partner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100 better built</fullName>
            </value>
            <value>
                <fullName>10x Solutions LLC</fullName>
            </value>
            <value>
                <fullName>1nnov8tive LLC</fullName>
            </value>
            <value>
                <fullName>1UP Solar</fullName>
            </value>
            <value>
                <fullName>1UP Solar LLC</fullName>
            </value>
            <value>
                <fullName>25th Hour Solutions LLC</fullName>
            </value>
            <value>
                <fullName>320 Solar LLC</fullName>
            </value>
            <value>
                <fullName>361 Technologies LLC</fullName>
            </value>
            <value>
                <fullName>365 Solar Energy</fullName>
            </value>
            <value>
                <fullName>3rd Rock Solar Discounters</fullName>
            </value>
            <value>
                <fullName>413Solar</fullName>
            </value>
            <value>
                <fullName>413Solar LLC</fullName>
            </value>
            <value>
                <fullName>4Season Real Estate Solutions LLC</fullName>
            </value>
            <value>
                <fullName>528 Lumen</fullName>
            </value>
            <value>
                <fullName>A3nergy Solutions</fullName>
            </value>
            <value>
                <fullName>ABC PRO GRP, LLC</fullName>
            </value>
            <value>
                <fullName>Absolute Sustainability LLC</fullName>
            </value>
            <value>
                <fullName>Active Care Connections</fullName>
            </value>
            <value>
                <fullName>Adorno Consulting LLC</fullName>
            </value>
            <value>
                <fullName>Advanced Exteriors, LLC</fullName>
            </value>
            <value>
                <fullName>Advanced Exteriors LLC</fullName>
            </value>
            <value>
                <fullName>Advisors Solar Group Inc.</fullName>
            </value>
            <value>
                <fullName>AE Contracting Services LLC</fullName>
            </value>
            <value>
                <fullName>AE Solar</fullName>
            </value>
            <value>
                <fullName>Ageint Security</fullName>
            </value>
            <value>
                <fullName>Alamo Smart Home</fullName>
            </value>
            <value>
                <fullName>Aligned Energy Partners</fullName>
            </value>
            <value>
                <fullName>Alliance Service Professionals LLC</fullName>
            </value>
            <value>
                <fullName>All in One Exterior and Construction</fullName>
            </value>
            <value>
                <fullName>Aloha Sun Power</fullName>
            </value>
            <value>
                <fullName>Harbor Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CommissionToBeProcessedSchedularTest.cls
@isTest
private class CommissionToBeProcessedSchedularTest
{
	private static testmethod void commissionToBeProcessedTest()
    {
        string account_recordtype_id = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Residential - Customer').getRecordTypeId();
        Account acc = TestDataFactory.createAccount('Harbor Energy',account_recordtype_id);
        insert acc;
        Contact cont = TestDataFactory.createContact('Test','O1', acc.id);
        cont.Title = 'Leadership';
        insert cont;
        List<Opportunity> opp_list = new List<Opportunity>();
        string opp_recordtype_id = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity opp_1 = TestDataFactory.createOpportunity(opp_recordtype_id, 'Test 1', acc.id, '17. Install Ready', 'Alabama');
        opp_1.LeadSource = '3rd Party Provider';
        opp_1.Lead_Source_Type__c = 'Channel';
        opp_1.X3rd_Party_Partner__c = 'Harbor Energy';
        opp_1.Financing_Tool__c	= 'Sunlight';
        opp_1.Loan_Term__c = '20';
        opp_1.Proposal_Created__c = true;
        opp_1.Engineering_Created__c = true;
        opp_1.Final_Design_Created_Date__c = system.Date.today();
        opp_1.Number_of_Arrays__c = 1;
		opp_1.Contract_Received_Confirmed__c= true;
        opp_1.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-5);
        opp_1.Amount = 30000;
        opp_1.Number_of_Solar_Panels__c  = 25;
        opp_1.Panel_Type__c = 'Q.PEAK-G4.1 300';
        opp_1.Panel_Wattage__c = 300;
        opp_list.add(opp_1);
        /* -------------------------------------------------------*/
        Opportunity opp_2 = TestDataFactory.createOpportunity(opp_recordtype_id, 'Test 2', acc.id, '7a. Contract Received Confirmed', 'Alabama');
        opp_2.LeadSource = '3rd Party Provider';
        opp_2.Lead_Source_Type__c = 'Channel';
        opp_2.Financing_Tool__c	= 'Sunlight';
        opp_2.X3rd_Party_Partner__c = 'Harbor Energy';
        opp_2.Loan_Term__c = '20';
        opp_2.Proposal_Created__c = true;
        opp_2.Engineering_Created__c = true;
        opp_2.Final_Design_Created_Date__c = system.Date.today();
        opp_2.Number_of_Arrays__c = 1;
		opp_2.Contract_Received_Confirmed__c= true;
        opp_2.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-5);
        opp_2.Amount = 30000;
        opp_2.Number_of_Solar_Panels__c  = 25;
        opp_2.Panel_Type__c = 'Q.PEAK-G4.1 300';
        opp_2.Panel_Wattage__c = 300;
        opp_list.add(opp_2);
        /*--------------------------------------- */
        Opportunity opp_3 = TestDataFactory.createOpportunity(opp_recordtype_id, 'Test 3', acc.id, '22. PTO', 'Alabama');
        opp_3.LeadSource = '3rd Party Provider';
        opp_3.Lead_Source_Type__c = 'Channel';
        opp_3.Financing_Tool__c	= 'Sunlight';
        opp_3.X3rd_Party_Partner__c = 'Harbor Energy';
        opp_2.Loan_Term__c = '20';
        opp_3.Proposal_Created__c = true;
        opp_3.Engineering_Created__c = true;
        opp_3.Final_Design_Created_Date__c = system.Date.today();
        opp_3.Number_of_Arrays__c = 1;
		opp_3.Contract_Received_Confirmed__c= true;
        opp_3.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-5);
        opp_3.Amount = 30000;
        opp_3.Number_of_Solar_Panels__c  = 25;
        opp_3.Panel_Type__c = 'Q.PEAK-G4.1 300';
        opp_3.Panel_Wattage__c = 300;
        opp_list.add(opp_3);
        /*--------------------------------------------------*/
        Opportunity opp_4 = TestDataFactory.createOpportunity(opp_recordtype_id, 'Test 3', acc.id, 'Cancelled', 'Alabama');
        opp_4.Reason_for_loss__c = 'Cancelled with Finance Partner';
        opp_4.LeadSource = '3rd Party Provider';
        opp_4.Lead_Source_Type__c = 'Channel';
        opp_4.X3rd_Party_Partner__c = 'Harbor Energy';
        opp_4.Financing_Tool__c	= 'Sunlight';
        opp_4.Loan_Term__c = '20';
		opp_4.Proposal_Created__c = true;
        opp_4.Engineering_Created__c = true;
        opp_4.Final_Design_Created_Date__c = system.Date.today();
        opp_4.Number_of_Arrays__c = 1;
		opp_4.Contract_Received_Confirmed__c= true;
        opp_4.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-5);
        opp_4.Amount = 30000;
        opp_4.Number_of_Solar_Panels__c  = 25;
        opp_4.Panel_Type__c = 'Q.PEAK-G4.1 300';
        opp_4.Panel_Wattage__c = 300;
        opp_list.add(opp_4);
        /*--------------------------------------------*/
        Opportunity opp_5 = TestDataFactory.createOpportunity(opp_recordtype_id, 'Test 1', acc.id, '17. Install Ready', 'Alabama');
        opp_5.LeadSource = '3rd Party Provider';
        opp_5.Lead_Source_Type__c = 'Channel';
        opp_5.X3rd_Party_Partner__c = 'Harbor Energy';
        opp_5.Financing_Tool__c	= 'Sunlight';
        opp_5.Loan_Term__c = '20';
        opp_5.Proposal_Created__c = true;
        opp_5.Engineering_Created__c = true;
        opp_5.Final_Design_Created_Date__c = system.Date.today();
        opp_5.Number_of_Arrays__c = 1;
		opp_5.Contract_Received_Confirmed__c= true;
        opp_5.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-5);
        opp_5.Amount = 30000;
        opp_5.Number_of_Solar_Panels__c  = 25;
        opp_5.Panel_Type__c = 'Q.PEAK-G4.1 300';
        opp_5.Panel_Wattage__c = 300;
        opp_list.add(opp_5);
        /*--------------------------------------------------------------*/
        Opportunity opp_6 = TestDataFactory.createOpportunity(opp_recordtype_id, 'Test 1', acc.id, '17. Install Ready', 'Alabama');
        opp_6.LeadSource = '3rd Party Provider';
        opp_6.Lead_Source_Type__c = 'Channel';
        opp_6.X3rd_Party_Partner__c = '360 Total Solutions LLC';
        opp_6.Financing_Tool__c	= 'Sunlight';
        opp_6.Loan_Term__c = '20';
        opp_6.Proposal_Created__c = true;
        opp_6.Engineering_Created__c = true;
        opp_6.Final_Design_Created_Date__c = system.Date.today();
        opp_6.Number_of_Arrays__c = 1;
		opp_6.Contract_Received_Confirmed__c= true;
        opp_6.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-5);
        opp_6.Amount = 30000;
        opp_6.Number_of_Solar_Panels__c  = 25;
        opp_6.Panel_Type__c = 'Q.PEAK-G4.1 300';
        opp_6.Panel_Wattage__c = 300;
        opp_list.add(opp_6);
        insert opp_list;
        opp_1.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-6);
        update opp_1;
        opp_5.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-6);
        update opp_5;
        opp_6.Contract_Received_Confirmed_Date__c = system.Date.today().addDays(-6);
        update opp_6;
        /*----------------------------------------------------*/
        
        Commission_plan__c commission_plan_1 = TestDataFactory.createCommissionPlan('CP Alabama');
		commission_plan_1.Location__c = 'Alabama';
        commission_plan_1.User__c = UserInfo.getUserId();
        commission_plan_1.Channel_Partner_Account__c = acc.id;
        commission_plan_1.X3rd_Party_Partner__c = 'Harbor Energy';
        commission_plan_1.Base_6kW__c = 2500;
        commission_plan_1.X6kW__c = 2500;
		commission_plan_1.Milestone_1_Percent__c = 30;
        commission_plan_1.Milestone_2_Percent__c = 55;
        commission_plan_1.Milestone_3_Percent__c = 15;
        insert commission_plan_1;
        Commission__c commission_1 = new Commission__c();
        commission_1.Opportunity__c = opp_1.id;
        commission_1.Commission_Plan__c = commission_plan_1.id;
       
        insert commission_1;
        /*------------------------------------------ */
        Commission__c commission_2 = new Commission__c();
        commission_2.Opportunity__c = opp_2.id;
        commission_2.Commission_Plan__c = commission_plan_1.id;
        insert commission_2;
        /*------------------------------------------ */
        Commission__c commission_3 = new Commission__c();
        commission_3.Opportunity__c = opp_3.id;
        commission_3.Commission_Plan__c = commission_plan_1.id;
        
        insert commission_3;
        /*------------------------------------------ */
        Commission__c commission_4 = new Commission__c();
        commission_4.Opportunity__c = opp_4.id;
        commission_4.Commission_Plan__c = commission_plan_1.id;
        insert commission_4;
        /*------------------------------------------ */
        Commission__c commission_5 = new Commission__c();
        commission_5.Opportunity__c = opp_5.id;
        commission_5.Commission_Plan__c = commission_plan_1.id;
        insert commission_5;
        /*------------------------------------------ */
        Commission__c commission_6 = new Commission__c();
        commission_6.Opportunity__c = opp_6.id;
        commission_6.Commission_Plan__c = commission_plan_1.id;
        insert commission_6;
        test.startTest();
        String CRON_EXP = '0 0 * * * ?'; 
        String jobId = System.schedule('Commission', CRON_EXP, new CommissionToBeProcessedSchedular());
        try
        {
            integer i = 1/0;
        }
        catch(exception ex)
        {
            CommissionHandler.sendErrorEmail('test@gmail.com',ex);
        }
        test.stopTest();
    }
}