unpackaged/main/default/objects/Opportunity/fields/Change_Order_Reason__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_Reason__c</fullName>
    <label>Change Order Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancellation Pending</fullName>
            </value>
            <value>
                <fullName>Sunlight Stip</fullName>
                <label>Contract / Loan Change</label>
            </value>
            <value>
                <fullName>Customer Failing to Action</fullName>
            </value>
            <value>
                <fullName>Customer Delay</fullName>
                <label>Customer Unresponsive</label>
            </value>
            <value>
                <fullName>EE/Offset Discrepancy</fullName>
            </value>
            <value>
                <fullName>Electrical Upgrade Required</fullName>
            </value>
            <value>
                <fullName>Design Change</fullName>
                <label>Engineering / Design Change</label>
            </value>
            <value>
                <fullName>Financier Hard Stipulations</fullName>
            </value>
            <value>
                <fullName>Financier Multiple Hard Stipulations</fullName>
            </value>
            <value>
                <fullName>Financier Soft Stipulation</fullName>
            </value>
            <value>
                <fullName>Financier Stipulation</fullName>
            </value>
            <value>
                <fullName>HOA Denial</fullName>
            </value>
            <value>
                <fullName>Multiple Items to be Addressed</fullName>
            </value>
            <value>
                <fullName>Reroof / Tree Removal Delay</fullName>
                <label>Reroof</label>
            </value>
            <value>
                <fullName>Structural Issues</fullName>
            </value>
            <value>
                <fullName>Sunnova Back End Change</fullName>
            </value>
            <value>
                <fullName>Sunnova Customer Facing Change</fullName>
            </value>
            <value>
                <fullName>Tree Removal Delay</fullName>
            </value>
            <value>
                <fullName>Utility Denial</fullName>
            </value>
            <value>
                <fullName>Virtual Survey Incomplete</fullName>
            </value>
            <value>
                <fullName>Engineer Denial</fullName>
                <isActive>false</isActive>
                <label>Engineer Denial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of contact associated with opportunity</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Date__c</fullName>
    <label>Contract Received Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Customer_Care_Representative__c.field-meta.xml
<CustomField>
    <fullName>Customer_Care_Representative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Care Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opp_Customer_Care_Specialist</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Engineering_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Engineering_Complete_Date__c</fullName>
    <label>Engineering Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Engineering_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Engineering_Sent_Date__c</fullName>
    <label>Engineering Sent Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Equipment_Ordered_Date__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Ordered_Date__c</fullName>
    <label>Equipment Ordered Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/HOA_Appeal__c.field-meta.xml
<CustomField>
    <fullName>HOA_Appeal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HOA Denial</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/HOA_Application_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>HOA_Application_Sent_Date__c</fullName>
    <label>HOA  ApplicationSent for Submittal</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/HOA_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>HOA_Approval_Date__c</fullName>
    <label>HOA Approval Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Home_Owners_Association__c.field-meta.xml
<CustomField>
    <fullName>Home_Owners_Association__c</fullName>
    <label>Home Owners Association</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Inspection_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Inspection_Completed_Date__c</fullName>
    <label>Inspection Scheduled Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Install_Ready_Date__c.field-meta.xml
<CustomField>
    <fullName>Install_Ready_Date__c</fullName>
    <label>Install Ready Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Start_Date__c</fullName>
    <label>Installation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Interconnection_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Interconnection_Sent_Date__c</fullName>
    <label>Interconnection Sent Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Net_Meter_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Net_Meter_Install_Date__c</fullName>
    <label>PTO / Net Meter Install Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Palmetto_Home_App_Downloaded__c.field-meta.xml
<CustomField>
    <fullName>Palmetto_Home_App_Downloaded__c</fullName>
    <description>date of which the Palmetto home app was downloaded by the homeowner</description>
    <label>Palmetto Home App Downloaded</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Permit_Filed_Date__c.field-meta.xml
<CustomField>
    <fullName>Permit_Filed_Date__c</fullName>
    <label>Permit Filed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Permit_Rec_d_Date__c.field-meta.xml
<CustomField>
    <fullName>Permit_Rec_d_Date__c</fullName>
    <label>Permit Rec'd Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Reason_for_loss__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_loss__c</fullName>
    <label>Reason for Loss</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled with Finance Partner</fullName>
            </value>
            <value>
                <fullName>Customer unresponsive</fullName>
            </value>
            <value>
                <fullName>Decided against Solar</fullName>
            </value>
            <value>
                <fullName>Decreased production after redesign</fullName>
            </value>
            <value>
                <fullName>Desires Lead Gen Service</fullName>
            </value>
            <value>
                <fullName>Didn't want it on Front of House</fullName>
            </value>
            <value>
                <fullName>Dislike Comp Structure</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Doesn't like subscription</fullName>
            </value>
            <value>
                <fullName>Doesn't like upfront install cost</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Didn't pass credit</fullName>
                <label>Finance Stipulation or Credit Issue</label>
            </value>
            <value>
                <fullName>Has EM already</fullName>
            </value>
            <value>
                <fullName>HOA Denied</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Moving Out of the Area</fullName>
            </value>
            <value>
                <fullName>Needs rescheduling</fullName>
            </value>
            <value>
                <fullName>Never agreed to appointment</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>No Solar Experience</fullName>
            </value>
            <value>
                <fullName>Not able to Use Tax Credits/Incentives</fullName>
            </value>
            <value>
                <fullName>Not a single family home</fullName>
            </value>
            <value>
                <fullName>Not enough Savings</fullName>
                <label>Not Enough Savings/ROI too Long</label>
            </value>
            <value>
                <fullName>Not in right utility service area</fullName>
            </value>
            <value>
                <fullName>Opportunity Clean-up</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Roof/Structural Total DQ</fullName>
            </value>
            <value>
                <fullName>Roof Issues</fullName>
                <label>Roof Issues-Addressable</label>
            </value>
            <value>
                <fullName>Moving to a New Home</fullName>
                <label>Selling Home Soon</label>
            </value>
            <value>
                <fullName>Shading</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SA_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>SA_Approved_Date__c</fullName>
    <label>System Activation (M2) Approved Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Signed_NMA_Rec_d_Date__c.field-meta.xml
<CustomField>
    <fullName>Signed_NMA_Rec_d_Date__c</fullName>
    <label>ICA Approved Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Site_Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Site_Approved_Date__c</fullName>
    <label>Site Approved Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Site_Audit_Completed__c.field-meta.xml
<CustomField>
    <fullName>Site_Audit_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Site Audit Completed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Site_Audit_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Site_Audit_Completed_Date__c</fullName>
    <label>Site Audit Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Site_Audit_FieldCompleted_Date__c.field-meta.xml
<CustomField>
    <fullName>Site_Audit_FieldCompleted_Date__c</fullName>
    <label>Site Audit Field Completed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Site_Audit_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Site_Audit_Order_Date__c</fullName>
    <label>Site Audit Completed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/SolarEdge_Site_ID__c.field-meta.xml
<CustomField>
    <fullName>SolarEdge_Site_ID__c</fullName>
    <formula>Contact__r.SolarEdge_Site_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SolarEdge Site ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/X18_Character_Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>X18_Character_Opportunity_ID__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <label>18 Character Opportunity ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/HomeCustomerUpdate.cls
global class HomeCustomerUpdate{
    
    public static Boolean runOnce = false;
    //This method is called on after update event of trigger.
    public void onAfterUpdate(List<Opportunity> lstOpp, Map<Id, Opportunity> mapIdToOldOpp){
        Set<Id> setOpportunityId = new Set<Id>();
        Id designSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        for(Opportunity objOpp : lstOpp){
            Opportunity objOldOpp = mapIdToOldOpp.get(objOpp.Id);
            if(objOpp.StageName != objOldOpp.StageName && objOpp.RecordTypeId == designSalesId){
                setOpportunityId.add(objOpp.Id);
            }
        }
        System.debug('>>>>>>'+setOpportunityId);
        if(!setOpportunityId.isEmpty()){
            if(runOnce == false){
                runOnce = true;
                for(Id oppId : setOpportunityId){
                    CustomerUpdate(oppId);
                }
            }
        }
    }


    @future (callout=true)
    public static void CustomerUpdate(id oppId) {
        try
        {   
            // kalidass
            /*
            Opportunity oppHome=[select SolarEdge_Site_ID__c,Palmetto_Home_App_Downloaded__c,Site_Audit_FieldCompleted_Date__c,Customer_Care_Representative__c,
                    HOA_Appeal__c, Site_Audit_Completed_Date__c,Site_Audit_Completed__c,Site_Approved_Date__c,Home_Owners_Association__c,Reason_for_loss__c,
                    HOA_Application_Sent_Date__c,HOA_Approval_Date__c,Engineering_Sent_Date__c,Engineering_Complete_Date__c,
                    NM_App_Rec_d_Date__c,Permit_Filed_Date__c,Signed_NMA_Rec_d_Date__c,Permit_Rec_d_Date__c,Equipment_Ordered_Date__c,
                    Install_Ready_Date__c,Installation_Start_Date__c,Installation_Complete_Date__c,Inspection_Completed_Date__c,
                    Net_Meter_Install_Date__c,SA_Approved_Date__c,StageName,Contact__c,Name,id,RecordType.Name 
                    from Opportunity where id=:oppId];
                    
            String JsonStringHome = JSON.serialize(oppHome);
            system.debug('>>>>>>>>'+JsonStringHome);
            if(oppHome.RecordType.Name != 'Energy Monitor'){
                HTTPResponse resHome = getInfoFromExternalService(JsonStringHome,'https://alchemy.palmetto.com/api/updateUserOpportunity');
                //HTTPResponse resHome = getInfoFromExternalService(JsonStringHome,'https://legacy-home-next.palmetto.com/api/updateUserOpportunity');
                //HTTPResponse resHome = getInfoFromExternalService(JsonStringHome,'https://legacy-home.palmetto.com/api/updateUserOpportunity'); 
                //system.debug('>>>>>>>>>'+resHome.getBody());
            }*/
            //end 
            //SOQL to construct JSON string in set body
            Opportunity opp = [select id,X18_Character_Opportunity_ID__c,StageName,RecordTypeId,Email__c,Contact__c,
                    Contract_Received_Date__c,Change_Order_Reason__c,Site_Audit_Order_Date__c,Site_Audit_FieldCompleted_Date__c,
                    Interconnection_Sent_Date__c,Permitting_Jurisdiction__c,Proposed_Installation_Date__c,Installation_Complete_Date__c,
                    Utility__c,Reason_for_loss__c,Other_Reason_for_Loss__c,Installation_Start_Date__c 
                    from Opportunity where id=:oppId]; 
                    
            String JsonString = JSON.serialize(opp);
            String status = '';
            String code = '';
            //Below code added by Prakash for Alchemy SF triggers
            system.debug('>>>>>>>'+JsonString);  
            String endPoint = System.Label.Alchemy_End_Point;           
            //HTTPResponse res1 = getInfoFromExternalService(JsonString,'https://alchemy-next.palmetto.com/updateOpportunityStatus');
            HTTPResponse res1 = getInfoFromExternalService(JsonString, endPoint);
            system.debug('>>>>>>>'+res1.getBody());             
            /*Id designSalesId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
            Id oppProcessId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Opportunity - Process').getRecordTypeId();
            Id energyMotorId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Energy Monitor').getRecordTypeId();
            if(((opp.RecordTypeId == designSalesId || opp.RecordTypeId == oppProcessId)&&(opp.StageName == '7a. Contract Received Confirmed' || opp.StageName == '22. PTO')) || (opp.RecordTypeId ==  energyMotorId && opp.StageName == 'EM4 Payment/Contract Received'))
            {
                system.debug('serialized JSON'+JSON.serialize(opp));
                system.debug('>>>>>>>'+JsonString);             
                HTTPResponse res = getInfoFromExternalService(JsonString,'https://alchemy.palmetto.com/api/upgradeuser');
                //HTTPResponse res = getInfoFromExternalService(JsonString,'https://legacy-home-next.palmetto.com/api/upgradeuser');
                //HTTPResponse res = getInfoFromExternalService(JsonString,'https://legacy-home.palmetto.com/api/upgradeuser');
                
                System.debug('>>>>>'+res.getBody());
                status =  CheckResponse('status',res);
                code = CheckResponse('code',res);             
                
                if (status != 'true' || code != '1' || res.getStatusCode() != 200)
                {
                    //SendEmail(JsonString);
                }
            }*/
            // Below code added by Kalidass for store Opportunity values in Home 
        }
        catch (Exception e){
            SendEmail( 'Exception' + e + '\n Opportunity Id = ' +  oppId);
        } 
    }
    public static String CheckResponse(String FieldName,HTTPResponse res )
    {
        JSONParser parser = JSON.createParser(res.getBody());
        string result = '';
        while (parser.nextToken() != null) 
        { 
            if (parser.getCurrentToken() == JSONToken.FIELD_NAME) 
            {
                String field= parser.getText();
                parser.nextToken();
                if (field == FieldName) 
                {
                    result =  parser.getText();
                    break;
                }                      
            }
        }
        return result;
    }
    
    
    public static HttpResponse getInfoFromExternalService(String jsonstr,String url)
    {
        //Construct HTTP request and response
        //Http request method,Endpoint and setBody
        HttpRequest req = new HttpRequest();
        req.setTimeout(20000);
        req.setHeader('Content-Type','application/json');
        String endpoint = url;
        req.setMethod('POST');
        req.setEndpoint(endpoint); 
        req.setBody(jsonstr);
        //Http response method 
        Http http = new Http();
        return http.send(req);
    }
    public static void SendEmail(String MailBody) 
    {
        List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> sendTo = new List<String>();
        //sendTo.add('mkpkarthiktest1@gmail.com');
        sendTo.add('technologyteam@palmetto.com');
        sendTo.add('bhargav.rentala@palmetto.com');
        mail.setReplyTo('alchemy@palmettoventures.com');
        mail.setSubject('URGENT SF Trigger Issue');
        //String body = 'Exception Details ' + e ;
        mail.setToAddresses(sendTo);
        mail.setHtmlBody(MailBody);
        mails.add(mail);
        Messaging.sendEmail(mails);
    }    
}