unpackaged/main/default/objects/Opportunity/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Channel Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Opp_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Opp_Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Do NOT designate CUSTOMER contact.</inlineHelpText>
    <label>Opp Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Opp Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PopulateChannelPartner.cls
global class PopulateChannelPartner implements Database.Batchable<SObject> {
    /*****************Batchable Interface Methods*****************/
    global Database.QueryLocator start(Database.BatchableContext context) {
        //String query = 'SELECT Id, Opp_Primary_Contact__r.AccountId from Opportunity '; 
        //query += 'where Channel_Partner__c = null AND Opp_Primary_Contact__r.AccountId != null';
        String query = Label.OppQuery;
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext context, List<Opportunity> lstOpportunity) {
        for(Opportunity objOpp : lstOpportunity){
            objOpp.Channel_Partner__c = objOpp.Opp_Primary_Contact__r.AccountId;
        }
        
        if(!lstOpportunity.isEmpty())
            Database.update(lstOpportunity, false);
    }
    
    global void finish(Database.BatchableContext context) {}
}