unpackaged/main/default/objects/Opportunity/fields/Contract_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Received_Date__c</fullName>
    <label>Contract Received Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Financing_Tool__c.field-meta.xml
<CustomField>
    <fullName>Financing_Tool__c</fullName>
    <label>Financing Tool</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Dividend Loan</fullName>
            </value>
            <value>
                <fullName>Financed</fullName>
            </value>
            <value>
                <fullName>Loanpal</fullName>
            </value>
            <value>
                <fullName>Loan Pal - SubPrime</fullName>
            </value>
            <value>
                <fullName>Mosaic Loan</fullName>
            </value>
            <value>
                <fullName>Operations Only</fullName>
            </value>
            <value>
                <fullName>Rocket</fullName>
            </value>
            <value>
                <fullName>Sunlight</fullName>
            </value>
            <value>
                <fullName>Sunnova Lease</fullName>
            </value>
            <value>
                <fullName>Sunnova Loan/Ownership</fullName>
            </value>
            <value>
                <fullName>SunRun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Installation_Complete_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Complete_Date__c</fullName>
    <label>Installation Complete Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/CreateFinanceJobBatchTest.cls
@isTest
private class CreateFinanceJobBatchTest
{
    static testMethod void unitTest(){
        Id designSalesId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Account objAccount = TestDataFactory.createAccount('Test Acc', designSalesId);
        objAccount.celigo_sfnsio__Account_Balance__c = 100;
        insert objAccount;
         
        Id designSalesOppId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('3rd Party - Design Sales').getRecordTypeId();
        Opportunity objOpp = TestDataFactory.createOpportunity(designSalesOppId, 'Test opp', objAccount.Id, '12. Install Complete' , 'NY');
        objOpp.Installation_Complete_Date__c = Date.today();
        objOpp.Contract_Received_Date__c = Date.today();
        objOpp.Financing_Tool__c = 'Loanpal';
        insert objOpp;
        
        Database.executeBatch(new CreateFinanceJobBatch());
    }
}