unpackaged/main/default/objects/Operations_Input__c/Operations_Input__c.object-meta.xml
<CustomObject>
    <label>Operations Input</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Operations Input Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Operations_Input__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Operations Inputs</relationshipLabel>
    <relationshipName>Operations_Inputs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Service_Agreement__c/Service_Agreement__c.object-meta.xml
<CustomObject>
    <label>Service Agreement</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Service Agreement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Agreement__c/fields/Active_MSA_Flag__c.field-meta.xml
<CustomField>
    <fullName>Active_MSA_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active MSA Flag</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Service_Agreement__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <label>Vendor</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Service Agreements</relationshipLabel>
    <relationshipName>Service_Agreements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Service_Agreement__c/fields/Vendor_Email__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Email__c</fullName>
    <formula>Vendor__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Service_Agreement__c/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <formula>Vendor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Service_Agreement__c/fields/Vendor_Onboarding_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Onboarding_Status__c</fullName>
    <formula>TEXT(Vendor__r.Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Onboarding Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Service_Agreement__c/fields/Vendor_Phone__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Phone__c</fullName>
    <formula>Vendor__r.Mobile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Phone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ServiceAgreementHandler.cls
public class ServiceAgreementHandler
{
    //This method is called on after insert event of trigger.
    public void onAfterInsert(List<Service_Agreement__c> lstServiceAgreement){
        createServiceProvider(lstServiceAgreement, null);
    }
    //This method is called on after update event of trigger.
    public void onAfterUpdate(List<Service_Agreement__c> lstServiceAgreement, Map<Id, Service_Agreement__c> mapIdToOldAgreement){
        createServiceProvider(lstServiceAgreement, mapIdToOldAgreement);
    }
    /*
    //This method is called to create operational input record.
    private void createOperationInput(List<Service_Agreement__c> lstServiceAgreement){
        List<Operations_Input__c> lstOperationsInput = new List<Operations_Input__c>();
        for(Service_Agreement__c objServiceAgreement : lstServiceAgreement){
            Operations_Input__c objOperationsInput = new Operations_Input__c();
            objOperationsInput.Service_Agreement__c = objServiceAgreement.Id;
            lstOperationsInput.add(objOperationsInput);
        }
        
        if(!lstOperationsInput.isEmpty())
            insert lstOperationsInput;
    }
    */
    //This method is used to create service provider record.
    private void createServiceProvider(List<Service_Agreement__c> lstServiceAgreement, Map<Id, Service_Agreement__c> mapIdToOldAgreement){
        /*
        List<dispconn__Service_Provider__c> lstServiceProvoider = new List<dispconn__Service_Provider__c>();
        for(Service_Agreement__c objServiceAgreement : lstServiceAgreement){
            if(objServiceAgreement.Active_MSA_Flag__c == true && (objServiceAgreement.Vendor_Onboarding_Status__c == 'Account Approved' || objServiceAgreement.Vendor_Onboarding_Status__c == 'Approved')){
                Boolean criteriaSatisfied = false;
                if(mapIdToOldAgreement == null){
                    criteriaSatisfied = true;
                } else{
                    Service_Agreement__c objOldAgreement = mapIdToOldAgreement.get(objServiceAgreement.Id);
                    if(objOldAgreement.Active_MSA_Flag__c == false){
                        criteriaSatisfied = true;
                    }
                }
                if(criteriaSatisfied){
                    dispconn__Service_Provider__c objServiceProvider = new dispconn__Service_Provider__c();
                    objServiceProvider.Name = objServiceAgreement.Vendor_Name__c + ' - ' + objServiceAgreement.State__c;
                    objServiceProvider.Service_Agreement__c = objServiceAgreement.Id;
                    objServiceProvider.Vendor__c = objServiceAgreement.Vendor__c;
                    objServiceProvider.dispconn__Email__c = objServiceAgreement.Vendor_Email__c;
                    objServiceProvider.dispconn__Phone__c = objServiceAgreement.Vendor_Phone__c;
                    lstServiceProvoider.add(objServiceProvider);
                }
            }            
        }
        try{
            if(!lstServiceProvoider.isEmpty())
                Database.insert(lstServiceProvoider, false);
        } catch(Exception e){}*/
    }
}