unpackaged/main/default/objects/Operations_Input__c/Operations_Input__c.object-meta.xml
<CustomObject>
    <label>Operations Input</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Operations Input Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operations Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Operations_Input__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <label>Service Agreement</label>
    <referenceTo>Service_Agreement__c</referenceTo>
    <relationshipLabel>Operations Inputs</relationshipLabel>
    <relationshipName>Operations_Inputs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Service_Agreement__c/Service_Agreement__c.object-meta.xml
<CustomObject>
    <label>Service Agreement</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Service Agreement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ServiceProviderHandler.cls
public class ServiceProviderHandler
{
    //This method is called on after insert event of trigger.
    public void onAfterInsert(List<dispconn__Service_Provider__c> lstServiceProvider){
        createOperationInput(lstServiceProvider);
    }
    //This method is called to create operational input record.
    private void createOperationInput(List<dispconn__Service_Provider__c> lstServiceProvider){
        /*List<Operations_Input__c> lstOperationsInput = new List<Operations_Input__c>();
        for(dispconn__Service_Provider__c objServiceProvider : lstServiceProvider){
            Operations_Input__c objOperationsInput = new Operations_Input__c();
            objOperationsInput.Service_Agreement__c = objServiceProvider.Service_Agreement__c;
            lstOperationsInput.add(objOperationsInput);
        }
        
        if(!lstOperationsInput.isEmpty())
            insert lstOperationsInput;*/
    }
}