unpackaged/main/default/objects/AccountTeamMember/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Created to identify the Build Partner Market Manager and Regional Director</description>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Build Partner</label>
    <referenceTo>Vendor__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vendor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor</relationshipLabel>
    <relationshipName>Vendor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/State.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <customValue>
        <fullName>New Jersey</fullName>
    </customValue>
    <masterLabel>State</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountTeamMemberHandler.cls
public with sharing class AccountTeamMemberHandler {
    public void onAfterInsert(List<AccountTeamMember> listAccTM){
        List<AccountTeamMember> accTmToCearteOppTM = new List<AccountTeamMember>();
        for(AccountTeamMember objAccTM : listAccTM){
            if(objAccTM.TeamMemberRole == 'Market Manager'){
                accTmToCearteOppTM.add(objAccTM);   
            }
        }
        if(!accTmToCearteOppTM.isEmpty()){
            createOppTeamMember(accTmToCearteOppTM);
        }
    }

    public void onAfterDelete(List<AccountTeamMember> listAccTM){
        List<AccountTeamMember> accTmToDeleteOppTM = new List<AccountTeamMember>();
        for(AccountTeamMember objAccTM : listAccTM){
            if(objAccTM.TeamMemberRole == 'Market Manager'){
                accTmToDeleteOppTM.add(objAccTM);   
            }
        }
        if(!accTmToDeleteOppTM.isEmpty()){
            deleteOppTeamMember(accTmToDeleteOppTM);
        }
    }

    public void onAfterUpdate(List<AccountTeamMember> listAccTM, Map<Id,AccountTeamMember> mapOldAccTM){
        List<AccountTeamMember> accTmToCearteOppTM = new List<AccountTeamMember>();
        List<AccountTeamMember> accTmToDeleteOppTM = new List<AccountTeamMember>();
        List<AccountTeamMember> accTmToUpdateStates = new List<AccountTeamMember>();
        for(AccountTeamMember objAccTM : listAccTM){
            if((objAccTM.TeamMemberRole == 'Market Manager' && mapOldAccTM.get(objAccTM.Id).TeamMemberRole != 'Market Manager')){
                accTmToCearteOppTM.add(objAccTM);
            }
            else if(objAccTM.TeamMemberRole != 'Market Manager' && mapOldAccTM.get(objAccTM.Id).TeamMemberRole == 'Market Manager'){
                accTmToDeleteOppTM.add(objAccTM);
            }
            if(objAccTM.State__c != null && objAccTM.State__c != mapOldAccTM.get(objAccTm.Id).State__c){
                accTmToUpdateStates.add(objAccTM);
            }
        }
        if(!accTmToCearteOppTM.isEmpty()){
            createOppTeamMember(accTmToCearteOppTM);
        }
        if(!accTmToDeleteOppTM.isEmpty()){
            deleteOppTeamMember(accTmToDeleteOppTM);
        }
        if(!accTmToUpdateStates.isEmpty()){
            updateOppTeamMemberByState(accTmToUpdateStates);
        }
    }

    private void createOppTeamMember(List<AccountTeamMember> listAccTM){
        Set<Id> accIds = new Set<Id>();
        Map<Id, AccountTeamMember> mapAccTMByAccId = new Map<Id, AccountTeamMember>();
        for(AccountTeamMember objAccTM : listAccTM){
            accIds.add(objAccTM.AccountId);
            mapAccTMByAccId.put(objAccTM.AccountId,objAccTM);
        }
        List<OpportunityTeamMember> listOppTM = new List<OpportunityTeamMember>();
        List<Opportunity> listOpps = [SELECT Id, Location__c, Vendor__r.Account__c FROM Opportunity WHERE Vendor__r.Account__c IN :accIds];
        for(Opportunity objOpp : listOpps){
            if(mapAccTMByAccId.containsKey(objOpp.Vendor__r.Account__c) && mapAccTMByAccId.get(objOpp.Vendor__r.Account__c).State__c != null && mapAccTMByAccId.get(objOpp.Vendor__r.Account__c).State__c.contains(objOpp.Location__c)){
                listOppTM.add(new OpportunityTeamMember(
                                    TeamMemberRole = 'Market Manager',
                                    UserId = mapAccTMByAccId.get(objOpp.Vendor__r.Account__c).UserId,
                                    OpportunityId = objOpp.Id
                                ));
            }
        }
        if(!listOppTM.isEmpty()){
            insert listOppTM;
        }
    }

    private void deleteOppTeamMember(List<AccountTeamMember> listAccTM){
        Set<Id> usrIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Map<Id, AccountTeamMember> mapAccTMbyAccId = new Map<Id,AccountTeamMember>();
        Map<Id, AccountTeamMember> mapAccTMbyUserId = new Map<Id,AccountTeamMember>();
        for(AccountTeamMember objAccTM : listAccTM){
            usrIds.add(objAccTM.UserId);
            accIds.add(objAccTM.AccountId);
            mapAccTMbyAccId.put(objAccTM.AccountId, objAccTM);
            mapAccTMbyUserId.put(objAccTM.UserId, objAccTM);
        }
        List<Opportunity> listOpps = [
            SELECT Id, Vendor__r.Account__c,
            (
                SELECT Id, UserId
                FROM OpportunityTeamMembers
                WHERE TeamMemberRole = 'Market Manager'
                AND UserId IN :usrIds
            )
            FROM Opportunity
            WHERE Vendor__r.Account__c IN :accIds
        ];
        List<OpportunityTeamMember> listOppTMForDeletion = new List<OpportunityTeamMember>();
        for(Opportunity objOpp : listOpps){
            if(mapAccTMbyAccId.containsKey(objOpp.Vendor__r.Account__c) && !objOpp.OpportunityTeamMembers.isEmpty()){
                for(OpportunityTeamMember objOppTM : objOpp.OpportunityTeamMembers){
                    if(mapAccTMbyUserId.containsKey(objOppTM.UserId)){
                        listOppTMForDeletion.add(objOppTM);
                    }
                }
            }
        }
        if(!listOppTMForDeletion.isEmpty()){
            delete listOppTMForDeletion;
        }
    }

    private void updateOppTeamMemberByState(List<AccountTeamMember> listAccTM){
        Set<Id> usrIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Map<Id, AccountTeamMember> mapAccTMbyAccId = new Map<Id,AccountTeamMember>();
        Map<Id, AccountTeamMember> mapAccTMbyUserId = new Map<Id,AccountTeamMember>();
        for(AccountTeamMember objAccTM : listAccTM){
            usrIds.add(objAccTM.UserId);
            accIds.add(objAccTM.AccountId);
            mapAccTMbyAccId.put(objAccTM.AccountId, objAccTM);
            mapAccTMbyUserId.put(objAccTM.UserId, objAccTM);
        }
        List<Opportunity> listOpps = [
            SELECT Id, Vendor__r.Account__c, Location__c,
            (
                SELECT Id, UserId
                FROM OpportunityTeamMembers
                WHERE TeamMemberRole = 'Market Manager'
                AND UserId IN :usrIds
            )
            FROM Opportunity
            WHERE Vendor__r.Account__c IN :accIds
        ];
        List<OpportunityTeamMember> listOppTMForDeletion = new List<OpportunityTeamMember>();
        List<OpportunityTeamMember> listOppTMForCreation = new List<OpportunityTeamMember>();
        for(Opportunity objOpp : listOpps){
            if(mapAccTMbyAccId.containsKey(objOpp.Vendor__r.Account__c) &&
                !mapAccTMbyAccId.get(objOpp.Vendor__r.Account__c).State__c.contains(objOpp.Location__c) &&
                !objOpp.OpportunityTeamMembers.isEmpty()){

                for(OpportunityTeamMember objOppTM : objOpp.OpportunityTeamMembers){
                    if(objOppTM.UserId == mapAccTMbyAccId.get(objOpp.Vendor__r.Account__c).UserId){
                        listOppTMForDeletion.add(objOppTM);
                    }
                }
            }else if((mapAccTMbyAccId.containsKey(objOpp.Vendor__r.Account__c) &&
            mapAccTMbyAccId.get(objOpp.Vendor__r.Account__c).State__c.contains(objOpp.Location__c))){
                Boolean createOppTm = true;
                if(!objOpp.OpportunityTeamMembers.isEmpty()){
                    for(OpportunityTeamMember objOppTM : objOpp.OpportunityTeamMembers){
                        if(objOppTM.UserId == mapAccTMbyAccId.get(objOpp.Vendor__r.Account__c).UserId){
                            createOppTm = false;
                        }
                    }
                }
                if(createOppTm){
                    listOppTMForCreation.add(new OpportunityTeamMember(
                                    TeamMemberRole = 'Market Manager',
                                    UserId = mapAccTMByAccId.get(objOpp.Vendor__r.Account__c).UserId,
                                    OpportunityId = objOpp.Id
                                ));
                }
            }
        }
        if(!listOppTMForDeletion.isEmpty()){
            delete listOppTMForDeletion;
        }
        if(!listOppTMForCreation.isEmpty()){
            insert listOppTMForCreation;
        }
    }
}